### ISSUE TITLE
Open failed: EACCES (Permission denied) on the self-signed certificate

### ISSUE THREAD

**Issue by reuseman** [emansih/FireflyMobile#109]
**Firefly III Server Version:**  5.3.3

**Firefly III Mobile Version:** 2.1.2

**Android Version:** 10

**Device Information:**  

- BRAND: Xiaomi
- MODEL:  Mi 9T Pro
--------------------------------------

## Expected Behavior
It should open the certificate. The app has permission to access to the storage

## Current Behavior
Crash

## Steps to Reproduce
1. Sign with OAUTH
2. Fill the fields
3. Check the checkbox to load the self-signed certificate
4. Select the default explorer in the page and open the certificate

`REPORT_ID=02818f9b-c0a9-4271-b4c1-45fc6b85687d
APP_VERSION_NAME=2.1.2
PHONE_MODEL=Mi 9T Pro
BRAND=Xiaomi
PRODUCT=raphael
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
	... 1 more
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/firefly-server.pem: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:496)
	at java.io.FileInputStream.<init>(FileInputStream.java:159)
	at java.io.FileInputStream.<init>(FileInputStream.java:115)
	at java.io.FileReader.<init>(FileReader.java:58)
	at xyz.hisname.fireflyiii.util.FileUtils.saveCaFile(FileUtils.kt:1)
	at xyz.hisname.fireflyiii.ui.onboarding.LoginFragment$getAccessCode$1.onClick(LoginFragment.kt:12)
	at android.view.View.performClick(View.java:7252)
	at android.view.View.performClickInternal(View.java:7229)
	at android.view.View.access$3500(View.java:821)
	at android.view.View$PerformClick.run(View.java:27765)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:7551)
	... 3 more
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
	at libcore.io.Linux.open(Native Method)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7450)
	at libcore.io.IoBridge.open(IoBridge.java:482)
	... 16 more

LOGCAT=--------- beginning of system
08-17 10:57:49.660 I/Timeline( 6274): Timeline: Activity_launch_request time:70928
08-17 10:57:50.191 W/Looper  ( 6274): Slow Looper main: Activity xyz.hisname.fireflyiii/.ui.onboarding.OnboardingActivity is 454ms late (wall=0ms running=0ms ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] }) because of 4 msg, msg 4 took 453ms (seq=9 running=32ms runnable=9ms io=25ms late=2ms h=android.app.ActivityThread$H w=159)
08-17 10:57:54.666 I/Timeline( 6274): Timeline: Activity_launch_request time:75935
08-17 10:58:01.413 I/Timeline( 6274): Timeline: Activity_launch_request time:82682
--------- beginning of main
08-17 11:00:26.888 D/AppCompatDelegate( 6274): updateForNightMode [allowRecreation:true, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:true, canReturnDifferentContext:true, host:xyz.hisname.fireflyiii.ui.onboarding.OnboardingActivity@2fc89eb]
08-17 11:00:26.888 D/AppCompatDelegate( 6274): updateForNightMode not recreating Activity: xyz.hisname.fireflyiii.ui.onboarding.OnboardingActivity@2fc89eb
08-17 11:00:26.888 D/AppCompatDelegate( 6274): updateForNightMode. Skipping. Night mode: 1 for host:xyz.hisname.fireflyiii.ui.onboarding.OnboardingActivity@2fc89eb
08-17 11:00:26.912 I/AssistStructure( 6274): Flattened final assist data: 4648 bytes, containing 1 windows, 28 views
08-17 11:00:27.022 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:27.025 I/chatty  ( 6274): uid=10390(xyz.hisname.fireflyiii) identical 8 lines
08-17 11:00:27.025 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:35.971 D/AppCompatDelegate( 6274): updateForNightMode [allowRecreation:true, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:true, canReturnDifferentContext:true, host:xyz.hisname.fireflyiii.ui.onboarding.OnboardingActivity@2fc89eb]
08-17 11:00:35.971 D/AppCompatDelegate( 6274): updateForNightMode not recreating Activity: xyz.hisname.fireflyiii.ui.onboarding.OnboardingActivity@2fc89eb
08-17 11:00:35.971 D/AppCompatDelegate( 6274): updateForNightMode. Skipping. Night mode: 1 for host:xyz.hisname.fireflyiii.ui.onboarding.OnboardingActivity@2fc89eb
08-17 11:00:36.108 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:36.111 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:37.385 W/BpBinder( 6274): Slow Binder: BpBinder transact took 261ms, interface=android.app.IActivityManager, code=20 oneway=false
08-17 11:00:38.082 W/InputEventReceiver( 6274): Attempted to finish an input event but the input event receiver has already been disposed.
08-17 11:00:38.735 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:38.740 I/chatty  ( 6274): uid=10390(xyz.hisname.fireflyiii) identical 4 lines
08-17 11:00:38.741 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:40.993 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:40.994 I/chatty  ( 6274): uid=10390(xyz.hisname.fireflyiii) identical 1 line
08-17 11:00:40.994 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:40.999 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:41.000 I/chatty  ( 6274): uid=10390(xyz.hisname.fireflyiii) identical 1 line
08-17 11:00:41.000 W/View    ( 6274): couldn't find view with id 2131362628
08-17 11:00:51.946 W/BpBinder( 6274): Slow Binder: BpBinder transact took 335ms, interface=android.app.IActivityManager, code=20 oneway=false
08-17 11:00:51.957 D/AndroidRuntime( 6274): Shutting down VM
--------- beginning of crash
08-17 11:00:51.962 E/AndroidRuntime( 6274): FATAL EXCEPTION: main
08-17 11:00:51.962 E/AndroidRuntime( 6274): Process: xyz.hisname.fireflyiii, PID: 6274
08-17 11:00:51.962 E/AndroidRuntime( 6274): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
08-17 11:00:51.962 E/AndroidRuntime( 6274): Caused by: java.lang.reflect.InvocationTargetException
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at java.lang.reflect.Method.invoke(Native Method)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	... 1 more
08-17 11:00:51.962 E/AndroidRuntime( 6274): Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/firefly-server.pem: open failed: EACCES (Permission denied)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at libcore.io.IoBridge.open(IoBridge.java:496)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at java.io.FileReader.<init>(FileReader.java:58)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at xyz.hisname.fireflyiii.util.FileUtils.saveCaFile(FileUtils.kt:1)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at xyz.hisname.fireflyiii.ui.onboarding.LoginFragment$getAccessCode$1.onClick(LoginFragment.kt:12)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.view.View.performClick(View.java:7252)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.view.View.performClickInternal(View.java:7229)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.view.View.access$3500(View.java:821)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.view.View$PerformClick.run(View.java:27765)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.os.Handler.handleCallback(Handler.java:883)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.os.Looper.loop(Looper.java:224)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	... 3 more
08-17 11:00:51.962 E/AndroidRuntime( 6274): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at libcore.io.Linux.open(Native Method)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7450)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	at libcore.io.IoBridge.open(IoBridge.java:482)
08-17 11:00:51.962 E/AndroidRuntime( 6274): 	... 16 more
08-17 11:00:51.969 E/ACRA    ( 6274): ACRA caught a RuntimeException for xyz.hisname.fireflyiii
08-17 11:00:51.969 E/ACRA    ( 6274): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
08-17 11:00:51.969 E/ACRA    ( 6274): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
08-17 11:00:51.969 E/ACRA    ( 6274): Caused by: java.lang.reflect.InvocationTargetException
08-17 11:00:51.969 E/ACRA    ( 6274): 	at java.lang.reflect.Method.invoke(Native Method)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
08-17 11:00:51.969 E/ACRA    ( 6274): 	... 1 more
08-17 11:00:51.969 E/ACRA    ( 6274): Caused by: java.io.FileNotFoundException: /storage/emulated/0/Download/firefly-server.pem: open failed: EACCES (Permission denied)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at libcore.io.IoBridge.open(IoBridge.java:496)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at java.io.FileInputStream.<init>(FileInputStream.java:115)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at java.io.FileReader.<init>(FileReader.java:58)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at xyz.hisname.fireflyiii.util.FileUtils.saveCaFile(FileUtils.kt:1)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at xyz.hisname.fireflyiii.ui.onboarding.LoginFragment$getAccessCode$1.onClick(LoginFragment.kt:12)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.view.View.performClick(View.java:7252)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.view.View.performClickInternal(View.java:7229)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.view.View.access$3500(View.java:821)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.view.View$PerformClick.run(View.java:27765)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.os.Handler.handleCallback(Handler.java:883)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.os.Handler.dispatchMessage(Handler.java:100)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.os.Looper.loop(Looper.java:224)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.app.ActivityThread.main(ActivityThread.java:7551)
08-17 11:00:51.969 E/ACRA    ( 6274): 	... 3 more
08-17 11:00:51.969 E/ACRA    ( 6274): Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at libcore.io.Linux.open(Native Method)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7450)
08-17 11:00:51.969 E/ACRA    ( 6274): 	at libcore.io.IoBridge.open(IoBridge.java:482)
08-17 11:00:51.969 E/ACRA    ( 6274): 	... 16 more

IS_SILENT=false
USER_CRASH_DATE=2020-08-17T11:00:51.974+02:00`

**Comment by emansih** [comment]
I'm using Mi 9T pro 
![Screenshot](https://user-images.githubusercontent.com/5896415/90380980-16dac480-e0c0-11ea-9994-329daf1a2d08.jpg)

**Comment by emansih** [comment]
Did you grant storage permission?

**Comment by emansih** [comment]
ah, i replicated the bug. it crashed after pressing Sign in

**Comment by reuseman** [comment]
Yeah sorry I missed the last step. So is gonna be a fix for it?

**Comment by emansih** [comment]
yes i will fix it
