### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by centralhardware** [emansih/FireflyMobile#130]
**Firefly III Server Version:**

5.4.5

--------------------------------------

## Expected Behavior

launch application

## Current Behavior

crash

## Steps to Reproduce

launch application via icon (fingerprint lock enabled)

## crash report

```
REPORT_ID=c18323cd-f27d-453c-b434-5283c56f43ea
APP_VERSION_NAME=3.0.5
PHONE_MODEL=HRY-LX1T
BRAND=HONOR
PRODUCT=HRY-LX1TRU
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.AppCompatDelegateImpl$5' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in /data/app/xyz.hisname.fireflyiii-5ugi-fWQantkUey0IquFqg==/base.apk)
at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(ContentFrameLayout.java:3)
at android.view.View.dispatchAttachedToWindow(View.java:19731)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3443)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
at android.view.Choreographer.doCallbacks(Choreographer.java:875)
at android.view.Choreographer.doFrame(Choreographer.java:776)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
at android.os.Handler.handleCallback(Handler.java:888)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8178)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

LOGCAT=10-29 11:28:05.595 E/AndroidRuntime(10904): at android.os.Handler.dispatchMessage(Handler.java:100)
10-29 11:28:05.595 E/AndroidRuntime(10904): at android.os.Looper.loop(Looper.java:213)
10-29 11:28:05.595 E/AndroidRuntime(10904): at android.app.ActivityThread.main(ActivityThread.java:8178)
10-29 11:28:05.595 E/AndroidRuntime(10904): at java.lang.reflect.Method.invoke(Native Method)
10-29 11:28:05.595 E/AndroidRuntime(10904): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-29 11:28:05.595 E/AndroidRuntime(10904): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
--------- beginning of main
10-29 11:32:46.934 I/name.fireflyii(11625): Reinit property: dalvik.vm.checkjni= false
10-29 11:32:46.936 E/name.fireflyii(11625): Not starting debugger since process cannot load the jdwp agent.
10-29 11:32:46.943 W/re-initialized>(11625): type=1400 audit(0.0:2985): avc: denied { read } for pid=11625 name="u:object_r:mmi_prop:s0" dev="tmpfs" ino=3950 scontext=u:r:untrusted_app:s0:c5,c256,c512,c768 tcontext=u:object_r:mmi_prop:s0 tclass=file permissive=0
10-29 11:32:46.947 E/libc    (11625): Access denied finding property "runtime.mmitest.isrunning"
10-29 11:32:46.954 D/ActivityThread(11625): Attach thread to application
10-29 11:32:46.982 I/name.fireflyii(11625): QarthPatchMonintor::Init
10-29 11:32:46.982 I/name.fireflyii(11625):
10-29 11:32:46.982 I/name.fireflyii(11625): QarthPatchMonintor::StartWatch
10-29 11:32:46.982 I/name.fireflyii(11625):
10-29 11:32:46.982 I/name.fireflyii(11625): QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
10-29 11:32:46.982 I/name.fireflyii(11625):
10-29 11:32:46.982 I/name.fireflyii(11625): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/xyz.hisname.fireflyiii
10-29 11:32:46.982 I/name.fireflyii(11625):
10-29 11:32:46.982 I/name.fireflyii(11625): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
10-29 11:32:46.982 I/name.fireflyii(11625):
10-29 11:32:46.982 I/name.fireflyii(11625): QarthPatchMonintor::Run
10-29 11:32:46.982 I/name.fireflyii(11625):
10-29 11:32:46.983 I/name.fireflyii(11625): QarthPatchMonintor::Reading
10-29 11:32:46.983 I/name.fireflyii(11625):
10-29 11:32:46.983 I/name.fireflyii(11625): QarthPatchMonintor::CheckNotifyEvent
10-29 11:32:46.983 I/name.fireflyii(11625):
10-29 11:32:46.983 I/name.fireflyii(11625): QarthPatchMonintor::CheckNotifyEvent before read
10-29 11:32:46.983 I/name.fireflyii(11625):
10-29 11:32:46.984 I/HwApiCacheMangerEx(11625): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10005#256
10-29 11:32:46.993 I/HwApiCacheMangerEx(11625): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10005#0
10-29 11:32:46.996 I/AwareBitmapCacher(11625): init processName:xyz.hisname.fireflyiii pid=11625 uid=10005
10-29 11:32:47.004 E/AwareLog(11625): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@f581fc8
10-29 11:32:47.004 E/AwareLog(11625): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@ee4a861
10-29 11:32:47.023 W/name.fireflyii(11625): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
10-29 11:32:47.024 W/name.fireflyii(11625): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
10-29 11:32:47.024 W/name.fireflyii(11625): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
10-29 11:32:47.045 V/ActivityThread(11625): callActivityOnCreate
10-29 11:32:47.053 V/HwWidgetFactory(11625): : successes to get AllImpl object and return....
10-29 11:32:47.059 I/ACRA    (11625): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
10-29 11:32:47.075 I/OverScrollerOptimization(11625): start init SmartSlideOverScroller and get the overscroller config
10-29 11:32:47.075 I/OverScrollerOptimization(11625): get the overscroller config
10-29 11:32:47.120 D/ActivityThread(11625): add activity client record, r= ActivityRecord{5f7d533 token=android.os.BinderProxy@8a8313f {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@8a8313f
10-29 11:32:47.177 D/ActivityThread(11625): Remove activity client record, r= ActivityRecord{5f7d533 token=android.os.BinderProxy@8a8313f {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@8a8313f
10-29 11:32:47.207 V/ActivityThread(11625): callActivityOnCreate
10-29 11:32:47.248 D/ActivityThread(11625): add activity client record, r= ActivityRecord{5f7d533 token=android.os.BinderProxy@8a8313f {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@8a8313f
10-29 11:32:47.276 D/AndroidRuntime(11625): Shutting down VM
10-29 11:32:47.276 I/QarthLog(11625): [PatchStore] createDisableExceptionQarthFile
10-29 11:32:47.276 I/QarthLog(11625): [PatchStore] create disable file for xyz.hisname.fireflyiii uid is 10005
10-29 11:32:47.277 W/HiTouch_HiTouchSensor(11625): depended package hiTouch does n't exist!
10-29 11:32:47.277 I/HiTouch_HiTouchSensor(11625): HiTouch restricted: system app HiTouch don't exist.
10-29 11:32:47.277 D/HiTouch_PressGestureDetector(11625): onAttached, package=xyz.hisname.fireflyiii, windowType=1, mHiTouchRestricted=true
10-29 11:32:47.278 E/AndroidRuntime(11625): FATAL EXCEPTION: main
10-29 11:32:47.278 E/AndroidRuntime(11625): Process: xyz.hisname.fireflyiii, PID: 11625
10-29 11:32:47.278 E/AndroidRuntime(11625): java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.AppCompatDelegateImpl$5' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in /data/app/xyz.hisname.fireflyiii-5ugi-fWQantkUey0IquFqg==/base.apk)
10-29 11:32:47.278 E/AndroidRuntime(11625): at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(ContentFrameLayout.java:3)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.View.dispatchAttachedToWindow(View.java:19731)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3443)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.Choreographer.doCallbacks(Choreographer.java:875)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.Choreographer.doFrame(Choreographer.java:776)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.os.Handler.handleCallback(Handler.java:888)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.os.Handler.dispatchMessage(Handler.java:100)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.os.Looper.loop(Looper.java:213)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.app.ActivityThread.main(ActivityThread.java:8178)
10-29 11:32:47.278 E/AndroidRuntime(11625): at java.lang.reflect.Method.invoke(Native Method)
10-29 11:32:47.278 E/AndroidRuntime(11625): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-29 11:32:47.278 E/AndroidRuntime(11625): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
10-29 11:32:47.279 E/ACRA    (11625): ACRA caught a IllegalAccessError for xyz.hisname.fireflyiii
10-29 11:32:47.279 E/ACRA    (11625): java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.AppCompatDelegateImpl$5' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in /data/app/xyz.hisname.fireflyiii-5ugi-fWQantkUey0IquFqg==/base.apk)
10-29 11:32:47.279 E/ACRA    (11625): at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(ContentFrameLayout.java:3)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.View.dispatchAttachedToWindow(View.java:19731)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3443)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.Choreographer.doCallbacks(Choreographer.java:875)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.Choreographer.doFrame(Choreographer.java:776)
10-29 11:32:47.279 E/ACRA    (11625): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
10-29 11:32:47.279 E/ACRA    (11625): at android.os.Handler.handleCallback(Handler.java:888)
10-29 11:32:47.279 E/ACRA    (11625): at android.os.Handler.dispatchMessage(Handler.java:100)
10-29 11:32:47.279 E/ACRA    (11625): at android.os.Looper.loop(Looper.java:213)
10-29 11:32:47.279 E/ACRA    (11625): at android.app.ActivityThread.main(ActivityThread.java:8178)
10-29 11:32:47.279 E/ACRA    (11625): at java.lang.reflect.Method.invoke(Native Method)
10-29 11:32:47.279 E/ACRA    (11625): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-29 11:32:47.279 E/ACRA    (11625): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
IS_SILENT=false
USER_CRASH_DATE=2020-10-29T11:32:47.283+07:00
```

**Comment by ivanboytsov** [comment]
The same. Crash on launch of v 3.0.5
Samsung Galaxy J7
Android 9

**Comment by emansih** [comment]
Sorry about that. It works for me on the debug builds, seems to crash only on release builds. Will push a release this weekend. Stay on the older version for now

**Comment by ivanboytsov** [comment]
![Screenshot_20201030-144056_Firefly III Mobile](https://user-images.githubusercontent.com/70232503/97701222-1bf3c100-1abe-11eb-9316-a33467c18d30.jpg)
Seems not fixed for me

**Comment by ivanboytsov** [comment]
Even wiping app's cache and data doesn't help.

**Comment by emansih** [comment]
Are there any logs?

**Comment by ivanboytsov** [comment]
> Are there any logs?

No. Doesn't offer to send logs via mail as it used to on crash.

**Comment by emansih** [comment]
Uninstall and install the new APK?

**Comment by ivanboytsov** [comment]
> Uninstall and install the new APK?

Yes. New install.

**Comment by emansih** [comment]
What happens if you disable battery optimisation for the app? It _might_ show the logs

**Comment by ivanboytsov** [comment]
Disabled, but nothing changed.
![Screenshot_20201030-153057_Settings](https://user-images.githubusercontent.com/70232503/97705350-fb7b3500-1ac4-11eb-8ff0-1330b22dc1f0.jpg)

**Comment by emansih** [comment]
It's really strange since ACRA isn't initializing. If you can use adb logcat, it might help

**Comment by emansih** [comment]
@ivanboytsov Hi. I managed to replicate the bug on a Pie emulator. Will be fixing it soon

**Comment by ivanboytsov** [comment]
Now it launches. Thanks.

**Comment by lzivadinovic** [comment]
Hi, i've managed to register app via oauth (past crash on startup, new 3.0.7 apk from github release) and i get this once im in app https://pastebin.com/NwuYDZKT
