### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by centralhardware** [emansih/FireflyMobile#132]
**Firefly III Server Version:**
 v5.4.5
## Expected Behavior

start application

## Current Behavior

after unlock app via fingerprint crash

## Steps to Reproduce

launch app and unlock via fingerprint

## crash report

```
REPORT_ID=6f464c82-2a76-4b20-83af-3bfecb3e31e5
APP_VERSION_NAME=3.0.7
PHONE_MODEL=HRY-LX1T
BRAND=HONOR
PRODUCT=HRY-LX1TRU
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
at java.math.BigDecimal.<init>(BigDecimal.java:425)
at xyz.hisname.fireflyiii.data.local.dao.BudgetDataDao_Impl.getConstraintBudgetWithCurrency(BudgetDataDao_Impl.java:12)
at xyz.hisname.fireflyiii.repository.budget.BudgetRepository.retrieveConstraintBudgetWithCurrency(BudgetRepository.kt:1)
at xyz.hisname.fireflyiii.repository.budget.BudgetViewModel$retrieveCurrentMonthBudget$1$2$4$1.invokeSuspend(BudgetViewModel.kt:13)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

LOGCAT=10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.Choreographer.doCallbacks(Choreographer.java:875)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.Choreographer.doFrame(Choreographer.java:776)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.os.Handler.handleCallback(Handler.java:888)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.os.Handler.dispatchMessage(Handler.java:100)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.os.Looper.loop(Looper.java:213)
10-29 11:32:47.278 E/AndroidRuntime(11625): at android.app.ActivityThread.main(ActivityThread.java:8178)
10-29 11:32:47.278 E/AndroidRuntime(11625): at java.lang.reflect.Method.invoke(Native Method)
10-29 11:32:47.278 E/AndroidRuntime(11625): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-29 11:32:47.278 E/AndroidRuntime(11625): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
10-29 12:44:09.187 E/AndroidRuntime(16885): FATAL EXCEPTION: main
10-29 12:44:09.187 E/AndroidRuntime(16885): Process: xyz.hisname.fireflyiii, PID: 16885
10-29 12:44:09.187 E/AndroidRuntime(16885): java.lang.IllegalAccessError: Illegal class access: 'androidx.appcompat.widget.ContentFrameLayout' attempting to access 'androidx.appcompat.app.AppCompatDelegateImpl$5' (declaration of 'androidx.appcompat.widget.ContentFrameLayout' appears in /data/app/xyz.hisname.fireflyiii-5ugi-fWQantkUey0IquFqg==/base.apk)
10-29 12:44:09.187 E/AndroidRuntime(16885): at androidx.appcompat.widget.ContentFrameLayout.onAttachedToWindow(ContentFrameLayout.java:3)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.View.dispatchAttachedToWindow(View.java:19731)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3443)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3450)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2201)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1857)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8089)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1057)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.Choreographer.doCallbacks(Choreographer.java:875)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.Choreographer.doFrame(Choreographer.java:776)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1042)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.os.Handler.handleCallback(Handler.java:888)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.os.Handler.dispatchMessage(Handler.java:100)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.os.Looper.loop(Looper.java:213)
10-29 12:44:09.187 E/AndroidRuntime(16885): at android.app.ActivityThread.main(ActivityThread.java:8178)
10-29 12:44:09.187 E/AndroidRuntime(16885): at java.lang.reflect.Method.invoke(Native Method)
10-29 12:44:09.187 E/AndroidRuntime(16885): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
10-29 12:44:09.187 E/AndroidRuntime(16885): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
--------- beginning of main
11-01 11:55:36.073 I/name.fireflyii(14334): Reinit property: dalvik.vm.checkjni= false
11-01 11:55:36.075 E/name.fireflyii(14334): Not starting debugger since process cannot load the jdwp agent.
11-01 11:55:36.077 W/re-initialized>(14334): type=1400 audit(0.0:185936): avc: denied { read } for pid=14334 name="u:object_r:mmi_prop:s0" dev="tmpfs" ino=3950 scontext=u:r:untrusted_app:s0:c5,c256,c512,c768 tcontext=u:object_r:mmi_prop:s0 tclass=file permissive=0
11-01 11:55:36.083 E/libc    (14334): Access denied finding property "runtime.mmitest.isrunning"
--------- beginning of system
11-01 11:55:36.085 D/ActivityThread(14334): Attach thread to application
11-01 11:55:36.135 I/HwApiCacheMangerEx(14334): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10005#256
11-01 11:55:36.135 I/HwApiCacheMangerEx(14334): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10005#0
11-01 11:55:36.136 I/name.fireflyii(14334): QarthPatchMonintor::Init
11-01 11:55:36.136 I/name.fireflyii(14334):
11-01 11:55:36.136 I/name.fireflyii(14334): QarthPatchMonintor::StartWatch
11-01 11:55:36.136 I/name.fireflyii(14334):
11-01 11:55:36.136 I/name.fireflyii(14334): QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
11-01 11:55:36.136 I/name.fireflyii(14334):
11-01 11:55:36.136 I/name.fireflyii(14334): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/xyz.hisname.fireflyiii
11-01 11:55:36.136 I/name.fireflyii(14334):
11-01 11:55:36.136 I/name.fireflyii(14334): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
11-01 11:55:36.136 I/name.fireflyii(14334):
11-01 11:55:36.136 I/name.fireflyii(14334): QarthPatchMonintor::Run
11-01 11:55:36.136 I/name.fireflyii(14334):
11-01 11:55:36.137 I/name.fireflyii(14334): QarthPatchMonintor::Reading
11-01 11:55:36.137 I/name.fireflyii(14334):
11-01 11:55:36.137 I/name.fireflyii(14334): QarthPatchMonintor::CheckNotifyEvent
11-01 11:55:36.137 I/name.fireflyii(14334):
11-01 11:55:36.137 I/name.fireflyii(14334): QarthPatchMonintor::CheckNotifyEvent before read
11-01 11:55:36.137 I/name.fireflyii(14334):
11-01 11:55:36.143 I/AwareBitmapCacher(14334): init processName:xyz.hisname.fireflyiii pid=14334 uid=10005
11-01 11:55:36.144 E/AwareLog(14334): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@1af164f
11-01 11:55:36.144 E/AwareLog(14334): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@72c1dc
11-01 11:55:36.169 W/name.fireflyii(14334): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
11-01 11:55:36.169 W/name.fireflyii(14334): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
11-01 11:55:36.169 W/name.fireflyii(14334): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
11-01 11:55:36.186 V/ActivityThread(14334): callActivityOnCreate
11-01 11:55:36.192 V/HwWidgetFactory(14334): : successes to get AllImpl object and return....
11-01 11:55:36.204 I/ACRA    (14334): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
11-01 11:55:36.209 I/OverScrollerOptimization(14334): start init SmartSlideOverScroller and get the overscroller config
11-01 11:55:36.209 I/OverScrollerOptimization(14334): get the overscroller config
11-01 11:55:36.239 D/ActivityThread(14334): add activity client record, r= ActivityRecord{893aed8 token=android.os.BinderProxy@a1bd9e3 {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@a1bd9e3
11-01 11:55:36.421 D/ActivityThread(14334): Remove activity client record, r= ActivityRecord{893aed8 token=android.os.BinderProxy@a1bd9e3 {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@a1bd9e3
11-01 11:55:36.445 V/ActivityThread(14334): callActivityOnCreate
11-01 11:55:36.471 D/ActivityThread(14334): add activity client record, r= ActivityRecord{893aed8 token=android.os.BinderProxy@a1bd9e3 {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@a1bd9e3
11-01 11:55:36.491 W/HiTouch_HiTouchSensor(14334): depended package hiTouch does n't exist!
11-01 11:55:36.491 I/HiTouch_HiTouchSensor(14334): HiTouch restricted: system app HiTouch don't exist.
11-01 11:55:36.491 D/HiTouch_PressGestureDetector(14334): onAttached, package=xyz.hisname.fireflyiii, windowType=1, mHiTouchRestricted=true
11-01 11:55:36.516 I/iGraphics(14334): [0020080c] pn: xyz.hisname.fireflyiii, p: 14334
11-01 11:55:36.516 I/iGraphics(14334): [0030080c] no spt app: xyz.hisname.fireflyiii
11-01 11:55:36.543 D/mali_winsys(14334): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
11-01 11:55:36.549 W/Gralloc3(14334): mapper 3.x is not supported
11-01 11:55:36.575 E/        (14334): APS:IFLoad:importExternalFunctions, search function createNewHwApsUtils failed, dlsym err:undefined symbol: createNewHwApsUtils
11-01 11:55:36.576 D/        (14334): APS:importExternalFunctions OK
11-01 11:55:36.579 I/HwViewRootImpl(14334): removeInvalidNode jank list is null
11-01 11:55:39.587 D/NetworkSecurityConfig(14334): Using Network Security Config from resource network_security_config debugBuild: false
11-01 11:55:39.809 W/RecyclerView(14334): No adapter attached; skipping layout
11-01 11:55:39.959 I/HwViewRootImpl(14334): removeInvalidNode jank list is null
11-01 11:55:40.205 E/ACRA    (14334): ACRA caught a NullPointerException for xyz.hisname.fireflyiii
11-01 11:55:40.205 E/ACRA    (14334): java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
11-01 11:55:40.205 E/ACRA    (14334): at java.math.BigDecimal.<init>(BigDecimal.java:425)
11-01 11:55:40.205 E/ACRA    (14334): at xyz.hisname.fireflyiii.data.local.dao.BudgetDataDao_Impl.getConstraintBudgetWithCurrency(BudgetDataDao_Impl.java:12)
11-01 11:55:40.205 E/ACRA    (14334): at xyz.hisname.fireflyiii.repository.budget.BudgetRepository.retrieveConstraintBudgetWithCurrency(BudgetRepository.kt:1)
11-01 11:55:40.205 E/ACRA    (14334): at xyz.hisname.fireflyiii.repository.budget.BudgetViewModel$retrieveCurrentMonthBudget$1$2$4$1.invokeSuspend(BudgetViewModel.kt:13)
11-01 11:55:40.205 E/ACRA    (14334): at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-01 11:55:40.205 E/ACRA    (14334): at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
11-01 11:55:40.205 E/ACRA    (14334): at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-01 11:55:40.205 E/ACRA    (14334): at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
IS_SILENT=false
USER_CRASH_DATE=2020-11-01T11:55:40.209+07:00
```

**Comment by emansih** [comment]
@centralhardware Hi! I might have fixed this issue. Could you try this APK? https://drive.google.com/file/d/1YV47voSaoEaq1hpcPyxXEqifuniWGG8z/view?usp=sharing Thank you

**Comment by centralhardware** [comment]
@emansih i tried it and the app works fine

**Comment by emansih** [comment]
Thank you

**Comment by ivanboytsov** [comment]
In my case app started crashing on launch on 2nd day after fresh install
[Fireflyiii-mobile-11.txt](https://github.com/emansih/FireflyMobile/files/5579168/Fireflyiii-mobile-11.txt)
