### ISSUE TITLE
Crashing after set up and on subsequent app launches

### ISSUE THREAD

**Issue by Fellsmarch** [emansih/FireflyMobile#133]
**Firefly III Server Version:** 
5.45

**Firefly III Mobile Version:**
3.07

**Android Version:**  
10

**Device Information:**  

- BRAND: HONOR (Huawei)
- MODEL: PCT-L29
--------------------------------------

## Expected Behavior
Setup and launch app

## Current Behavior
Can successfully launch app before it has been set up. After setting up with OAuth (as getting a quick success message prior to crash), the app crashes. Any subsequent launches of the app also crashes the app with the same stack trace.

## Steps to Reproduce
- Set up app with OAuth
- When given choice with what to launch with after clicking set up button, choose Firefly III Mobile App
- App crashes
- Re-launch app
- App crashes

```
REPORT_ID=f6690011-ef7f-46bc-a9f8-2cc05bf6d778
APP_VERSION_NAME=3.0.7
PHONE_MODEL=PCT-L29
BRAND=HONOR
PRODUCT=PCT-L29
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	at java.math.BigDecimal.<init>(BigDecimal.java:425)
	at xyz.hisname.fireflyiii.data.local.dao.BudgetDataDao_Impl.getConstraintBudgetWithCurrency(BudgetDataDao_Impl.java:12)
	at xyz.hisname.fireflyiii.repository.budget.BudgetRepository.retrieveConstraintBudgetWithCurrency(BudgetRepository.kt:1)
	at xyz.hisname.fireflyiii.repository.budget.BudgetViewModel$retrieveCurrentMonthBudget$1$2$4$1.invokeSuspend(BudgetViewModel.kt:13)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

LOGCAT=11-04 23:41:47.094 V/ActivityThread(20134): callActivityOnCreate
11-04 23:41:47.108 D/ActivityThread(20134): add activity client record, r= ActivityRecord{36cc1a6 token=android.os.BinderProxy@ca986da {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@ca986da
11-04 23:41:47.589 D/RtgSched(20134): resetRtgSchedHandle failed enable:0
11-04 23:41:47.674 D/ActivityThread(20134): Remove activity client record, r= ActivityRecord{36cc1a6 token=android.os.BinderProxy@ca986da {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@ca986da
11-04 23:42:52.016 D/ActivityThread(21346): Attach thread to application
11-04 23:42:52.061 V/ActivityThread(21346): callActivityOnCreate
11-04 23:42:52.082 D/ActivityThread(21346): add activity client record, r= ActivityRecord{9b1053 token=android.os.BinderProxy@f59c9fc {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@f59c9fc
11-04 23:42:52.083 D/ActivityThread(21346): Won't deliver top position change in state=1
11-04 23:42:52.084 D/ActivityThread(21346): Won't deliver top position change in state=1
11-04 23:42:52.093 V/ActivityThread(21346): callActivityOnCreate
11-04 23:42:52.103 D/ActivityThread(21346): add activity client record, r= ActivityRecord{45f368 token=android.os.BinderProxy@5cdb689 {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.AuthActivity}} token= android.os.BinderProxy@5cdb689
11-04 23:42:52.183 D/ActivityThread(21346): Remove activity client record, r= ActivityRecord{9b1053 token=android.os.BinderProxy@f59c9fc {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@f59c9fc
11-04 23:42:53.156 W/HwApsManager(21346): HwApsManagerService, registerCallback, start !
11-04 23:42:55.313 D/TextClassifierService(21346): No configured system TextClassifierService
11-04 23:42:57.020 D/TextClassifierService(21346): No configured system TextClassifierService
11-04 23:43:00.275 D/RtgSched(21346): resetRtgSchedHandle failed enable:0
11-04 23:43:07.373 D/ActivityThread(21346): Won't deliver top position change in state=5
11-04 23:43:10.029 D/RtgSched(21346): resetRtgSchedHandle failed enable:0
11-04 23:43:10.745 I/ActivityThread(21346): Handle window ActivityRecord{45f368 token=android.os.BinderProxy@5cdb689 {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.AuthActivity}} visibility: true
11-04 23:43:10.829 D/RtgSched(21346): resetRtgSchedHandle failed enable:0
11-04 23:43:12.289 D/ActivityThread(21346): Won't deliver top position change in state=2
11-04 23:43:13.560 V/ActivityThread(21346): callActivityOnCreate
11-04 23:43:13.615 D/ActivityThread(21346): add activity client record, r= ActivityRecord{cef96dd token=android.os.BinderProxy@a3d7847 {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@a3d7847
11-04 23:43:14.176 D/ActivityThread(21346): Remove activity client record, r= ActivityRecord{45f368 token=android.os.BinderProxy@5cdb689 {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.AuthActivity}} token= android.os.BinderProxy@5cdb689
11-04 23:43:14.238 D/RtgSched(21346): resetRtgSchedHandle failed enable:0
11-04 23:43:14.549 D/ActivityThread(23132): Attach thread to application
--------- beginning of main
11-04 23:43:19.575 D/AwareBitmapCacher(23132): handleInit disable xyz.hisname.fireflyiii:acra
11-04 23:45:10.271 I/name.fireflyii(23519): Reinit property: dalvik.vm.checkjni= false
11-04 23:45:10.271 I/name.fireflyii(23519): ReInitProperties: persist.vm.debug.dumpapi= false
11-04 23:45:10.271 E/name.fireflyii(23519): Not starting debugger since process cannot load the jdwp agent.
11-04 23:45:10.279 D/ActivityThread(23519): Attach thread to application
11-04 23:45:10.292 D/HwFrameworkSecurityPartsFactory(23519): HwFrameworkSecurityPartsFactory in.
11-04 23:45:10.292 I/HwFrameworkSecurityPartsFactory(23519): add HwFrameworkSecurityPartsFactory to memory.
11-04 23:45:10.292 E/BehaviorCollectManager(23519): Fail to acquire dataAnalyzerService...
11-04 23:45:10.303 I/name.fireflyii(23519): QarthPatchMonintor::Init
11-04 23:45:10.303 I/name.fireflyii(23519): 
11-04 23:45:10.303 I/name.fireflyii(23519): QarthPatchMonintor::StartWatch
11-04 23:45:10.303 I/name.fireflyii(23519): 
11-04 23:45:10.303 I/name.fireflyii(23519): QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
11-04 23:45:10.303 I/name.fireflyii(23519): 
11-04 23:45:10.303 I/name.fireflyii(23519): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/xyz.hisname.fireflyiii
11-04 23:45:10.304 I/name.fireflyii(23519): 
11-04 23:45:10.304 I/name.fireflyii(23519): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
11-04 23:45:10.304 I/name.fireflyii(23519): 
11-04 23:45:10.304 I/name.fireflyii(23519): QarthPatchMonintor::Run
11-04 23:45:10.304 I/name.fireflyii(23519): 
11-04 23:45:10.305 I/name.fireflyii(23519): QarthPatchMonintor::Reading
11-04 23:45:10.305 I/name.fireflyii(23519): 
11-04 23:45:10.305 I/name.fireflyii(23519): QarthPatchMonintor::CheckNotifyEvent
11-04 23:45:10.305 I/name.fireflyii(23519): 
11-04 23:45:10.305 I/name.fireflyii(23519): QarthPatchMonintor::CheckNotifyEvent before read
11-04 23:45:10.305 I/name.fireflyii(23519): 
11-04 23:45:10.305 I/HwApiCacheMangerEx(23519): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10291#256
11-04 23:45:10.305 I/HwApiCacheMangerEx(23519): need clear apicache,because volumes changed,oldCnt=0 newCnt=1
11-04 23:45:10.306 I/HwApiCacheMangerEx(23519): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10291#0
11-04 23:45:10.306 I/HwApiCacheMangerEx(23519): need clear apicache,because volumes changed,oldCnt=1 newCnt=1
11-04 23:45:10.308 I/AwareBitmapCacher(23519): init processName:xyz.hisname.fireflyiii pid=23519 uid=10291
11-04 23:45:10.308 I/HwApiCacheMangerEx(23519): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10291#256
11-04 23:45:10.308 I/HwApiCacheMangerEx(23519): need clear apicache,because volumes changed,oldCnt=1 newCnt=1
11-04 23:45:10.310 E/AwareLog(23519): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@2ed98c9
11-04 23:45:10.316 W/name.fireflyii(23519): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
11-04 23:45:10.316 W/name.fireflyii(23519): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
11-04 23:45:10.316 W/name.fireflyii(23519): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
11-04 23:45:10.317 I/iGraphics(23519): [0020080c] pn: xyz.hisname.fireflyiii, p: 23519
11-04 23:45:10.317 I/iGraphics(23519): [0030080c] no spt app: xyz.hisname.fireflyiii
11-04 23:45:10.328 V/ActivityThread(23519): callActivityOnCreate
11-04 23:45:10.331 V/HwWidgetFactory(23519): : successes to get AllImpl object and return....
11-04 23:45:10.333 I/DecorView[](23519):  old windowMode:0 new windoMode:1
11-04 23:45:10.337 I/OverScrollerOptimization(23519): start init SmartSlideOverScroller and get the overscroller config
11-04 23:45:10.337 I/OverScrollerOptimization(23519): get the overscroller config
11-04 23:45:10.339 I/ACRA    (23519): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
11-04 23:45:10.362 D/NetworkSecurityConfig(23519): Using Network Security Config from resource network_security_config debugBuild: false
11-04 23:45:10.374 D/HwGalleryCacheManagerImpl(23519): mIsEffect:false
11-04 23:45:10.383 D/ActivityThread(23519): add activity client record, r= ActivityRecord{36cc1a6 token=android.os.BinderProxy@ca986da {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@ca986da
11-04 23:45:10.424 I/DecorView[](23519):  old windowMode:1 new windoMode:1
11-04 23:45:10.428 I/RmeSchedManager(23519): init Rme, version is: v1.0
11-04 23:45:10.433 D/ActivityThread(23519): Remove activity client record, r= ActivityRecord{36cc1a6 token=android.os.BinderProxy@ca986da {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@ca986da
11-04 23:45:10.439 V/ActivityThread(23519): callActivityOnCreate
11-04 23:45:10.441 I/DecorView[](23519):  old windowMode:0 new windoMode:1
11-04 23:45:10.453 D/ActivityThread(23519): add activity client record, r= ActivityRecord{36cc1a6 token=android.os.BinderProxy@ca986da {xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}} token= android.os.BinderProxy@ca986da
11-04 23:45:10.494 I/DecorView[](23519):  old windowMode:1 new windoMode:1
11-04 23:45:10.499 D/HiTouch_PressGestureDetector(23519): onAttached, package=xyz.hisname.fireflyiii, windowType=1, mHiTouchRestricted=false
11-04 23:45:10.514 D/mali_winsys(23519): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
11-04 23:45:10.517 W/RecyclerView(23519): No adapter attached; skipping layout
11-04 23:45:10.550 W/Gralloc3(23519): mapper 3.x is not supported
11-04 23:45:10.578 I/HwViewRootImpl(23519): removeInvalidNode jank list is null
11-04 23:45:10.584 D/DecorView(23519): showOrHideHighlightView: hasFocus=true; winMode=1; isMrgNull=true
11-04 23:45:10.584 W/InputMethodManager(23519): startInputReason = 1
11-04 23:45:10.586 W/InputMethodManager(23519): startInputReason = 5
11-04 23:45:10.883 E/ACRA    (23519): ACRA caught a NullPointerException for xyz.hisname.fireflyiii
11-04 23:45:10.883 E/ACRA    (23519): java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
11-04 23:45:10.883 E/ACRA    (23519): 	at java.math.BigDecimal.<init>(BigDecimal.java:425)
11-04 23:45:10.883 E/ACRA    (23519): 	at xyz.hisname.fireflyiii.data.local.dao.BudgetDataDao_Impl.getConstraintBudgetWithCurrency(BudgetDataDao_Impl.java:12)
11-04 23:45:10.883 E/ACRA    (23519): 	at xyz.hisname.fireflyiii.repository.budget.BudgetRepository.retrieveConstraintBudgetWithCurrency(BudgetRepository.kt:1)
11-04 23:45:10.883 E/ACRA    (23519): 	at xyz.hisname.fireflyiii.repository.budget.BudgetViewModel$retrieveCurrentMonthBudget$1$2$4$1.invokeSuspend(BudgetViewModel.kt:13)
11-04 23:45:10.883 E/ACRA    (23519): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
11-04 23:45:10.883 E/ACRA    (23519): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:15)
11-04 23:45:10.883 E/ACRA    (23519): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
11-04 23:45:10.883 E/ACRA    (23519): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
IS_SILENT=false
USER_CRASH_DATE=2020-11-04T23:45:10.884+13:00

```

**Comment by emansih** [comment]
@Fellsmarch Hi! I _might_ have fixed this issue. Could you try this APK? https://drive.google.com/file/d/1YV47voSaoEaq1hpcPyxXEqifuniWGG8z/view?usp=sharing Thank you!

**Comment by Fellsmarch** [comment]
Yup, that worked, thanks.
