### ISSUE TITLE
Crash on adding tag

### ISSUE THREAD

**Issue by gthbusrr** [emansih/FireflyMobile#144]
**Firefly III Server Version:**

- 5.4.6 (Latest)

**Firefly III Mobile Version:**

- 4.0.2 (Latest)

**Android Version:** 

- 10

**Device Information:**  

- BRAND: Samsung
- MODEL: Galaxy Note20 Ultra
--------------------------------------

## Expected Behavior
- Able to add tag without crashing
- [Suggestions] Faster loading time when navigating to add transaction screen
## Current Behavior
- Crashes whenever I tried to add a tag
## Steps to Reproduce
1. Click any button to navigate to the screen for adding transaction
2. Type something in "tag" field
3. Click on suggested tag
4. BOOM

```
REPORT_ID=616c17e2-e5dc-4111-9268-04e44955a664
APP_VERSION_NAME=4.0.2
PHONE_MODEL=SM-N9860
BRAND=samsung
PRODUCT=c2qzhx
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
	at com.hootsuite.nachos.chip.ChipSpan.<init>(ChipSpan.java:15)
	at xyz.hisname.fireflyiii.ui.transaction.addtransaction.AddTransactionFragment$setIcons$8.createChip(AddTransactionFragment.kt:4)
	at com.hootsuite.nachos.tokenizer.SpanChipTokenizer.terminateToken(SpanChipTokenizer.java:2)
	at com.hootsuite.nachos.NachoTextView.onItemClick(NachoTextView.java:12)
	at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:1071)
	at android.widget.AutoCompleteTextView.access$600(AutoCompleteTextView.java:101)
	at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1414)
	at android.widget.AdapterView.performItemClick(AdapterView.java:374)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1736)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4207)
	at android.widget.AbsListView$7.run(AbsListView.java:6692)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8154)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
Caused by: java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
	... 18 more

LOGCAT=01-17 08:32:07.919 I/ViewRootImpl@af8853c[AddTransactionActivity](31017): MSG_RESIZED: frame=(0,0,1080,2316) ci=(0,67,0,0) vi=(0,67,0,573) or=1
01-17 08:32:07.956 W/View    (31017): couldn't find view with id 2131362694
01-17 08:32:07.960 W/View    (31017): couldn't find view with id 2131362694
01-17 08:32:07.962 I/chatty  (31017): uid=10459(xyz.hisname.fireflyiii) identical 3 lines
01-17 08:32:07.962 W/View    (31017): couldn't find view with id 2131362694
01-17 08:32:07.968 W/View    (31017): couldn't find view with id 2131362694
01-17 08:32:08.007 I/chatty  (31017): uid=10459(xyz.hisname.fireflyiii) identical 13 lines
01-17 08:32:08.015 W/View    (31017): couldn't find view with id 2131362694
01-17 08:32:08.018 W/View    (31017): couldn't find view with id 2131362694
01-17 08:32:08.019 I/chatty  (31017): uid=10459(xyz.hisname.fireflyiii) identical 10 lines
01-17 08:32:08.020 W/View    (31017): couldn't find view with id 2131362694
01-17 08:32:12.509 E/SpannableStringBuilder(31017): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-17 08:32:12.510 E/SpannableStringBuilder(31017): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-17 08:32:12.676 I/ViewRootImpl@af8853c[AddTransactionActivity](31017): ViewPostIme key 0
01-17 08:32:12.679 I/ViewRootImpl@af8853c[AddTransactionActivity](31017): ViewPostIme key 1
01-17 08:32:13.152 D/NativeCustomFrequencyManager(31017): [NativeCFMS] BpCustomFrequencyManager::BpCustomFrequencyManager()
01-17 08:32:13.161 I/ViewRootImpl@cb1ba5e[PopupWindow:19706e3](31017): setView = android.widget.PopupWindow$PopupDecorView@1292e3f TM=true MM=false
01-17 08:32:13.167 V/InputMethodManager(31017): Not IME target window, ignoring
01-17 08:32:13.181 I/ViewRootImpl@cb1ba5e[PopupWindow:19706e3](31017): Relayout returned: old=(0,67,1080,2316) new=(54,1196,1026,1428) req=(972,232)0 dur=10 res=0x7 s={true 523615793152} ch=true
01-17 08:32:13.182 D/OpenGLRenderer(31017): createReliableSurface : 0x79e3acb0c0(0x79e9eef000)
01-17 08:32:13.182 D/OpenGLRenderer(31017): eglCreateWindowSurface : 0x79e9ee4d80
01-17 08:32:13.183 D/AbsListView(31017):  in onLayout changed 
01-17 08:32:13.184 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:13.188 E/NativeCustomFrequencyManager(31017): [NativeCFMS] BpCustomFrequencyManager::sendDrawingTid()
01-17 08:32:13.188 D/OpenGLRenderer(31017): GPIS:: SetUp Pid : 31017    Tid : 2097
01-17 08:32:13.216 I/ViewRootImpl@cb1ba5e[PopupWindow:19706e3](31017): MSG_RESIZED: frame=(54,1196,1026,1428) ci=(0,0,0,0) vi=(0,0,0,0) or=1
01-17 08:32:13.256 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:13.259 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:13.411 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:13.415 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:13.910 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.077 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.131 I/ViewRootImpl@cb1ba5e[PopupWindow:19706e3](31017): ViewPostIme pointer 0
01-17 08:32:14.143 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.198 I/ViewRootImpl@cb1ba5e[PopupWindow:19706e3](31017): ViewPostIme pointer 1
01-17 08:32:14.198 D/AbsListView(31017): onTouchUp() mTouchMode : 0
01-17 08:32:14.202 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.209 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.213 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.217 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.221 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.225 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.229 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.234 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.237 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.243 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.247 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.250 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.253 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.259 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.263 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
01-17 08:32:14.267 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x79e9ee4d80 -> 0x7a554c0a80
01-17 08:32:14.272 D/AndroidRuntime(31017): Shutting down VM
--------- beginning of crash
01-17 08:32:14.273 E/AndroidRuntime(31017): FATAL EXCEPTION: main
01-17 08:32:14.273 E/AndroidRuntime(31017): Process: xyz.hisname.fireflyiii, PID: 31017
01-17 08:32:14.273 E/AndroidRuntime(31017): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at com.hootsuite.nachos.chip.ChipSpan.<init>(ChipSpan.java:15)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at xyz.hisname.fireflyiii.ui.transaction.addtransaction.AddTransactionFragment$setIcons$8.createChip(AddTransactionFragment.kt:4)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at com.hootsuite.nachos.tokenizer.SpanChipTokenizer.terminateToken(SpanChipTokenizer.java:2)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at com.hootsuite.nachos.NachoTextView.onItemClick(NachoTextView.java:12)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:1071)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.widget.AutoCompleteTextView.access$600(AutoCompleteTextView.java:101)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1414)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.widget.AdapterView.performItemClick(AdapterView.java:374)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1736)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4207)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.widget.AbsListView$7.run(AbsListView.java:6692)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.os.Handler.handleCallback(Handler.java:883)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.os.Looper.loop(Looper.java:237)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at android.app.ActivityThread.main(ActivityThread.java:8154)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at java.lang.reflect.Method.invoke(Native Method)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
01-17 08:32:14.273 E/AndroidRuntime(31017): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
01-17 08:32:14.273 E/AndroidRuntime(31017): Caused by: java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
01-17 08:32:14.273 E/AndroidRuntime(31017): 	... 18 more
01-17 08:32:14.273 E/ACRA    (31017): ACRA caught a NoClassDefFoundError for xyz.hisname.fireflyiii
01-17 08:32:14.273 E/ACRA    (31017): java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
01-17 08:32:14.273 E/ACRA    (31017): 	at com.hootsuite.nachos.chip.ChipSpan.<init>(ChipSpan.java:15)
01-17 08:32:14.273 E/ACRA    (31017): 	at xyz.hisname.fireflyiii.ui.transaction.addtransaction.AddTransactionFragment$setIcons$8.createChip(AddTransactionFragment.kt:4)
01-17 08:32:14.273 E/ACRA    (31017): 	at com.hootsuite.nachos.tokenizer.SpanChipTokenizer.terminateToken(SpanChipTokenizer.java:2)
01-17 08:32:14.273 E/ACRA    (31017): 	at com.hootsuite.nachos.NachoTextView.onItemClick(NachoTextView.java:12)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.widget.AutoCompleteTextView.performCompletion(AutoCompleteTextView.java:1071)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.widget.AutoCompleteTextView.access$600(AutoCompleteTextView.java:101)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.widget.AutoCompleteTextView$DropDownItemClickListener.onItemClick(AutoCompleteTextView.java:1414)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.widget.AdapterView.performItemClick(AdapterView.java:374)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1736)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:4207)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.widget.AbsListView$7.run(AbsListView.java:6692)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.os.Handler.handleCallback(Handler.java:883)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.os.Looper.loop(Looper.java:237)
01-17 08:32:14.273 E/ACRA    (31017): 	at android.app.ActivityThread.main(ActivityThread.java:8154)
01-17 08:32:14.273 E/ACRA    (31017): 	at java.lang.reflect.Method.invoke(Native Method)
01-17 08:32:14.273 E/ACRA    (31017): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
01-17 08:32:14.273 E/ACRA    (31017): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)
01-17 08:32:14.273 E/ACRA    (31017): Caused by: java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
01-17 08:32:14.273 E/ACRA    (31017): 	... 18 more
01-17 08:32:14.277 D/OpenGLRenderer(31017): makeCurrent EglSurface : 0x7a554c0a80 -> 0x79e9ee4d80
IS_SILENT=false
USER_CRASH_DATE=2021-01-17T08:32:14.288+08:00
```

**Comment by emansih** [comment]
This is a minor bug because I removed Jetifier. Will be fixed in the next release.
