### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by ryan77627** [emansih/FireflyMobile#152]
**Firefly III Server Version:** 5.4.6

**Firefly III Mobile Version:** 4.0.4

**Android Version:**  11

**Device Information:**  MI8 on PixelExperience rom

- BRAND: xiaomi
- MODEL: mi 8
--------------------------------------

## Expected Behavior
Expected to launch properly after setting up app and authenticating using access token (not oauth)
## Current Behavior
Crashes on launch. EDIT: I should say I don't believe this is a duplicate of the other crash issue because the stack traces refer to different issues.
## Steps to Reproduce
Add account using personal access token
App crashes trying to load the main interface

```
REPORT_ID=95ce34c7-bf8d-42f4-8b76-afb37430769d
APP_VERSION_NAME=1.3.6
PHONE_MODEL=MI 8
BRAND=Xiaomi
PRODUCT=dipper
ANDROID_VERSION=11
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter description
	at xyz.hisname.fireflyiii.repository.models.transaction.TransactionAttributes.<init>(Unknown Source:28)
	at xyz.hisname.fireflyiii.data.local.dao.ba.a(TransactionDataDao_Impl.java:326)
	at xyz.hisname.fireflyiii.b.k.C.a(TransactionRepository.kt:41)
	at xyz.hisname.fireflyiii.b.k.A.c(Unknown Source:12)
	at d.c.b.a.a.a(ContinuationImpl.kt:3)
	at kotlinx.coroutines.Ea.b(ResumeMode.kt:15)
	at kotlinx.coroutines.internal.z.a(Scopes.kt:4)
	at kotlinx.coroutines.va.a(JobSupport.kt:54)
	at kotlinx.coroutines.va.b(JobSupport.kt:6)
	at kotlinx.coroutines.va.a(JobSupport.kt:95)
	at kotlinx.coroutines.va.b(JobSupport.kt:38)
	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
	at d.c.b.a.a.a(ContinuationImpl.kt:10)
	at kotlinx.coroutines.X.run(Dispatched.kt:15)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)

LOGCAT=02-22 03:12:19.353 W/glide-active-re( 9238): type=1400 audit(0.0:52284): avc: denied { search } for name="background" dev="tmpfs" ino=12589 scontext=u:r:untrusted_app_29:s0:c112,c257,c512,c768 tcontext=u:object_r:blkio:s0 tclass=dir permissive=0 app=xyz.hisname.fireflyiii
02-22 03:12:19.375 I/MaterialDrawer( 9238): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
02-22 03:12:19.696 I/AdrenoGLES-0( 9238): QUALCOMM build                   : 95db91f, Ifbc588260a
02-22 03:12:19.696 I/AdrenoGLES-0( 9238): Build Date                       : 09/24/20
02-22 03:12:19.696 I/AdrenoGLES-0( 9238): OpenGL ES Shader Compiler Version: EV031.32.02.01
02-22 03:12:19.696 I/AdrenoGLES-0( 9238): Local Branch                     : mybrancheafe5b6d-fb5b-f1b0-b904-5cb90179c3e0
02-22 03:12:19.696 I/AdrenoGLES-0( 9238): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r114-rel
02-22 03:12:19.696 I/AdrenoGLES-0( 9238): Remote Branch                    : NONE
02-22 03:12:19.696 I/AdrenoGLES-0( 9238): Reconstruct Branch               : NOTHING
02-22 03:12:19.697 I/AdrenoGLES-0( 9238): Build Config                     : S P 10.0.7 AArch64
02-22 03:12:19.697 I/AdrenoGLES-0( 9238): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
02-22 03:12:19.701 I/AdrenoGLES-0( 9238): PFP: 0x016ee187, ME: 0x00000000
02-22 03:12:19.747 E/RecyclerView( 9238): No adapter attached; skipping layout
02-22 03:12:19.805 I/Gralloc4( 9238): mapper 4.x is not supported
02-22 03:12:19.805 W/Gralloc3( 9238): mapper 3.x is not supported
02-22 03:12:19.865 I/MaterialDrawer( 9238): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
02-22 03:12:20.048 E/RecyclerView( 9238): No adapter attached; skipping layout
02-22 03:12:20.516 E/ACRA    ( 9238): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
02-22 03:12:20.516 E/ACRA    ( 9238): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter description
02-22 03:12:20.516 E/ACRA    ( 9238): 	at xyz.hisname.fireflyiii.repository.models.transaction.TransactionAttributes.<init>(Unknown Source:28)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at xyz.hisname.fireflyiii.data.local.dao.ba.a(TransactionDataDao_Impl.java:326)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at xyz.hisname.fireflyiii.b.k.C.a(TransactionRepository.kt:41)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at xyz.hisname.fireflyiii.b.k.A.c(Unknown Source:12)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at d.c.b.a.a.a(ContinuationImpl.kt:3)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.Ea.b(ResumeMode.kt:15)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.internal.z.a(Scopes.kt:4)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.va.a(JobSupport.kt:54)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.va.b(JobSupport.kt:6)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.va.a(JobSupport.kt:95)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.va.b(JobSupport.kt:38)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at d.c.b.a.a.a(ContinuationImpl.kt:10)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.X.run(Dispatched.kt:15)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
02-22 03:12:20.516 E/ACRA    ( 9238): 	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)
02-22 03:12:20.652 W/Choreographer( 9238): Frame time is 0.133097 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
02-22 03:12:20.664 I/ACRA    ( 9238): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2021-02-22T03:12:20.518-05:00.stacktrace
02-22 03:12:20.694 I/Process ( 9238): Sending signal. PID: 9238 SIG: 9
02-22 03:12:20.798 E/DatabaseUtils( 7870): Writing exception to parcel
02-22 03:12:20.798 E/DatabaseUtils( 7870): java.lang.SecurityException: Permission Denial: reading org.acra.attachment.AcraContentProvider uri content://xyz.hisname.fireflyiii.acra/root/data/user/0/xyz.hisname.fireflyiii/cache/Fireflyiii-mobile.txt from pid=7823, uid=1000 requires the provider be exported, or grantUriPermission()
02-22 03:12:20.798 E/DatabaseUtils( 7870): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
02-22 03:12:20.798 E/DatabaseUtils( 7870): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
02-22 03:12:20.798 E/DatabaseUtils( 7870): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
02-22 03:12:20.798 E/DatabaseUtils( 7870): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
02-22 03:12:20.798 E/DatabaseUtils( 7870): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
02-22 03:12:20.798 E/DatabaseUtils( 7870): 	at android.os.Binder.execTransact(Binder.java:1123)
02-22 03:12:20.829 E/DatabaseUtils( 7870): Writing exception to parcel
02-22 03:12:20.829 E/DatabaseUtils( 7870): java.lang.SecurityException: Permission Denial: reading org.acra.attachment.AcraContentProvider uri content://xyz.hisname.fireflyiii.acra/root/data/user/0/xyz.hisname.fireflyiii/cache/Fireflyiii-mobile.txt from pid=7823, uid=1000 requires the provider be exported, or grantUriPermission()
02-22 03:12:20.829 E/DatabaseUtils( 7870): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:820)
02-22 03:12:20.829 E/DatabaseUtils( 7870): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:684)
02-22 03:12:20.829 E/DatabaseUtils( 7870): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
02-22 03:12:20.829 E/DatabaseUtils( 7870): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:106)
02-22 03:12:20.829 E/DatabaseUtils( 7870): 	at android.os.Binder.execTransactInternal(Binder.java:1154)
02-22 03:12:20.829 E/DatabaseUtils( 7870): 	at android.os.Binder.execTransact(Binder.java:1123)
02-22 03:12:33.042 E/name.fireflyii( 9557): Not starting debugger since process cannot load the jdwp agent.
02-22 03:12:33.065 D/ApplicationLoaders( 9557): Returning zygote-cached class loader: /system/framework/android.test.base.jar
02-22 03:12:33.078 D/NetworkSecurityConfig( 9557): Using Network Security Config from resource network_security_config debugBuild: false
02-22 03:12:33.079 D/NetworkSecurityConfig( 9557): Using Network Security Config from resource network_security_config debugBuild: false
02-22 03:12:33.086 I/MultiDex( 9557): VM with version 2.1.0 has multidex support
02-22 03:12:33.086 I/MultiDex( 9557): Installing application
02-22 03:12:33.086 I/MultiDex( 9557): VM has multidex support, MultiDex support library is disabled.
02-22 03:12:33.098 I/TetheringManager( 9557): registerTetheringEventCallback:xyz.hisname.fireflyiii
02-22 03:12:33.143 I/ACRA    ( 9557): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
02-22 03:12:33.193 W/glide-active-re( 9557): type=1400 audit(0.0:52287): avc: denied { search } for name="background" dev="tmpfs" ino=12589 scontext=u:r:untrusted_app_29:s0:c112,c257,c512,c768 tcontext=u:object_r:blkio:s0 tclass=dir permissive=0 app=xyz.hisname.fireflyiii
02-22 03:12:33.216 I/MaterialDrawer( 9557): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): QUALCOMM build                   : 95db91f, Ifbc588260a
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): Build Date                       : 09/24/20
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): OpenGL ES Shader Compiler Version: EV031.32.02.01
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): Local Branch                     : mybrancheafe5b6d-fb5b-f1b0-b904-5cb90179c3e0
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r114-rel
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): Remote Branch                    : NONE
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): Reconstruct Branch               : NOTHING
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): Build Config                     : S P 10.0.7 AArch64
02-22 03:12:33.517 I/AdrenoGLES-0( 9557): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
02-22 03:12:33.522 I/AdrenoGLES-0( 9557): PFP: 0x016ee187, ME: 0x00000000
02-22 03:12:33.572 E/RecyclerView( 9557): No adapter attached; skipping layout
02-22 03:12:33.627 I/Gralloc4( 9557): mapper 4.x is not supported
02-22 03:12:33.627 W/Gralloc3( 9557): mapper 3.x is not supported
02-22 03:12:33.682 I/MaterialDrawer( 9557): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
02-22 03:12:33.864 E/RecyclerView( 9557): No adapter attached; skipping layout
02-22 03:12:34.307 E/ACRA    ( 9557): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
02-22 03:12:34.307 E/ACRA    ( 9557): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter description
02-22 03:12:34.307 E/ACRA    ( 9557): 	at xyz.hisname.fireflyiii.repository.models.transaction.TransactionAttributes.<init>(Unknown Source:28)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at xyz.hisname.fireflyiii.data.local.dao.ba.a(TransactionDataDao_Impl.java:326)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at xyz.hisname.fireflyiii.b.k.C.a(TransactionRepository.kt:41)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at xyz.hisname.fireflyiii.b.k.A.c(Unknown Source:12)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at d.c.b.a.a.a(ContinuationImpl.kt:3)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.Ea.b(ResumeMode.kt:15)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.internal.z.a(Scopes.kt:4)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.va.a(JobSupport.kt:54)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.va.b(JobSupport.kt:6)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.va.a(JobSupport.kt:95)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.va.b(JobSupport.kt:38)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at d.c.b.a.a.a(ContinuationImpl.kt:10)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.X.run(Dispatched.kt:15)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
02-22 03:12:34.307 E/ACRA    ( 9557): 	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)
IS_SILENT=false
USER_CRASH_DATE=2021-02-22T03:12:34.310-05:00
```

**Comment by ryan77627** [comment]
Please excuse my being dumb, I noticed the version string in the log a bit too late. For whatever reason fdroid downloaded a **really** old version. Sorry!
