### ISSUE TITLE
App crashes due to Firefly III > 5.5.3 returning DateTime strings instead of Date only strings

### ISSUE THREAD

**Issue by ruifung** [emansih/FireflyMobile#161]
**Firefly III Server Version:**
5.5.6
**Firefly III Mobile Version:**
4.6.0
**Android Version:**  
10
**Device Information:**  
- BRAND: Nokia
- MODEL:  6.1 Plus
--------------------------------------

## Expected Behavior
Going into piggy bank screen should display list of piggy banks

## Current Behavior
It crashes due to firefly API changes now returning ISO Date-Time strings rather then Date only strings
Probably should be using ZonedDateTime rather then LocalDate now.

## Steps to Reproduce
Attempt to load piggy bank screen on firefly version > 5.5.3
See https://github.com/firefly-iii/firefly-iii/releases/tag/5.5.3

```
REPORT_ID=ca209b62-2f7b-498d-be73-3bd45dbd4de4
APP_VERSION_NAME=4.6.0
PHONE_MODEL=Nokia 6.1 Plus
BRAND=Nokia
PRODUCT=Dragon_00WW
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=j$.time.format.e: Text '2021-12-31T00:00:00+08:00' could not be parsed, unparsed text found at index 10
	at j$.time.format.DateTimeFormatter.e(:2)
	at j$.time.format.DateTimeFormatter.parse(:2)
	at j$.time.LocalDate.parse(:2)
	at xyz.hisname.fireflyiii.ui.piggybank.PiggyRecyclerAdapter.onBindViewHolder(PiggyRecyclerAdapter.kt:36)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:156)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
	at android.view.View.layout(View.java:21916)
	at android.view.ViewGroup.layout(ViewGroup.java:6260)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3081)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2591)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1722)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7605)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
	at android.view.Choreographer.doFrame(Choreographer.java:799)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7397)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

LOGCAT=04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3081)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2591)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1722)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7605)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.Choreographer.doFrame(Choreographer.java:799)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.os.Handler.handleCallback(Handler.java:883)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.os.Looper.loop(Looper.java:214)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at java.lang.reflect.Method.invoke(Native Method)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-11 08:45:29.914 E/AndroidRuntime(14273): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
04-11 08:45:29.914 E/ACRA    (14273): ACRA caught a e for xyz.hisname.fireflyiii
04-11 08:45:29.914 E/ACRA    (14273): j$.time.format.e: Text '2021-12-31T00:00:00+08:00' could not be parsed, unparsed text found at index 10
04-11 08:45:29.914 E/ACRA    (14273): 	at j$.time.format.DateTimeFormatter.e(:2)
04-11 08:45:29.914 E/ACRA    (14273): 	at j$.time.format.DateTimeFormatter.parse(:2)
04-11 08:45:29.914 E/ACRA    (14273): 	at j$.time.LocalDate.parse(:2)
04-11 08:45:29.914 E/ACRA    (14273): 	at xyz.hisname.fireflyiii.ui.piggybank.PiggyRecyclerAdapter.onBindViewHolder(PiggyRecyclerAdapter.kt:36)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:1)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:9)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:156)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:9)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:12)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:119)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:12)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:15)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:3)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:11)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:12)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:23)
04-11 08:45:29.914 E/ACRA    (14273): 	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:1)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:8)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:10)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
04-11 08:45:29.914 E/ACRA    (14273): 	at com.android.internal.policy.DecorView.onLayout(DecorView.java:779)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.View.layout(View.java:21916)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewGroup.layout(ViewGroup.java:6260)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3081)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2591)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1722)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7605)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1041)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.Choreographer.doCallbacks(Choreographer.java:864)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.Choreographer.doFrame(Choreographer.java:799)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1026)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.os.Handler.handleCallback(Handler.java:883)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.os.Handler.dispatchMessage(Handler.java:100)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.os.Looper.loop(Looper.java:214)
04-11 08:45:29.914 E/ACRA    (14273): 	at android.app.ActivityThread.main(ActivityThread.java:7397)
04-11 08:45:29.914 E/ACRA    (14273): 	at java.lang.reflect.Method.invoke(Native Method)
04-11 08:45:29.914 E/ACRA    (14273): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
04-11 08:45:29.914 E/ACRA    (14273): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
IS_SILENT=false
USER_CRASH_DATE=2021-04-11T08:45:29.927+08:00
```

**Comment by emansih** [comment]
I'm aware of it but I don't have the time to fix it. Will fix it by the end of the month

**Comment by emansih** [comment]
It's rolling out via Google Play Store as we speak.
