### ISSUE TITLE
Login Fail with PAT / Oauth in the same network

### ISSUE THREAD

**Issue by los2pollos** [emansih/FireflyMobile#171]
**Firefly III Server Version:**
Version 5.5.12

**Firefly III Mobile Version:**
Version 4.9.0

**Android Version:**  
Android 10 - Lineage OS

**Device Information:**  

- BRAND: Samsung
- MODEL: Note 9
--------------------------------------

## Expected Behavior
Login with PAT / OAuth. The server is in my same network since I have it running in a docker container on my personal server. I don't have a domain to provide and the server is not exposed to the internet. 

## Current Behavior
Fail

## Steps to Reproduce
I use IP:Port and provide the secret / token. None of them works. I've tried different browsers. None of them succeeds. There is a SSL problem. 
Do I need to create a self-signed certificate?

**Comment by emansih** [comment]
Hi. The app only supports HTTPS protocol

**Comment by los2pollos** [comment]
So far as I have understood, Firefly III does not support HTTPS. So what is the solution?
Can I enable HTTPS on Firefly III?

**Comment by emansih** [comment]
Hi. Yes you can enable HTTPS on Firefly III. I do not know what is your setup. I suggest reading the manual at https://docs.firefly-iii.org/firefly-iii/

**Comment by los2pollos** [comment]
I've used docker-compose -d up with these two files adapted to my setup:
[https://dbtechreviews.com/wp-content/uploads/2020/08/Firefly-III.zip](url)

The app is up and running.
Firefly is on port 8003 on the same host that was composed with, same IP. 
I've found this guide: [https://gist.github.com/optimistic5/ca5a4a8593dcdb7360f712d37a0cc657](url), but I'm not very sure about next steps.

**Comment by emansih** [comment]
Are you using self signed cert or let's encrypt?

**Comment by los2pollos** [comment]
I'm not using none of them. I can not understand how to set certificates up for Firefly. It's running in a Docker container.
Should I create a self signed cert for the FireFlyMobile app straightly from the system that hosts the Firefly container?

**Comment by emansih** [comment]
Hi. This is out of scope of this project. What I can tell you is you will need to create a cert for your docker container and if it's a self signed cert, import it to your android device or import it via the app.

**Comment by los2pollos** [comment]
I got this error while using the self signed certificate I created in the docker container

REPORT_ID=1be233c1-9158-4337-8928-3d42514327cb
APP_VERSION_NAME=4.9.0
PHONE_MODEL=SM-N960F
BRAND=samsung
PRODUCT=crownltexx
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
... 1 more
Caused by: java.io.FileNotFoundException: No content provider: /storage/emulated/0/Download/firefly_cert.crt
at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1673)
at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
at xyz.hisname.fireflyiii.ui.onboarding.AuthActivityViewModel.authViaPat(AuthActivityViewModel.kt:9)
at xyz.hisname.fireflyiii.ui.onboarding.PatFragment$signInButtonClick$1.onClick(PatFragment.kt:5)
at android.view.View.performClick(View.java:7259)
at android.view.View.performClickInternal(View.java:7236)
at android.view.View.access$3600(View.java:801)
at android.view.View$PerformClick.run(View.java:27892)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
... 3 more

LOGCAT=06-14 14:29:41.096 W/ActivityThread( 4850): handleWindowVisibility: no activity for token android.os.BinderProxy@b7c6fb0
06-14 14:29:41.172 I/mali_winsys( 4850): new_window_surface() [1440x2960] return: 0x3000
06-14 14:29:41.176 W/Gralloc3( 4850): mapper 3.x is not supported
06-14 14:29:41.178 I/gralloc ( 4850): Arm Module v1.0
06-14 14:29:41.195 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:29:41.196 I/mali_winsys( 4850): delete_surface() [1440x2960] return
06-14 14:29:41.196 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:29:41.196 W/libEGL  ( 4850): EGLNativeWindowType 0x767781ce50 disconnect failed
06-14 14:29:41.215 W/ActivityThread( 4850): Activity state must be in [ON_RESUME..ON_STOP] in order to be relaunched,current state is 1
06-14 14:29:41.220 I/mali_winsys( 4850): new_window_surface() [1440x2960] return: 0x3000
06-14 14:29:49.691 I/mali_winsys( 4850): new_window_surface() [818x151] return: 0x3000
06-14 14:29:53.165 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:29:53.172 I/mali_winsys( 4850): delete_surface() [818x151] return
06-14 14:29:53.172 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:29:53.173 W/libEGL  ( 4850): EGLNativeWindowType 0x770c7c99d0 disconnect failed
06-14 14:29:54.927 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:29:54.928 I/mali_winsys( 4850): delete_surface() [1440x2960] return
06-14 14:29:54.928 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:29:54.929 W/libEGL  ( 4850): EGLNativeWindowType 0x767781ce50 disconnect failed
06-14 14:30:02.060 I/mali_winsys( 4850): new_window_surface() [1440x2960] return: 0x3000
06-14 14:30:04.179 I/mali_winsys( 4850): new_window_surface() [818x151] return: 0x3000
06-14 14:30:07.015 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:30:07.017 I/mali_winsys( 4850): delete_surface() [1440x2960] return
06-14 14:30:07.017 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:30:07.018 W/libEGL  ( 4850): EGLNativeWindowType 0x7620bbf190 disconnect failed
06-14 14:30:07.653 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:30:07.654 I/mali_winsys( 4850): delete_surface() [818x151] return
06-14 14:30:07.654 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:30:07.655 W/libEGL  ( 4850): EGLNativeWindowType 0x7620bbec90 disconnect failed
06-14 14:30:09.640 I/mali_winsys( 4850): new_window_surface() [1440x2960] return: 0x3000
06-14 14:30:24.935 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:30:24.938 I/mali_winsys( 4850): delete_surface() [1440x2960] return
06-14 14:30:24.938 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:30:24.939 W/libEGL  ( 4850): EGLNativeWindowType 0x7620bbec90 disconnect failed
06-14 14:31:26.137 I/mali_winsys( 4850): new_window_surface() [1440x2960] return: 0x3000
06-14 14:31:28.306 I/mali_winsys( 4850): new_window_surface() [132x132] return: 0x3000
06-14 14:31:28.469 I/mali_winsys( 4850): new_window_surface() [332x210] return: 0x3000
06-14 14:31:28.993 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:31:28.994 I/mali_winsys( 4850): delete_surface() [132x132] return
06-14 14:31:28.994 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:31:28.994 W/libEGL  ( 4850): EGLNativeWindowType 0x760b3e0dd0 disconnect failed
06-14 14:31:28.997 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:31:28.997 I/mali_winsys( 4850): delete_surface() [332x210] return
06-14 14:31:28.997 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:31:28.997 W/libEGL  ( 4850): EGLNativeWindowType 0x770c6ecb10 disconnect failed
06-14 14:31:28.997 D/OpenGLRenderer( 4850): endAllActiveAnimators on 0x760b38cf00 (RippleDrawable) with handle 0x767794e660
06-14 14:31:29.692 I/mali_winsys( 4850): new_window_surface() [132x132] return: 0x3000
06-14 14:31:30.310 I/mali_egl( 4850): eglDestroySurface() in
06-14 14:31:30.310 I/mali_winsys( 4850): delete_surface() [132x132] return
06-14 14:31:30.310 I/mali_egl( 4850): eglDestroySurface() out
06-14 14:31:30.311 W/libEGL  ( 4850): EGLNativeWindowType 0x760b3e2450 disconnect failed
06-14 14:31:35.453 D/AndroidRuntime( 4850): Shutting down VM
--------- beginning of crash
06-14 14:31:35.454 E/AndroidRuntime( 4850): FATAL EXCEPTION: main
06-14 14:31:35.454 E/AndroidRuntime( 4850): Process: xyz.hisname.fireflyiii, PID: 4850
06-14 14:31:35.454 E/AndroidRuntime( 4850): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
06-14 14:31:35.454 E/AndroidRuntime( 4850): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
06-14 14:31:35.454 E/AndroidRuntime( 4850): Caused by: java.lang.reflect.InvocationTargetException
06-14 14:31:35.454 E/AndroidRuntime( 4850): at java.lang.reflect.Method.invoke(Native Method)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-14 14:31:35.454 E/AndroidRuntime( 4850): ... 1 more
06-14 14:31:35.454 E/AndroidRuntime( 4850): Caused by: java.io.FileNotFoundException: No content provider: /storage/emulated/0/Download/firefly_cert.crt
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1673)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at xyz.hisname.fireflyiii.ui.onboarding.AuthActivityViewModel.authViaPat(AuthActivityViewModel.kt:9)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at xyz.hisname.fireflyiii.ui.onboarding.PatFragment$signInButtonClick$1.onClick(PatFragment.kt:5)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.view.View.performClick(View.java:7259)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.view.View.performClickInternal(View.java:7236)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.view.View.access$3600(View.java:801)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.view.View$PerformClick.run(View.java:27892)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.os.Handler.handleCallback(Handler.java:883)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.os.Handler.dispatchMessage(Handler.java:100)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.os.Looper.loop(Looper.java:214)
06-14 14:31:35.454 E/AndroidRuntime( 4850): at android.app.ActivityThread.main(ActivityThread.java:7356)
06-14 14:31:35.454 E/AndroidRuntime( 4850): ... 3 more
06-14 14:31:35.455 E/ACRA    ( 4850): ACRA caught a RuntimeException for xyz.hisname.fireflyiii
06-14 14:31:35.455 E/ACRA    ( 4850): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
06-14 14:31:35.455 E/ACRA    ( 4850): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:501)
06-14 14:31:35.455 E/ACRA    ( 4850): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
06-14 14:31:35.455 E/ACRA    ( 4850): Caused by: java.lang.reflect.InvocationTargetException
06-14 14:31:35.455 E/ACRA    ( 4850): at java.lang.reflect.Method.invoke(Native Method)
06-14 14:31:35.455 E/ACRA    ( 4850): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
06-14 14:31:35.455 E/ACRA    ( 4850): ... 1 more
06-14 14:31:35.455 E/ACRA    ( 4850): Caused by: java.io.FileNotFoundException: No content provider: /storage/emulated/0/Download/firefly_cert.crt
06-14 14:31:35.455 E/ACRA    ( 4850): at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1673)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1503)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.content.ContentResolver.openInputStream(ContentResolver.java:1187)
06-14 14:31:35.455 E/ACRA    ( 4850): at xyz.hisname.fireflyiii.ui.onboarding.AuthActivityViewModel.authViaPat(AuthActivityViewModel.kt:9)
06-14 14:31:35.455 E/ACRA    ( 4850): at xyz.hisname.fireflyiii.ui.onboarding.PatFragment$signInButtonClick$1.onClick(PatFragment.kt:5)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.view.View.performClick(View.java:7259)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.view.View.performClickInternal(View.java:7236)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.view.View.access$3600(View.java:801)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.view.View$PerformClick.run(View.java:27892)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.os.Handler.handleCallback(Handler.java:883)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.os.Handler.dispatchMessage(Handler.java:100)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.os.Looper.loop(Looper.java:214)
06-14 14:31:35.455 E/ACRA    ( 4850): at android.app.ActivityThread.main(ActivityThread.java:7356)
06-14 14:31:35.455 E/ACRA    ( 4850): ... 3 more
IS_SILENT=false
USER_CRASH_DATE=2021-06-14T14:31:35.461+02:00

**Comment by emansih** [comment]
Sorry about that. I recently got back to development again. I will look into your issue.

**Comment by emansih** [comment]
@los2pollos Hi. How do i replicate this bug? What are the steps you did to crash the app?
