### ISSUE TITLE
New App Version crashes on startup

### ISSUE THREAD

**Issue by Jezz3** [emansih/FireflyMobile#184]
**Firefly III Server Version:**
5.6.2

**Firefly III Mobile Version:**
4.14.0/i think it also happens on 4.13.1

**Android Version:**  
Android 11

**Device Information:**  
- BRAND: Samsung
- MODEL: Galaxy A40
--------------------------------------

## Current Behavior
App crashes on startup

## Steps to Reproduce
Install App, Start App

```
REPORT_ID=ee983e6c-ba45-406c-9a0b-c4d54848f01a
APP_VERSION_NAME=4.14.0
PHONE_MODEL=SM-A405FN
BRAND=samsung
PRODUCT=a40eea
ANDROID_VERSION=11
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:4)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:501)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
	at xyz.hisname.fireflyiii.data.local.dao.BillDataDao_Impl.getBillDueFromDate(BillDataDao_Impl.java:4)
	at xyz.hisname.fireflyiii.repository.bills.BillRepository.getBillDueFromDate(BillRepository.kt:1)
	at xyz.hisname.fireflyiii.ui.HomeViewModel$getNoOfBillsDueToday$1.invokeSuspend(HomeViewModel.kt:6)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

LOGCAT=--------- beginning of main
10-13 23:41:12.810 D/ActivityThread(11808): setConscryptValidator - put
--------- beginning of system
10-13 23:41:12.909 D/ActivityThread(11808): handleBindApplication()++ app=xyz.hisname.fireflyiii
10-13 23:41:12.960 D/ActivityThread(11808): handleBindApplication() -- skipGraphicsSupport=false
10-13 23:41:12.961 D/ActivityThread(11808): ActivityThread::handleMakeApplication() data=AppBindData{appInfo=ApplicationInfo{603a8d6 xyz.hisname.fireflyiii}} appContext=android.app.ContextImpl@8844757 appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@2591244 data.restrictedBackupMode= false data.providers= [ContentProviderInfo{name=xyz.hisname.fireflyiii.workmanager-init className=androidx.work.impl.WorkManagerInitializer}, ContentProviderInfo{name=xyz.hisname.fireflyiii.provider className=androidx.core.content.FileProvider}, ContentProviderInfo{name=xyz.hisname.fireflyiii.androidx-startup className=androidx.startup.InitializationProvider}] Caller=android.app.ActivityThread.handleBindApplication:7446 android.app.ActivityThread.access$1400:301 android.app.ActivityThread$H.handleMessage:2148 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 
10-13 23:41:12.964 D/LoadedApk(11808): LoadedApk::makeApplication() appContext=android.app.ContextImpl@815af2d appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@2591244
10-13 23:41:12.964 D/NetworkSecurityConfig(11808): Using Network Security Config from resource network_security_config debugBuild: false
10-13 23:41:12.970 D/NetworkSecurityConfig(11808): Using Network Security Config from resource network_security_config debugBuild: false
10-13 23:41:12.972 W/name.fireflyii(11808): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
10-13 23:41:12.972 W/name.fireflyii(11808): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
10-13 23:41:12.972 W/name.fireflyii(11808): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
10-13 23:41:12.996 I/TetheringManager(11808): registerTetheringEventCallback:xyz.hisname.fireflyiii
10-13 23:41:12.997 D/ConnectivityManager(11808): ConnectivityManager() mContext=xyz.hisname.fireflyiii.CustomApp@49c01f3 getOpPackageName()=xyz.hisname.fireflyiii getBasePackageName()=xyz.hisname.fireflyiii getPackageName()=xyz.hisname.fireflyiii
10-13 23:41:13.099 I/DecorView(11808): [INFO] isPopOver=false, config=true
10-13 23:41:13.099 I/DecorView(11808): updateCaptionType >> DecorView@a9d22de[], isFloating=false, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=true
10-13 23:41:13.099 D/DecorView(11808): setCaptionType = 0, this = DecorView@a9d22de[]
10-13 23:41:13.103 I/ACRA    (11808): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
10-13 23:41:13.174 E/ACRA    (11808): ACRA caught a IllegalStateException for xyz.hisname.fireflyiii
10-13 23:41:13.174 E/ACRA    (11808): java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
10-13 23:41:13.174 E/ACRA    (11808): 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
10-13 23:41:13.174 E/ACRA    (11808): 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:4)
10-13 23:41:13.174 E/ACRA    (11808): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:501)
10-13 23:41:13.174 E/ACRA    (11808): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
10-13 23:41:13.174 E/ACRA    (11808): 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
10-13 23:41:13.174 E/ACRA    (11808): 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
10-13 23:41:13.174 E/ACRA    (11808): 	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
10-13 23:41:13.174 E/ACRA    (11808): 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
10-13 23:41:13.174 E/ACRA    (11808): 	at xyz.hisname.fireflyiii.data.local.dao.BillDataDao_Impl.getBillDueFromDate(BillDataDao_Impl.java:4)
10-13 23:41:13.174 E/ACRA    (11808): 	at xyz.hisname.fireflyiii.repository.bills.BillRepository.getBillDueFromDate(BillRepository.kt:1)
10-13 23:41:13.174 E/ACRA    (11808): 	at xyz.hisname.fireflyiii.ui.HomeViewModel$getNoOfBillsDueToday$1.invokeSuspend(HomeViewModel.kt:6)
10-13 23:41:13.174 E/ACRA    (11808): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
10-13 23:41:13.174 E/ACRA    (11808): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
10-13 23:41:13.174 E/ACRA    (11808): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-13 23:41:13.174 E/ACRA    (11808): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
10-13 23:41:13.272 D/InputTransport(11808): Input channel constructed: 'ed193b0', fd=79
10-13 23:41:13.274 I/ViewRootImpl@82e07ee[HomeActivity](11808): setView = com.android.internal.policy.DecorView@a9d22de TM=true
10-13 23:41:13.319 I/SurfaceControl(11808): assignNativeObject: nativeObject = 0 Surface(name=null)/@0x8f9efe2 / android.view.SurfaceControl.readFromParcel:1115 android.view.IWindowSession$Stub$Proxy.relayout:1820 android.view.ViewRootImpl.relayoutWindow:9005 android.view.ViewRootImpl.performTraversals:3360 android.view.ViewRootImpl.doTraversal:2618 android.view.ViewRootImpl$TraversalRunnable.run:9971 android.view.Choreographer$CallbackRecord.run:1010 android.view.Choreographer.doCallbacks:809 android.view.Choreographer.doFrame:744 android.view.Choreographer$FrameDisplayEventReceiver.run:995 
10-13 23:41:13.320 I/ViewRootImpl@82e07ee[HomeActivity](11808): Relayout returned: old=(0,0,1080,2340) new=(0,0,1080,2340) req=(1080,2340)0 dur=12 res=0x7 s={true 501862797312} ch=true fn=-1
10-13 23:41:13.325 W/RecyclerView(11808): No adapter attached; skipping layout
10-13 23:41:13.395 I/ViewRootImpl@82e07ee[HomeActivity](11808): [DP] dp(1) 1 android.view.ViewRootImpl.reportNextDraw:10957 android.view.ViewRootImpl.performTraversals:3845 android.view.ViewRootImpl.doTraversal:2618 
10-13 23:41:13.395 I/ViewRootImpl@82e07ee[HomeActivity](11808): [DP] pd() Asnyc report
10-13 23:41:13.412 I/Gralloc4(11808): mapper 4.x is not supported
10-13 23:41:13.413 W/Gralloc3(11808): mapper 3.x is not supported
10-13 23:41:13.415 I/gralloc (11808): Arm Module v1.0
10-13 23:41:13.503 I/ViewRootImpl@82e07ee[HomeActivity](11808): [DP] pdf(0) 1 android.view.ViewRootImpl.lambda$performDraw$1$ViewRootImpl:4668 android.view.-$$Lambda$ViewRootImpl$DJd0VUYJgsebcnSohO6h8zc_ONI.run:6 android.os.Handler.handleCallback:938 
10-13 23:41:13.503 I/ViewRootImpl@82e07ee[HomeActivity](11808): [DP] rdf()
10-13 23:41:13.533 I/ViewRootImpl@82e07ee[HomeActivity](11808): MSG_WINDOW_FOCUS_CHANGED 1 1
10-13 23:41:13.533 D/InputMethodManager(11808): prepareNavigationBarInfo() DecorView@a9d22de[HomeActivity]
10-13 23:41:13.533 D/InputMethodManager(11808): getNavigationBarColor() -12808772
10-13 23:41:13.535 D/InputMethodManager(11808): prepareNavigationBarInfo() DecorView@a9d22de[HomeActivity]
10-13 23:41:13.535 D/InputMethodManager(11808): getNavigationBarColor() -12808772
10-13 23:41:13.535 V/InputMethodManager(11808): Starting input: tba=xyz.hisname.fireflyiii ic=null mNaviBarColor -12808772 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
10-13 23:41:13.535 D/InputMethodManager(11808): startInputInner - Id : 0
10-13 23:41:13.535 I/InputMethodManager(11808): startInputInner - mService.startInputOrWindowGainedFocus
10-13 23:41:13.543 D/InputTransport(11808): Input channel constructed: 'ClientS', fd=82
10-13 23:41:13.544 D/InputMethodManager(11808): prepareNavigationBarInfo() DecorView@a9d22de[HomeActivity]
10-13 23:41:13.544 D/InputMethodManager(11808): getNavigationBarColor() -12808772
10-13 23:41:13.544 V/InputMethodManager(11808): Starting input: tba=xyz.hisname.fireflyiii ic=null mNaviBarColor -12808772 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
10-13 23:41:13.544 D/InputMethodManager(11808): startInputInner - Id : 0
10-13 23:41:13.551 D/SurfaceControl(11808): hide : mNativeObject = 501866708832 - sc.mNativeObject = 502056305856 - Surface(name=Surface(name=ad9a57c InputMethod)/@0x5b20750 - animation-leash)/@0x8a28242
10-13 23:41:13.551 D/SurfaceControl(11808): nativeSetFlags Done : Surface(name=Surface(name=ad9a57c InputMethod)/@0x5b20750 - animation-leash)/@0x8a28242
10-13 23:41:13.552 I/SurfaceControl(11808): release : mNativeObject = 502056303552 - Surface(name=Surface(name=236cf17 NavigationBar0)/@0xbdd0339 - animation-leash)/@0x1edc253 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
10-13 23:41:13.552 I/SurfaceControl(11808): nativeRelease nativeObject s[502056303552]
10-13 23:41:13.552 I/SurfaceControl(11808): nativeRelease nativeObject e[502056303552]
10-13 23:41:13.552 I/SurfaceControl(11808): release : mNativeObject = 502056302880 - Surface(name=Surface(name=d3bd059 StatusBar)/@0x871a03d - animation-leash)/@0x2a33790 / android.view.-$$Lambda$Rl1VZmNJ0VZDLK0BAbaVGis0rrA.accept:2 android.view.InsetsSourceControl.release:170 android.view.InsetsSourceConsumer.setControl:202 android.view.InsetsController.onControlsChanged:833 
10-13 23:41:13.553 I/SurfaceControl(11808): nativeRelease nativeObject s[502056302880]
10-13 23:41:13.553 I/SurfaceControl(11808): nativeRelease nativeObject e[502056302880]
10-13 23:41:13.916 I/ACRA    (11808): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2021-10-13T23:41:13.180+02:00.stacktrace
10-13 23:41:13.926 W/Bundle  (11808): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
10-13 23:41:13.926 W/Bundle  (11808): Attempt to cast generated internal exception:
10-13 23:41:13.926 W/Bundle  (11808): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
10-13 23:41:13.926 W/Bundle  (11808): 	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1343)
10-13 23:41:13.926 W/Bundle  (11808): 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1145)
10-13 23:41:13.926 W/Bundle  (11808): 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:9005)
10-13 23:41:13.926 W/Bundle  (11808): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:12041)
10-13 23:41:13.926 W/Bundle  (11808): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1721)
10-13 23:41:13.926 W/Bundle  (11808): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1074)
10-13 23:41:13.926 W/Bundle  (11808): 	at android.app.ContextImpl.startActivity(ContextImpl.java:1045)
10-13 23:41:13.926 W/Bundle  (11808): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:413)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:30)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.sender.ReportSender$-CC.$default$send(ReportSender.kt:1)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.sender.EmailIntentSender.send(Unknown Source:0)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:6)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:5)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:12)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:48)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:7)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.builder.ReportExecutor.execute(ReportExecutor.kt:38)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.builder.ReportBuilder.build(ReportBuilder.kt:3)
10-13 23:41:13.926 W/Bundle  (11808): 	at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.kt:11)
10-13 23:41:13.926 W/Bundle  (11808): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
10-13 23:41:13.926 W/Bundle  (11808): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.android.AndroidExceptionPreHandler.handleException(AndroidExceptionPreHandler.kt:3)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.CoroutineExceptionHandlerImplKt.handleCoroutineExceptionImpl(CoroutineExceptionHandlerImpl.kt:2)
10-13 23:41:13.926 W/Bundle  (11808): 	at com.mikepenz.materialdrawer.R$layout.handleCoroutineException(Unknown Source:2)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.StandaloneCoroutine.handleJobException(Builders.common.kt:1)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:21)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:26)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:2)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:2)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-13 23:41:13.926 W/Bundle  (11808): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)
10-13 23:41:13.955 I/Process (11808): Sending signal. PID: 11808 SIG: 9
10-13 23:41:14.219 E/fireflyiii:acr(12015): Not starting debugger since process cannot load the jdwp agent.
10-13 23:41:14.231 D/ActivityThread(12015): setConscryptValidator
10-13 23:41:14.231 D/ActivityThread(12015): setConscryptValidator - put
10-13 23:41:14.245 D/ActivityThread(12015): handleBindApplication()++ app=xyz.hisname.fireflyiii:acra
10-13 23:41:14.302 D/ActivityThread(12015): handleBindApplication() -- skipGraphicsSupport=false
10-13 23:41:14.303 D/ActivityThread(12015): ActivityThread::handleMakeApplication() data=AppBindData{appInfo=ApplicationInfo{603a8d6 xyz.hisname.fireflyiii}} appContext=android.app.ContextImpl@8844757 appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@2591244 data.restrictedBackupMode= false data.providers= [ContentProviderInfo{name=xyz.hisname.fireflyiii.acra className=org.acra.attachment.AcraContentProvider}] Caller=android.app.ActivityThread.handleBindApplication:7446 android.app.ActivityThread.access$1400:301 android.app.ActivityThread$H.handleMessage:2148 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 
10-13 23:41:14.305 D/LoadedApk(12015): LoadedApk::makeApplication() appContext=android.app.ContextImpl@815af2d appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@2591244
10-13 23:41:14.305 D/NetworkSecurityConfig(12015): Using Network Security Config from resource network_security_config debugBuild: false
10-13 23:41:14.323 D/NetworkSecurityConfig(12015): Using Network Security Config from resource network_security_config debugBuild: false
10-13 23:41:17.192 E/name.fireflyii(11867): Not starting debugger since process cannot load the jdwp agent.
10-13 23:41:17.208 D/ActivityThread(11867): setConscryptValidator
10-13 23:41:17.208 D/ActivityThread(11867): setConscryptValidator - put
10-13 23:41:17.226 D/ActivityThread(11867): handleBindApplication()++ app=xyz.hisname.fireflyiii
10-13 23:41:17.295 D/ActivityThread(11867): handleBindApplication() -- skipGraphicsSupport=false
10-13 23:41:17.295 D/ActivityThread(11867): ActivityThread::handleMakeApplication() data=AppBindData{appInfo=ApplicationInfo{603a8d6 xyz.hisname.fireflyiii}} appContext=android.app.ContextImpl@8844757 appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@2591244 data.restrictedBackupMode= false data.providers= [ContentProviderInfo{name=xyz.hisname.fireflyiii.workmanager-init className=androidx.work.impl.WorkManagerInitializer}, ContentProviderInfo{name=xyz.hisname.fireflyiii.provider className=androidx.core.content.FileProvider}, ContentProviderInfo{name=xyz.hisname.fireflyiii.androidx-startup className=androidx.startup.InitializationProvider}] Caller=android.app.ActivityThread.handleBindApplication:7446 android.app.ActivityThread.access$1400:301 android.app.ActivityThread$H.handleMessage:2148 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 
10-13 23:41:17.298 D/LoadedApk(11867): LoadedApk::makeApplication() appContext=android.app.ContextImpl@815af2d appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@2591244
10-13 23:41:17.298 D/NetworkSecurityConfig(11867): Using Network Security Config from resource network_security_config debugBuild: false
10-13 23:41:17.309 D/NetworkSecurityConfig(11867): Using Network Security Config from resource network_security_config debugBuild: false
10-13 23:41:17.312 W/name.fireflyii(11867): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
10-13 23:41:17.313 W/name.fireflyii(11867): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
10-13 23:41:17.313 W/name.fireflyii(11867): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
10-13 23:41:17.323 I/TetheringManager(11867): registerTetheringEventCallback:xyz.hisname.fireflyiii
10-13 23:41:17.324 D/ConnectivityManager(11867): ConnectivityManager() mContext=xyz.hisname.fireflyiii.CustomApp@49c01f3 getOpPackageName()=xyz.hisname.fireflyiii getBasePackageName()=xyz.hisname.fireflyiii getPackageName()=xyz.hisname.fireflyiii
10-13 23:41:17.420 I/ACRA    (11867): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
10-13 23:41:22.285 I/name.fireflyii(11867): Waiting for a blocking GC ProfileSaver
10-13 23:41:22.303 I/name.fireflyii(11867): WaitForGcToComplete blocked ProfileSaver on AddRemoveAppImageSpace for 18.320ms
10-13 23:41:22.316 I/name.fireflyii(11867): WaitForGcToComplete blocked RunEmptyCheckpoint on ProfileSaver for 12.597ms
10-13 23:41:53.670 E/name.fireflyii(12126): Not starting debugger since process cannot load the jdwp agent.
10-13 23:41:53.697 D/ActivityThread(12126): setConscryptValidator
10-13 23:41:53.697 D/ActivityThread(12126): setConscryptValidator - put
10-13 23:41:53.819 D/ActivityThread(12126): handleBindApplication()++ app=xyz.hisname.fireflyiii
10-13 23:41:53.869 D/ActivityThread(12126): handleBindApplication() -- skipGraphicsSupport=false
10-13 23:41:53.870 D/ActivityThread(12126): ActivityThread::handleMakeApplication() data=AppBindData{appInfo=ApplicationInfo{603a8d6 xyz.hisname.fireflyiii}} appContext=android.app.ContextImpl@8844757 appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@2591244 data.restrictedBackupMode= false data.providers= [ContentProviderInfo{name=xyz.hisname.fireflyiii.workmanager-init className=androidx.work.impl.WorkManagerInitializer}, ContentProviderInfo{name=xyz.hisname.fireflyiii.provider className=androidx.core.content.FileProvider}, ContentProviderInfo{name=xyz.hisname.fireflyiii.androidx-startup className=androidx.startup.InitializationProvider}] Caller=android.app.ActivityThread.handleBindApplication:7446 android.app.ActivityThread.access$1400:301 android.app.ActivityThread$H.handleMessage:2148 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 
10-13 23:41:53.880 D/LoadedApk(12126): LoadedApk::makeApplication() appContext=android.app.ContextImpl@815af2d appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@2591244
10-13 23:41:53.881 D/NetworkSecurityConfig(12126): Using Network Security Config from resource network_security_config debugBuild: false
10-13 23:41:53.886 D/NetworkSecurityConfig(12126): Using Network Security Config from resource network_security_config debugBuild: false
10-13 23:41:53.889 W/name.fireflyii(12126): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
10-13 23:41:53.889 W/name.fireflyii(12126): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
10-13 23:41:53.889 W/name.fireflyii(12126): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
10-13 23:41:53.928 I/TetheringManager(12126): registerTetheringEventCallback:xyz.hisname.fireflyiii
10-13 23:41:53.929 D/ConnectivityManager(12126): ConnectivityManager() mContext=xyz.hisname.fireflyiii.CustomApp@49c01f3 getOpPackageName()=xyz.hisname.fireflyiii getBasePackageName()=xyz.hisname.fireflyiii getPackageName()=xyz.hisname.fireflyiii
10-13 23:41:54.038 I/ACRA    (12126): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
10-13 23:41:54.071 I/DecorView(12126): [INFO] isPopOver=false, config=true
10-13 23:41:54.071 I/DecorView(12126): updateCaptionType >> DecorView@e8855db[], isFloating=false, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=true
10-13 23:41:54.071 D/DecorView(12126): setCaptionType = 0, this = DecorView@e8855db[]
10-13 23:41:54.184 E/ACRA    (12126): ACRA caught a IllegalStateException for xyz.hisname.fireflyiii
10-13 23:41:54.184 E/ACRA    (12126): java.lang.IllegalStateException: Room cannot verify the data integrity. Looks like you've changed schema but forgot to update the version number. You can simply fix this by increasing the version number.
10-13 23:41:54.184 E/ACRA    (12126): 	at androidx.room.RoomOpenHelper.onOpen(RoomOpenHelper.java:9)
10-13 23:41:54.184 E/ACRA    (12126): 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onOpen(FrameworkSQLiteOpenHelper.java:4)
10-13 23:41:54.184 E/ACRA    (12126): 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:501)
10-13 23:41:54.184 E/ACRA    (12126): 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:387)
10-13 23:41:54.184 E/ACRA    (12126): 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:2)
10-13 23:41:54.184 E/ACRA    (12126): 	at androidx.sqlite.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:1)
10-13 23:41:54.184 E/ACRA    (12126): 	at androidx.room.RoomDatabase.inTransaction(RoomDatabase.java:1)
10-13 23:41:54.184 E/ACRA    (12126): 	at androidx.room.RoomDatabase.assertNotSuspendingTransaction(RoomDatabase.java:1)
10-13 23:41:54.184 E/ACRA    (12126): 	at xyz.hisname.fireflyiii.data.local.dao.BillDataDao_Impl.getBillDueFromDate(BillDataDao_Impl.java:4)
10-13 23:41:54.184 E/ACRA    (12126): 	at xyz.hisname.fireflyiii.repository.bills.BillRepository.getBillDueFromDate(BillRepository.kt:1)
10-13 23:41:54.184 E/ACRA    (12126): 	at xyz.hisname.fireflyiii.ui.HomeViewModel$getNoOfBillsDueToday$1.invokeSuspend(HomeViewModel.kt:6)
10-13 23:41:54.184 E/ACRA    (12126): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
10-13 23:41:54.184 E/ACRA    (12126): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
10-13 23:41:54.184 E/ACRA    (12126): 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
10-13 23:41:54.184 E/ACRA    (12126): 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:11)

IS_SILENT=false
USER_CRASH_DATE=2021-10-13T23:41:54.201+02:00

```

**Comment by emansih** [comment]
ah. The fix from #183 broke it. It only affects upgrade. I will be pushing a new build ASAP
