### ISSUE TITLE
App crashes on startup

### ISSUE THREAD

**Issue by viharm** [emansih/FireflyMobile#193]
**Firefly III Server Version:**
5.6.10

**Firefly III Mobile Version:**
Photuris II 5.0.3

**Android Version:**  
11

**Device Information:**  

- BRAND: Samsung
- MODEL: Galaxy A52
--------------------------------------
App crashing at startup

## Expected Behavior
App loads after logging in.

## Current Behavior
Crashing on startup

## Steps to Reproduce
Tried to login with personal access token and with OAuth. After a few seconds screen goes black and the email client pops up with the log as an attachment.

```
REPORT_ID=49fd40ed-f699-41e5-8041-32db3059fce2
APP_VERSION_NAME=5.0.3
PHONE_MODEL=SM-A525F
BRAND=samsung
PRODUCT=a52qnsxx
ANDROID_VERSION=11
BUILD_CONFIG=
STACK_TRACE=java.util.NoSuchElementException: Char sequence is empty.
	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:246)
	at android.app.ActivityThread.main(ActivityThread.java:8653)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

LOGCAT=--------- beginning of main
01-15 16:10:11.032 E/name.fireflyii(12001): Not starting debugger since process cannot load the jdwp agent.
01-15 16:10:11.047 D/ActivityThread(12001): setConscryptValidator
01-15 16:10:11.049 D/ActivityThread(12001): setConscryptValidator - put
--------- beginning of system
01-15 16:10:11.085 D/ActivityThread(12001): handleBindApplication()++ app=xyz.hisname.fireflyiii
01-15 16:10:11.138 D/LoadedApk(12001): LoadedApk::makeApplication() appContext=android.app.ContextImpl@f36f7f6 appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii appContext.mPackageInfo=android.app.LoadedApk@838b7f7
01-15 16:10:11.138 D/NetworkSecurityConfig(12001): Using Network Security Config from resource network_security_config debugBuild: false
01-15 16:10:11.142 D/NetworkSecurityConfig(12001): Using Network Security Config from resource network_security_config debugBuild: false
01-15 16:10:11.147 D/WM-WrkMgrInitializer(12001): Initializing WorkManager with default configuration.
01-15 16:10:11.148 W/name.fireflyii(12001): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
01-15 16:10:11.148 W/name.fireflyii(12001): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
01-15 16:10:11.148 W/name.fireflyii(12001): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
01-15 16:10:11.157 I/TetheringManager(12001): registerTetheringEventCallback:xyz.hisname.fireflyiii
01-15 16:10:11.157 D/ConnectivityManager(12001): ConnectivityManager() mContext=xyz.hisname.fireflyiii.CustomApp@642e4d0 getOpPackageName()=xyz.hisname.fireflyiii getBasePackageName()=xyz.hisname.fireflyiii getPackageName()=xyz.hisname.fireflyiii
01-15 16:10:11.162 D/ActivityThread(12001): handleBindApplication() -- skipGraphicsSupport=false
01-15 16:10:11.185 I/AdrenoGLES-0(12001): QUALCOMM build                   : e1ac91e, I2b3b5fbd00
01-15 16:10:11.185 I/AdrenoGLES-0(12001): Build Date                       : 11/17/20
01-15 16:10:11.185 I/AdrenoGLES-0(12001): OpenGL ES Shader Compiler Version: EV031.32.02.06
01-15 16:10:11.185 I/AdrenoGLES-0(12001): Local Branch                     : 
01-15 16:10:11.185 I/AdrenoGLES-0(12001): Remote Branch                    : 
01-15 16:10:11.185 I/AdrenoGLES-0(12001): Remote Branch                    : 
01-15 16:10:11.185 I/AdrenoGLES-0(12001): Reconstruct Branch               : 
01-15 16:10:11.185 I/AdrenoGLES-0(12001): Build Config                     : S P 10.0.7 AArch64
01-15 16:10:11.185 I/AdrenoGLES-0(12001): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
01-15 16:10:11.203 I/AdrenoGLES-0(12001): PFP: 0x016ee190, ME: 0x00000000
01-15 16:10:11.214 I/ACRA    (12001): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
01-15 16:10:11.276 I/DecorView(12001): [INFO] isPopOver=false, config=true
01-15 16:10:11.276 I/DecorView(12001): updateCaptionType >> DecorView@547395f[], isFloating=false, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=true
01-15 16:10:11.276 D/DecorView(12001): setCaptionType = 0, this = DecorView@547395f[]
01-15 16:10:11.426 D/InputTransport(12001): Input channel constructed: 'eae11d0', fd=94
01-15 16:10:11.429 I/ViewRootImpl@e7f2ecd[HomeActivity](12001): setView = com.android.internal.policy.DecorView@547395f TM=true
01-15 16:10:11.435 D/AndroidRuntime(12001): Shutting down VM
--------- beginning of crash
01-15 16:10:11.435 E/AndroidRuntime(12001): FATAL EXCEPTION: main
01-15 16:10:11.435 E/AndroidRuntime(12001): Process: xyz.hisname.fireflyiii, PID: 12001
01-15 16:10:11.435 E/AndroidRuntime(12001): java.util.NoSuchElementException: Char sequence is empty.
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at android.os.Handler.handleCallback(Handler.java:938)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at android.os.Looper.loop(Looper.java:246)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at java.lang.reflect.Method.invoke(Native Method)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
01-15 16:10:11.435 E/AndroidRuntime(12001): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
01-15 16:10:11.435 E/ACRA    (12001): ACRA caught a NoSuchElementException for xyz.hisname.fireflyiii
01-15 16:10:11.435 E/ACRA    (12001): java.util.NoSuchElementException: Char sequence is empty.
01-15 16:10:11.435 E/ACRA    (12001): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
01-15 16:10:11.435 E/ACRA    (12001): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
01-15 16:10:11.435 E/ACRA    (12001): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
01-15 16:10:11.435 E/ACRA    (12001): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
01-15 16:10:11.435 E/ACRA    (12001): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
01-15 16:10:11.435 E/ACRA    (12001): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
01-15 16:10:11.435 E/ACRA    (12001): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
01-15 16:10:11.435 E/ACRA    (12001): 	at android.os.Handler.handleCallback(Handler.java:938)
01-15 16:10:11.435 E/ACRA    (12001): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-15 16:10:11.435 E/ACRA    (12001): 	at android.os.Looper.loop(Looper.java:246)
01-15 16:10:11.435 E/ACRA    (12001): 	at android.app.ActivityThread.main(ActivityThread.java:8653)
01-15 16:10:11.435 E/ACRA    (12001): 	at java.lang.reflect.Method.invoke(Native Method)
01-15 16:10:11.435 E/ACRA    (12001): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
01-15 16:10:11.435 E/ACRA    (12001): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)

IS_SILENT=false
USER_CRASH_DATE=2022-01-15T16:10:11.438+00:00
```

**Comment by emansih** [comment]
your issue seems similar to #192 but I am not able to replicate the issue. could you try to install this APK? https://drive.google.com/file/d/1i84Z_P1d8W9WnjOF0IilRHx_2M1pP5yt/view?usp=sharing

**Comment by viharm** [comment]
> your issue seems similar to #192 but I am not able to replicate the issue. could you try to install this APK? https://drive.google.com/file/d/1i84Z_P1d8W9WnjOF0IilRHx_2M1pP5yt/view?usp=sharing

Tried this APK. Same outcome. Debug output below...
```
REPORT_ID=550af346-003e-4bb6-b042-bf156016380b
APP_VERSION_NAME=5.0.3
PHONE_MODEL=SM-A525F
BRAND=samsung
PRODUCT=a52qnsxx
ANDROID_VERSION=12
BUILD_CONFIG=
STACK_TRACE=java.util.NoSuchElementException: Char sequence is empty.
	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8633)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

LOGCAT=--------- beginning of crash
01-30 06:43:21.883 E/AndroidRuntime( 5265): FATAL EXCEPTION: main
01-30 06:43:21.883 E/AndroidRuntime( 5265): Process: xyz.hisname.fireflyiii, PID: 5265
01-30 06:43:21.883 E/AndroidRuntime( 5265): java.util.NoSuchElementException: Char sequence is empty.
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at android.os.Handler.handleCallback(Handler.java:938)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at android.os.Looper.loopOnce(Looper.java:226)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at android.os.Looper.loop(Looper.java:313)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at java.lang.reflect.Method.invoke(Native Method)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
01-30 06:43:21.883 E/AndroidRuntime( 5265): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
01-30 07:38:56.434 E/AndroidRuntime(15400): FATAL EXCEPTION: main
01-30 07:38:56.434 E/AndroidRuntime(15400): Process: xyz.hisname.fireflyiii, PID: 15400
01-30 07:38:56.434 E/AndroidRuntime(15400): java.util.NoSuchElementException: Char sequence is empty.
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at android.os.Handler.handleCallback(Handler.java:938)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at android.os.Looper.loopOnce(Looper.java:226)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at android.os.Looper.loop(Looper.java:313)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at java.lang.reflect.Method.invoke(Native Method)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
01-30 07:38:56.434 E/AndroidRuntime(15400): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
--------- beginning of main
01-31 05:29:38.731 E/name.fireflyii(14812): Not starting debugger since process cannot load the jdwp agent.
01-31 05:29:38.736 E/USNET   (14812): USNET: appName: xyz.hisname.fireflyiii
01-31 05:29:38.739 D/ProcessState(14812): Binder ioctl to enable oneway spam detection failed: Invalid argument
01-31 05:29:38.745 D/ActivityThread(14812): setConscryptValidator
01-31 05:29:38.745 D/ActivityThread(14812): setConscryptValidator - put
--------- beginning of system
01-31 05:29:38.780 D/ActivityThread(14812): handleBindApplication()++ app=xyz.hisname.fireflyiii
01-31 05:29:38.781 D/CompatibilityChangeReporter(14812): Compat change id reported: 171979766; UID 10406; state: DISABLED
01-31 05:29:38.827 V/GraphicsEnvironment(14812): ANGLE Developer option for 'xyz.hisname.fireflyiii' set to: 'default'
01-31 05:29:38.827 V/GraphicsEnvironment(14812): Neither updatable production driver nor prerelease driver is supported.
01-31 05:29:38.829 D/LoadedApk(14812): LoadedApk::makeApplication() appContext.mOpPackageName=xyz.hisname.fireflyiii appContext.mBasePackageName=xyz.hisname.fireflyiii
01-31 05:29:38.830 D/NetworkSecurityConfig(14812): Using Network Security Config from resource network_security_config debugBuild: false
01-31 05:29:38.833 D/NetworkSecurityConfig(14812): Using Network Security Config from resource network_security_config debugBuild: false
01-31 05:29:38.837 D/WM-WrkMgrInitializer(14812): Initializing WorkManager with default configuration.
01-31 05:29:38.838 W/name.fireflyii(14812): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (max-target-o, reflection, denied)
01-31 05:29:38.838 W/name.fireflyii(14812): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (max-target-o, reflection, denied)
01-31 05:29:38.838 W/name.fireflyii(14812): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (max-target-o, reflection, denied)
01-31 05:29:38.851 D/ActivityThread(14812): handleBindApplication() --
01-31 05:29:38.874 D/CompatibilityChangeReporter(14812): Compat change id reported: 160794467; UID 10406; state: DISABLED
01-31 05:29:38.944 I/AdrenoGLES-0(14812): QUALCOMM build                   : e1ac91e, I2b3b5fbd00
01-31 05:29:38.944 I/AdrenoGLES-0(14812): Build Date                       : 11/17/20
01-31 05:29:38.944 I/AdrenoGLES-0(14812): OpenGL ES Shader Compiler Version: EV031.32.02.06
01-31 05:29:38.944 I/AdrenoGLES-0(14812): Local Branch                     : 
01-31 05:29:38.944 I/AdrenoGLES-0(14812): Remote Branch                    : 
01-31 05:29:38.944 I/AdrenoGLES-0(14812): Remote Branch                    : 
01-31 05:29:38.944 I/AdrenoGLES-0(14812): Reconstruct Branch               : 
01-31 05:29:38.944 I/AdrenoGLES-0(14812): Build Config                     : S P 10.0.7 AArch64
01-31 05:29:38.944 I/AdrenoGLES-0(14812): Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
01-31 05:29:38.949 I/AdrenoGLES-0(14812): PFP: 0x016ee190, ME: 0x00000000
01-31 05:29:38.960 I/ACRA    (14812): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
01-31 05:29:38.996 I/DecorView(14812): [INFO] isPopOver=false, config=true
01-31 05:29:38.996 I/DecorView(14812): updateCaptionType >> DecorView@e3916b2[], isFloating=false, isApplication=true, hasWindowControllerCallback=true, hasWindowDecorCaption=false
01-31 05:29:38.996 D/DecorView(14812): setCaptionType = 0, this = DecorView@e3916b2[]
01-31 05:29:38.997 I/DecorView(14812): getCurrentDensityDpi: from real metrics. densityDpi=420 msg=resources_loaded
01-31 05:29:39.045 D/CompatibilityChangeReporter(14812): Compat change id reported: 171228096; UID 10406; state: ENABLED
01-31 05:29:39.118 I/MSHandlerLifeCycle(14812): isMultiSplitHandlerRequested: ignored. pkg=xyz.hisname.fireflyiii parent=null callers=com.android.internal.policy.DecorView.setVisibility:4224 android.app.ActivityThread.handleResumeActivity:5294 android.app.servertransaction.ResumeActivityItem.execute:54 android.app.servertransaction.ActivityTransactionItem.execute:45 android.app.servertransaction.TransactionExecutor.executeLifecycleState:176 
01-31 05:29:39.118 I/MSHandlerLifeCycle(14812): removeMultiSplitHandler: no exist. decor=DecorView@e3916b2[]
01-31 05:29:39.140 I/ViewRootImpl@c187c62[HomeActivity](14812): setView = com.android.internal.policy.DecorView@e3916b2 TM=true
01-31 05:29:39.141 I/MSHandlerLifeCycle(14812): isMultiSplitHandlerRequested: windowingMode=1 isFullscreen=true isPopOver=false isHidden=false skipActivityType=false isHandlerType=true this: DecorView@e3916b2[HomeActivity]
01-31 05:29:39.141 I/MSHandlerLifeCycle(14812): removeMultiSplitHandler: no exist. decor=DecorView@e3916b2[HomeActivity]
01-31 05:29:39.144 I/ActivityThread(14812): Schedule relaunch activity: xyz.hisname.fireflyiii.ui.HomeActivity
01-31 05:29:39.147 D/AndroidRuntime(14812): Shutting down VM
01-31 05:29:39.148 E/AndroidRuntime(14812): FATAL EXCEPTION: main
01-31 05:29:39.148 E/AndroidRuntime(14812): Process: xyz.hisname.fireflyiii, PID: 14812
01-31 05:29:39.148 E/AndroidRuntime(14812): java.util.NoSuchElementException: Char sequence is empty.
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at android.os.Handler.handleCallback(Handler.java:938)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at android.os.Looper.loopOnce(Looper.java:226)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at android.os.Looper.loop(Looper.java:313)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at java.lang.reflect.Method.invoke(Native Method)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
01-31 05:29:39.148 E/AndroidRuntime(14812): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)
01-31 05:29:39.149 E/ACRA    (14812): ACRA caught a NoSuchElementException for xyz.hisname.fireflyiii
01-31 05:29:39.149 E/ACRA    (14812): java.util.NoSuchElementException: Char sequence is empty.
01-31 05:29:39.149 E/ACRA    (14812): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
01-31 05:29:39.149 E/ACRA    (14812): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
01-31 05:29:39.149 E/ACRA    (14812): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
01-31 05:29:39.149 E/ACRA    (14812): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
01-31 05:29:39.149 E/ACRA    (14812): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
01-31 05:29:39.149 E/ACRA    (14812): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
01-31 05:29:39.149 E/ACRA    (14812): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
01-31 05:29:39.149 E/ACRA    (14812): 	at android.os.Handler.handleCallback(Handler.java:938)
01-31 05:29:39.149 E/ACRA    (14812): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-31 05:29:39.149 E/ACRA    (14812): 	at android.os.Looper.loopOnce(Looper.java:226)
01-31 05:29:39.149 E/ACRA    (14812): 	at android.os.Looper.loop(Looper.java:313)
01-31 05:29:39.149 E/ACRA    (14812): 	at android.app.ActivityThread.main(ActivityThread.java:8633)
01-31 05:29:39.149 E/ACRA    (14812): 	at java.lang.reflect.Method.invoke(Native Method)
01-31 05:29:39.149 E/ACRA    (14812): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
01-31 05:29:39.149 E/ACRA    (14812): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)

IS_SILENT=false
USER_CRASH_DATE=2022-01-31T05:29:39.153+00:00
```

**Comment by emansih** [comment]
@viharm your crash log says you are running 5.0.3. That is _really_ old.... The latest is 5.0.6

**Comment by viharm** [comment]
> @viharm your crash log says you are running 5.0.3. That is _really_ old.... The latest is 5.0.6

I don't know. I just installed the APK you sent ([here](https://github.com/emansih/FireflyMobile/issues/193#issuecomment-1013963368))

**Comment by emansih** [comment]
Yeah... That was quite some time ago.... Get the new version from fdroid or Google play store
