### ISSUE TITLE
App crashing on Huawei BLA-L29 

### ISSUE THREAD

**Issue by Biskit1943** [emansih/FireflyMobile#207]
Since a few weeks now the app is crashing on startup. I now even tried to opt into the beta program but that didn't fixed the issue.
Here is the report generated by the app:
```
REPORT_ID=b8ac4f25-3998-4b17-972f-6a5a38636ad2
APP_VERSION_NAME=5.0.6
PHONE_MODEL=BLA-L29
BRAND=HUAWEI
PRODUCT=BLA-L29
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:213)
    at android.app.ActivityThread.main(ActivityThread.java:8178)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
    at android.os.Parcel.createException(Parcel.java:2071)
    at android.os.Parcel.readException(Parcel.java:2039)
    at android.os.Parcel.readException(Parcel.java:1987)
    at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1371)
    at android.accounts.AccountManager.getUserData(AccountManager.java:514)
    at xyz.hisname.fireflyiii.data.local.account.OldAuthenticatorManager.getUserEmail(OldAuthenticatorManager.kt:1)
    at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:27)
    at android.app.Activity.performCreate(Activity.java:8086)
    at android.app.Activity.performCreate(Activity.java:8074)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
    ... 11 more
Caused by: android.os.RemoteException: Remote stack trace:
    at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1592)
    at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:468)
    at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1083)
    at android.os.Binder.execTransactInternal(Binder.java:1028)
    at android.os.Binder.execTransact(Binder.java:1001)


LOGCAT=--------- beginning of system
02-13 10:31:21.765 D/ActivityThread(22629): Attach thread to application
02-13 10:31:21.906 V/ActivityThread(22629): callActivityOnCreate
--------- beginning of crash
02-13 10:31:21.973 E/AndroidRuntime(22629): FATAL EXCEPTION: main
02-13 10:31:21.973 E/AndroidRuntime(22629): Process: xyz.hisname.fireflyiii, PID: 22629
02-13 10:31:21.973 E/AndroidRuntime(22629): java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.os.Handler.dispatchMessage(Handler.java:107)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.os.Looper.loop(Looper.java:213)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.ActivityThread.main(ActivityThread.java:8178)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at java.lang.reflect.Method.invoke(Native Method)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
02-13 10:31:21.973 E/AndroidRuntime(22629): Caused by: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.os.Parcel.createException(Parcel.java:2071)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.os.Parcel.readException(Parcel.java:2039)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.os.Parcel.readException(Parcel.java:1987)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1371)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.accounts.AccountManager.getUserData(AccountManager.java:514)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at xyz.hisname.fireflyiii.data.local.account.OldAuthenticatorManager.getUserEmail(OldAuthenticatorManager.kt:1)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:27)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.Activity.performCreate(Activity.java:8086)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.Activity.performCreate(Activity.java:8074)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
02-13 10:31:21.973 E/AndroidRuntime(22629):     ... 11 more
02-13 10:31:21.973 E/AndroidRuntime(22629): Caused by: android.os.RemoteException: Remote stack trace:
02-13 10:31:21.973 E/AndroidRuntime(22629):     at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1592)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:468)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1083)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.os.Binder.execTransactInternal(Binder.java:1028)
02-13 10:31:21.973 E/AndroidRuntime(22629):     at android.os.Binder.execTransact(Binder.java:1001)
02-13 10:31:21.973 E/AndroidRuntime(22629): 
02-13 10:31:44.460 D/ActivityThread(22806): Attach thread to application
02-13 10:31:44.562 V/ActivityThread(22806): callActivityOnCreate
02-13 10:31:44.617 E/AndroidRuntime(22806): FATAL EXCEPTION: main
02-13 10:31:44.617 E/AndroidRuntime(22806): Process: xyz.hisname.fireflyiii, PID: 22806
02-13 10:31:44.617 E/AndroidRuntime(22806): java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.os.Handler.dispatchMessage(Handler.java:107)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.os.Looper.loop(Looper.java:213)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.ActivityThread.main(ActivityThread.java:8178)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at java.lang.reflect.Method.invoke(Native Method)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
02-13 10:31:44.617 E/AndroidRuntime(22806): Caused by: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.os.Parcel.createException(Parcel.java:2071)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.os.Parcel.readException(Parcel.java:2039)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.os.Parcel.readException(Parcel.java:1987)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1371)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.accounts.AccountManager.getUserData(AccountManager.java:514)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at xyz.hisname.fireflyiii.data.local.account.OldAuthenticatorManager.getUserEmail(OldAuthenticatorManager.kt:1)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:27)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.Activity.performCreate(Activity.java:8086)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.Activity.performCreate(Activity.java:8074)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
02-13 10:31:44.617 E/AndroidRuntime(22806):     ... 11 more
02-13 10:31:44.617 E/AndroidRuntime(22806): Caused by: android.os.RemoteException: Remote stack trace:
02-13 10:31:44.617 E/AndroidRuntime(22806):     at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1592)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:468)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1083)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.os.Binder.execTransactInternal(Binder.java:1028)
02-13 10:31:44.617 E/AndroidRuntime(22806):     at android.os.Binder.execTransact(Binder.java:1001)
02-13 10:31:44.617 E/AndroidRuntime(22806): 
--------- beginning of main
02-13 10:31:49.371 I/fireflyiii:acr(23012): Reinit property: dalvik.vm.checkjni= false
02-13 10:31:49.372 E/fireflyiii:acr(23012): Not starting debugger since process cannot load the jdwp agent.
02-13 10:31:49.384 E/libc    (23012): Access denied finding property "runtime.mmitest.isrunning"
02-13 10:31:49.387 D/ActivityThread(23012): Attach thread to application
02-13 10:31:49.429 W/fireflyiii:acr(23012): JIT profile information will not be recorded: profile file does not exits.
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::Init
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::StartWatch
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/xyz.hisname.fireflyiii
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::Run
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::Reading
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::CheckNotifyEvent
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/fireflyiii:acr(23012): QarthPatchMonintor::CheckNotifyEvent before read
02-13 10:31:49.433 I/fireflyiii:acr(23012): 
02-13 10:31:49.433 I/HwApiCacheMangerEx(23012): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10308#256
02-13 10:31:49.434 I/HwApiCacheMangerEx(23012): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10308#0
02-13 10:31:49.435 I/AwareBitmapCacher(23012): init processName:xyz.hisname.fireflyiii:acra pid=23012 uid=10308
02-13 10:31:49.456 D/HwFrameworkSecurityPartsFactory(23012): HwFrameworkSecurityPartsFactory in.
02-13 10:31:49.456 I/HwFrameworkSecurityPartsFactory(23012): add HwFrameworkSecurityPartsFactory to memory.
02-13 10:31:54.442 D/AwareBitmapCacher(23012): handleInit disable xyz.hisname.fireflyiii:acra
02-13 10:31:59.984 I/name.fireflyii(23292): Reinit property: dalvik.vm.checkjni= false
02-13 10:31:59.986 E/name.fireflyii(23292): Not starting debugger since process cannot load the jdwp agent.
02-13 10:31:59.986 W/re-initialized>(23292): type=1400 audit(0.0:12954): avc: denied { read } for pid=23292 name="u:object_r:mmi_prop:s0" dev="tmpfs" ino=11821 scontext=u:r:untrusted_app:s0:c52,c257,c512,c768 tcontext=u:object_r:mmi_prop:s0 tclass=file permissive=0
02-13 10:31:59.993 E/libc    (23292): Access denied finding property "runtime.mmitest.isrunning"
02-13 10:31:59.995 D/ActivityThread(23292): Attach thread to application
02-13 10:32:00.013 W/name.fireflyii(23292): JIT profile information will not be recorded: profile file does not exits.
02-13 10:32:00.017 I/name.fireflyii(23292): QarthPatchMonintor::Init
02-13 10:32:00.017 I/name.fireflyii(23292): 
02-13 10:32:00.017 I/name.fireflyii(23292): QarthPatchMonintor::StartWatch
02-13 10:32:00.017 I/name.fireflyii(23292): 
02-13 10:32:00.017 I/name.fireflyii(23292): QarthPatchMonintor::WatchPackage: /data/hotpatch/fwkhotpatch/
02-13 10:32:00.017 I/name.fireflyii(23292): 
02-13 10:32:00.018 I/name.fireflyii(23292): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/xyz.hisname.fireflyiii
02-13 10:32:00.018 I/name.fireflyii(23292): 
02-13 10:32:00.018 I/name.fireflyii(23292): QarthPatchMonintor::CheckAndWatchPatch: /data/hotpatch/fwkhotpatch/all
02-13 10:32:00.018 I/name.fireflyii(23292): 
02-13 10:32:00.018 I/name.fireflyii(23292): QarthPatchMonintor::Run
02-13 10:32:00.018 I/name.fireflyii(23292): 
02-13 10:32:00.018 I/name.fireflyii(23292): QarthPatchMonintor::Reading
02-13 10:32:00.018 I/name.fireflyii(23292): 
02-13 10:32:00.018 I/name.fireflyii(23292): QarthPatchMonintor::CheckNotifyEvent
02-13 10:32:00.018 I/name.fireflyii(23292): 
02-13 10:32:00.018 I/name.fireflyii(23292): QarthPatchMonintor::CheckNotifyEvent before read
02-13 10:32:00.018 I/name.fireflyii(23292): 
02-13 10:32:00.019 I/HwApiCacheMangerEx(23292): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10308#256
02-13 10:32:00.019 I/HwApiCacheMangerEx(23292): apicache path=/storage/emulated/0 state=mounted key=xyz.hisname.fireflyiii#10308#0
02-13 10:32:00.021 I/AwareBitmapCacher(23292): init processName:xyz.hisname.fireflyiii pid=23292 uid=10308
02-13 10:32:00.023 E/AwareLog(23292): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@9b982cb
02-13 10:32:00.023 E/AwareLog(23292): AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@416d9c1
02-13 10:32:00.024 D/WM-WrkMgrInitializer(23292): Initializing WorkManager with default configuration.
02-13 10:32:00.027 W/name.fireflyii(23292): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
02-13 10:32:00.027 W/name.fireflyii(23292): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
02-13 10:32:00.027 W/name.fireflyii(23292): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
02-13 10:32:00.083 I/ACRA    (23292): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
02-13 10:32:00.105 V/ActivityThread(23292): callActivityOnCreate
02-13 10:32:00.115 V/HwWidgetFactory(23292): : successes to get AllImpl object and return....
02-13 10:32:00.115 I/OverScrollerOptimization(23292): start init SmartSlideOverScroller and get the overscroller config
02-13 10:32:00.115 I/OverScrollerOptimization(23292): get the overscroller config
02-13 10:32:00.118 W/name.fireflyii(23292): Accessing hidden method Landroid/view/Window;->getInsetsController()Landroid/view/WindowInsetsController; (blacklist, linking, denied)
02-13 10:32:00.154 I/BlockMonitor(23292): dispatchingThrewException In MainThread
02-13 10:32:00.154 D/AndroidRuntime(23292): Shutting down VM
02-13 10:32:00.154 I/QarthLog(23292): [PatchStore] createDisableExceptionQarthFile
02-13 10:32:00.154 I/QarthLog(23292): [PatchStore] create disable file for xyz.hisname.fireflyiii uid is 10308
02-13 10:32:00.155 E/AndroidRuntime(23292): FATAL EXCEPTION: main
02-13 10:32:00.155 E/AndroidRuntime(23292): Process: xyz.hisname.fireflyiii, PID: 23292
02-13 10:32:00.155 E/AndroidRuntime(23292): java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.os.Handler.dispatchMessage(Handler.java:107)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.os.Looper.loop(Looper.java:213)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.ActivityThread.main(ActivityThread.java:8178)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at java.lang.reflect.Method.invoke(Native Method)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
02-13 10:32:00.155 E/AndroidRuntime(23292): Caused by: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.os.Parcel.createException(Parcel.java:2071)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.os.Parcel.readException(Parcel.java:2039)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.os.Parcel.readException(Parcel.java:1987)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1371)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.accounts.AccountManager.getUserData(AccountManager.java:514)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at xyz.hisname.fireflyiii.data.local.account.OldAuthenticatorManager.getUserEmail(OldAuthenticatorManager.kt:1)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:27)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.Activity.performCreate(Activity.java:8086)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.Activity.performCreate(Activity.java:8074)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
02-13 10:32:00.155 E/AndroidRuntime(23292):     ... 11 more
02-13 10:32:00.155 E/AndroidRuntime(23292): Caused by: android.os.RemoteException: Remote stack trace:
02-13 10:32:00.155 E/AndroidRuntime(23292):     at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1592)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:468)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1083)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.os.Binder.execTransactInternal(Binder.java:1028)
02-13 10:32:00.155 E/AndroidRuntime(23292):     at android.os.Binder.execTransact(Binder.java:1001)
02-13 10:32:00.155 E/AndroidRuntime(23292): 
02-13 10:32:00.156 E/ACRA    (23292): ACRA caught a RuntimeException for xyz.hisname.fireflyiii
02-13 10:32:00.156 E/ACRA    (23292): java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
02-13 10:32:00.156 E/ACRA    (23292):     at android.os.Handler.dispatchMessage(Handler.java:107)
02-13 10:32:00.156 E/ACRA    (23292):     at android.os.Looper.loop(Looper.java:213)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.ActivityThread.main(ActivityThread.java:8178)
02-13 10:32:00.156 E/ACRA    (23292):     at java.lang.reflect.Method.invoke(Native Method)
02-13 10:32:00.156 E/ACRA    (23292):     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
02-13 10:32:00.156 E/ACRA    (23292):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
02-13 10:32:00.156 E/ACRA    (23292): Caused by: java.lang.SecurityException: uid 10308 cannot get user data for accounts of type: OAUTH
02-13 10:32:00.156 E/ACRA    (23292):     at android.os.Parcel.createException(Parcel.java:2071)
02-13 10:32:00.156 E/ACRA    (23292):     at android.os.Parcel.readException(Parcel.java:2039)
02-13 10:32:00.156 E/ACRA    (23292):     at android.os.Parcel.readException(Parcel.java:1987)
02-13 10:32:00.156 E/ACRA    (23292):     at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:1371)
02-13 10:32:00.156 E/ACRA    (23292):     at android.accounts.AccountManager.getUserData(AccountManager.java:514)
02-13 10:32:00.156 E/ACRA    (23292):     at xyz.hisname.fireflyiii.data.local.account.OldAuthenticatorManager.getUserEmail(OldAuthenticatorManager.kt:1)
02-13 10:32:00.156 E/ACRA    (23292):     at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:27)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.Activity.performCreate(Activity.java:8086)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.Activity.performCreate(Activity.java:8074)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
02-13 10:32:00.156 E/ACRA    (23292):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
02-13 10:32:00.156 E/ACRA    (23292):     ... 11 more
02-13 10:32:00.156 E/ACRA    (23292): Caused by: android.os.RemoteException: Remote stack trace:
02-13 10:32:00.156 E/ACRA    (23292):     at com.android.server.accounts.AccountManagerService.getUserData(AccountManagerService.java:1592)
02-13 10:32:00.156 E/ACRA    (23292):     at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:468)
02-13 10:32:00.156 E/ACRA    (23292):     at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1083)
02-13 10:32:00.156 E/ACRA    (23292):     at android.os.Binder.execTransactInternal(Binder.java:1028)
02-13 10:32:00.156 E/ACRA    (23292):     at android.os.Binder.execTransact(Binder.java:1001)
02-13 10:32:00.156 E/ACRA    (23292): 

IS_SILENT=false
USER_CRASH_DATE=2022-02-13T10:32:00.157+01:00

```

Thanks for your work.

**Comment by emansih** [comment]
What happens
 
1. When you clear app data.
2. Go to Android Settings -> Accounts -> Delete Photuris III account

Will that solve your issue?

**Comment by emansih** [comment]
What happens if you uninstall and install again?

**Comment by Biskit1943** [comment]
Account wasn't there. Reinstall did help. 👍

**Comment by Biskit1943** [comment]
@teldosas Youre right, after removing all accounts and making sure the login does not fail it works (for now).
Thangs for the notice :)
