### ISSUE TITLE
App crashes after succesfully signing in with OAuth

### ISSUE THREAD

**Issue by JiriS97** [emansih/FireflyMobile#241]
**Firefly III Server Version:**
5.7.18

**Firefly III Mobile Version:**
5.0.3

**Android Version:**  
10

**Device Information:**  

- BRAND: OnePlus 
- MODEL: 5
--------------------------------------
App crashes after signing in with OAuth. 
 
## Expected Behavior
To sign in 

## Current Behavior
After entering all the details and authorizing the app on the web the redirect works fine, app says Welcome and then crashes when trying to create new record or even while reopening it.

## Steps to Reproduce
Create OAuth client, fill in all the details on OAuth page of the app and try to authorize the app. Then create a record.

java.util.NoSuchElementException: Char sequence is empty.
	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7697)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

LOGCAT=--------- beginning of main
02-04 12:51:13.721 I/name.fireflyii(26376): [GL_OOM] ClampGrowthLimit 268435456
02-04 12:51:13.733 D/WM-WrkMgrInitializer(26376): Initializing WorkManager with default configuration.
02-04 12:51:13.741 W/name.fireflyii(26376): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
02-04 12:51:13.743 W/name.fireflyii(26376): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
02-04 12:51:13.744 W/name.fireflyii(26376): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
02-04 12:51:13.753 V/Font    (26376): Change font:2
02-04 12:51:13.754 V/Font    (26376): Default family:android.graphics.Typeface@3b7b816
02-04 12:51:13.806 I/ACRA    (26376): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
02-04 12:51:13.848 V/FlingOptimizerScroller(26376): FlingOptimizerOverScroller Init
02-04 12:51:13.850 W/name.fireflyii(26376): Accessing hidden method Landroid/view/Window;->getInsetsController()Landroid/view/WindowInsetsController; (blacklist, linking, denied)
02-04 12:51:13.892 W/ActivityThread(26376): handleWindowVisibility: no activity for token android.os.BinderProxy@58f01c
02-04 12:51:13.969 V/ViewRootImpl(26376): The specified message queue synchronization  barrier token has not been posted or has already been removed
02-04 12:51:13.982 I/AdrenoGLES(26376): QUALCOMM build                   : 6209c5d, Ifdcc64d6e8
02-04 12:51:13.982 I/AdrenoGLES(26376): Build Date                       : 12/12/19
02-04 12:51:13.982 I/AdrenoGLES(26376): OpenGL ES Shader Compiler Version: EV031.27.05.03
02-04 12:51:13.982 I/AdrenoGLES(26376): Local Branch                     : mybranchea1c9b4a-9e05-f149-a3b2-1458d0b52ae8
02-04 12:51:13.982 I/AdrenoGLES(26376): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r85-rel
02-04 12:51:13.982 I/AdrenoGLES(26376): Remote Branch                    : NONE
02-04 12:51:13.982 I/AdrenoGLES(26376): Reconstruct Branch               : NOTHING
02-04 12:51:13.983 I/AdrenoGLES(26376): Build Config                     : C O 9.0.3 AArch64
02-04 12:51:13.986 D/ViewRootImpl[AuthActivity](26376): windowFocusChanged hasFocus=true inTouchMode=true
02-04 12:51:13.999 I/AdrenoGLES(26376): PFP: 0x005ff112, ME: 0x005ff066
02-04 12:51:14.018 W/Gralloc3(26376): mapper 3.x is not supported
02-04 12:51:14.135 D/OnePlusJankManager(26376):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.AuthActivity--- jank level = 1
02-04 12:51:14.145 W/ActivityThread(26376): Activity state must be in [ON_RESUME..ON_STOP] in order to be relaunched,current state is 1
02-04 12:51:14.154 D/ViewRootImpl[AuthActivity](26376): windowFocusChanged hasFocus=false inTouchMode=true
02-04 12:51:14.187 V/ViewRootImpl(26376): The specified message queue synchronization  barrier token has not been posted or has already been removed
02-04 12:51:14.196 D/ViewRootImpl[AuthActivity](26376): windowFocusChanged hasFocus=true inTouchMode=true
02-04 12:51:14.203 W/Choreographer(26376): Already have a pending vsync event.  There should only be one at a time.
02-04 12:51:16.828 I/Surface (26376): opservice is null false
02-04 12:51:16.884 I/AssistStructure(26376): Flattened final assist data: 3816 bytes, containing 1 windows, 27 views
02-04 12:51:19.233 I/AssistStructure(26376): Flattened final assist data: 3824 bytes, containing 1 windows, 27 views
02-04 12:51:19.296 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:19.308 I/chatty  (26376): uid=10281(xyz.hisname.fireflyiii) identical 4 lines
02-04 12:51:19.308 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:22.566 I/AssistStructure(26376): Flattened final assist data: 3824 bytes, containing 1 windows, 27 views
02-04 12:51:22.587 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:22.588 I/chatty  (26376): uid=10281(xyz.hisname.fireflyiii) identical 2 lines
02-04 12:51:22.589 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:24.601 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:24.601 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:24.609 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:24.609 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:25.417 I/AssistStructure(26376): Flattened final assist data: 3936 bytes, containing 1 windows, 27 views
02-04 12:51:25.428 V/ViewRootImpl(26376): The specified message queue synchronization  barrier token has not been posted or has already been removed
02-04 12:51:27.913 I/AssistStructure(26376): Flattened final assist data: 3928 bytes, containing 1 windows, 27 views
02-04 12:51:27.924 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:27.926 I/chatty  (26376): uid=10281(xyz.hisname.fireflyiii) identical 2 lines
02-04 12:51:27.926 E/SpannableStringBuilder(26376): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 12:51:43.424 D/OnePlusJankManager(26376):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.AuthActivity--- jank level = 2
02-04 12:51:43.459 D/ViewRootImpl[AuthActivity](26376): windowFocusChanged hasFocus=false inTouchMode=true
02-04 12:51:52.644 D/ViewRootImpl[AuthActivity](26376): windowFocusChanged hasFocus=true inTouchMode=true
02-04 12:51:52.704 I/AssistStructure(26376): Flattened final assist data: 4088 bytes, containing 1 windows, 27 views
02-04 12:51:53.681 V/ViewRootImpl(26376): The specified message queue synchronization  barrier token has not been posted or has already been removed
02-04 12:51:53.718 I/AssistStructure(26376): Flattened final assist data: 4200 bytes, containing 2 windows, 28 views
02-04 12:51:56.710 I/Choreographer(26376): Skipped 40 frames!  The application may be doing too much work on its main thread.
02-04 12:51:56.710 D/OnePlusJankManager(26376):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.AuthActivity--- jank level = 3
02-04 12:51:56.733 D/ViewRootImpl[AuthActivity](26376): windowFocusChanged hasFocus=false inTouchMode=true
02-04 12:51:57.365 I/Choreographer(26376): Skipped 38 frames!  The application may be doing too much work on its main thread.
02-04 12:51:57.381 D/OnePlusJankManager(26376):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.AuthActivity--- jank level = 3
02-04 12:52:00.379 D/ViewRootImpl[AuthActivity](26376): windowFocusChanged hasFocus=true inTouchMode=true
02-04 12:52:00.567 D/NetworkSecurityConfig(26376): Using Network Security Config from resource network_security_config debugBuild: false
02-04 12:52:01.264 V/ViewRootImpl(26376): The specified message queue synchronization  barrier token has not been posted or has already been removed
02-04 12:52:01.572 W/ActivityThread(26376): handleWindowVisibility: no activity for token android.os.BinderProxy@ae400b7
02-04 12:52:01.586 D/ViewRootImpl[AuthActivity](26376): windowFocusChanged hasFocus=false inTouchMode=true
02-04 12:52:01.858 I/name.fireflyii(26376): Background young concurrent copying GC freed 53942(2495KB) AllocSpace objects, 6(312KB) LOS objects, 11% free, 13MB/15MB, paused 265us total 148.549ms
02-04 12:52:01.891 V/ViewRootImpl(26376): The specified message queue synchronization  barrier token has not been posted or has already been removed
02-04 12:52:01.949 D/ViewRootImpl[HomeActivity](26376): windowFocusChanged hasFocus=true inTouchMode=true
02-04 12:52:01.952 W/RecyclerView(26376): No adapter attached; skipping layout
02-04 12:52:02.128 W/Choreographer(26376): Already have a pending vsync event.  There should only be one at a time.
02-04 12:52:02.137 I/name.fireflyii(26376): Background concurrent copying GC freed 24173(1229KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 13MB/27MB, paused 56us total 102.739ms
02-04 12:52:02.138 D/OnePlusJankManager(26376):  Chor uploadMDM JANK_TYPE_ONCE mViewTitle = xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity--- jank level = 1
02-04 12:52:02.146 D/AndroidRuntime(26376): Shutting down VM
--------- beginning of crash
02-04 12:52:02.147 E/AndroidRuntime(26376): FATAL EXCEPTION: main
02-04 12:52:02.147 E/AndroidRuntime(26376): Process: xyz.hisname.fireflyiii, PID: 26376
02-04 12:52:02.147 E/AndroidRuntime(26376): java.util.NoSuchElementException: Char sequence is empty.
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at android.os.Handler.handleCallback(Handler.java:883)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at android.os.Looper.loop(Looper.java:214)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at java.lang.reflect.Method.invoke(Native Method)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-04 12:52:02.147 E/AndroidRuntime(26376): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
02-04 12:52:02.147 E/ACRA    (26376): ACRA caught a NoSuchElementException for xyz.hisname.fireflyiii
02-04 12:52:02.147 E/ACRA    (26376): java.util.NoSuchElementException: Char sequence is empty.
02-04 12:52:02.147 E/ACRA    (26376): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
02-04 12:52:02.147 E/ACRA    (26376): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
02-04 12:52:02.147 E/ACRA    (26376): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
02-04 12:52:02.147 E/ACRA    (26376): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
02-04 12:52:02.147 E/ACRA    (26376): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
02-04 12:52:02.147 E/ACRA    (26376): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
02-04 12:52:02.147 E/ACRA    (26376): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
02-04 12:52:02.147 E/ACRA    (26376): 	at android.os.Handler.handleCallback(Handler.java:883)
02-04 12:52:02.147 E/ACRA    (26376): 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-04 12:52:02.147 E/ACRA    (26376): 	at android.os.Looper.loop(Looper.java:214)
02-04 12:52:02.147 E/ACRA    (26376): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
02-04 12:52:02.147 E/ACRA    (26376): 	at java.lang.reflect.Method.invoke(Native Method)
02-04 12:52:02.147 E/ACRA    (26376): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-04 12:52:02.147 E/ACRA    (26376): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
02-04 12:52:02.295 D/ViewRootImpl[HomeActivity](26376): windowFocusChanged hasFocus=false inTouchMode=true
02-04 12:52:02.316 I/ACRA    (26376): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2023-02-04T12:52:02.153+01:00.stacktrace
02-04 12:52:02.329 W/Bundle  (26376): Key android.intent.extra.TEXT expected ArrayList<CharSequence> but value was a java.lang.String.  The default value <null> was returned.
02-04 12:52:02.330 W/Bundle  (26376): Attempt to cast generated internal exception:
02-04 12:52:02.330 W/Bundle  (26376): java.lang.ClassCastException: java.lang.String cannot be cast to java.util.ArrayList
02-04 12:52:02.330 W/Bundle  (26376): 	at android.os.BaseBundle.getCharSequenceArrayList(BaseBundle.java:1312)
02-04 12:52:02.330 W/Bundle  (26376): 	at android.os.Bundle.getCharSequenceArrayList(Bundle.java:1095)
02-04 12:52:02.330 W/Bundle  (26376): 	at android.content.Intent.getCharSequenceArrayListExtra(Intent.java:8028)
02-04 12:52:02.330 W/Bundle  (26376): 	at android.content.Intent.migrateExtraStreamToClipData(Intent.java:10975)
02-04 12:52:02.330 W/Bundle  (26376): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1895)
02-04 12:52:02.330 W/Bundle  (26376): 	at android.app.ContextImpl.startActivity(ContextImpl.java:975)
02-04 12:52:02.330 W/Bundle  (26376): 	at android.app.ContextImpl.startActivity(ContextImpl.java:940)
02-04 12:52:02.330 W/Bundle  (26376): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:383)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.sender.EmailIntentSender.send(EmailIntentSender.kt:30)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.sender.ReportSender$-CC.$default$send(ReportSender.kt:1)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.sender.EmailIntentSender.send(Unknown Source:0)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.kt:6)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.sender.ReportDistributor.distribute(ReportDistributor.kt:5)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.sender.SendingConductor.sendReports(SendingConductor.kt:12)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.scheduler.DefaultSenderScheduler.scheduleReportSending(DefaultSenderScheduler.kt:48)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.scheduler.SchedulerStarter.scheduleReports(SchedulerStarter.kt:7)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.builder.ReportExecutor.sendReport(ReportExecutor.kt:2)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.builder.ReportExecutor.execute(ReportExecutor.kt:37)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.builder.ReportBuilder.build(ReportBuilder.kt:3)
02-04 12:52:02.330 W/Bundle  (26376): 	at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.kt:11)
02-04 12:52:02.330 W/Bundle  (26376): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
02-04 12:52:02.330 W/Bundle  (26376): 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
02-04 12:52:02.330 W/Bundle  (26376): 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2187)
02-04 12:52:02.345 I/Process (26376): Sending signal. PID: 26376 SIG: 9
02-04 12:52:12.660 E/name.fireflyii(30061): Unknown bits set in runtime_flags: 0x20000
02-04 12:52:12.673 E/name.fireflyii(30061): Not starting debugger since process cannot load the jdwp agent.
02-04 12:52:12.950 W/name.fireflyii(30061): JIT profile information will not be recorded: profile file does not exits.
02-04 12:52:12.965 I/Perf    (30061): Connecting to perf service.
02-04 12:52:12.984 I/name.fireflyii(30061): [GL_OOM] ClampGrowthLimit 268435456
02-04 12:52:13.011 D/WM-WrkMgrInitializer(30061): Initializing WorkManager with default configuration.
02-04 12:52:13.026 W/name.fireflyii(30061): Accessing hidden field Ljava/util/Collections$SynchronizedCollection;->mutex:Ljava/lang/Object; (greylist-max-o, reflection, denied)
02-04 12:52:13.026 W/name.fireflyii(30061): Accessing hidden method Ljava/util/Collections$SynchronizedSet;-><init>(Ljava/util/Set;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
02-04 12:52:13.026 W/name.fireflyii(30061): Accessing hidden method Ljava/util/Collections$SynchronizedCollection;-><init>(Ljava/util/Collection;Ljava/lang/Object;)V (greylist-max-o, reflection, denied)
02-04 12:52:13.048 V/Font    (30061): Change font:2
02-04 12:52:13.048 V/Font    (30061): Default family:android.graphics.Typeface@3b7b816
02-04 12:52:13.151 I/ACRA    (30061): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
02-04 12:52:13.209 V/FlingOptimizerScroller(30061): FlingOptimizerOverScroller Init
02-04 12:52:13.215 W/name.fireflyii(30061): Accessing hidden method Landroid/view/Window;->getInsetsController()Landroid/view/WindowInsetsController; (blacklist, linking, denied)
02-04 12:52:13.366 D/NetworkSecurityConfig(30061): Using Network Security Config from resource network_security_config debugBuild: false
02-04 12:52:13.486 V/ViewRootImpl(30061): The specified message queue synchronization  barrier token has not been posted or has already been removed
02-04 12:52:13.514 D/ViewRootImpl[HomeActivity](30061): windowFocusChanged hasFocus=true inTouchMode=true
02-04 12:52:13.514 I/AdrenoGLES(30061): QUALCOMM build                   : 6209c5d, Ifdcc64d6e8
02-04 12:52:13.514 I/AdrenoGLES(30061): Build Date                       : 12/12/19
02-04 12:52:13.514 I/AdrenoGLES(30061): OpenGL ES Shader Compiler Version: EV031.27.05.03
02-04 12:52:13.514 I/AdrenoGLES(30061): Local Branch                     : mybranchea1c9b4a-9e05-f149-a3b2-1458d0b52ae8
02-04 12:52:13.514 I/AdrenoGLES(30061): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r85-rel
02-04 12:52:13.514 I/AdrenoGLES(30061): Remote Branch                    : NONE
02-04 12:52:13.514 I/AdrenoGLES(30061): Reconstruct Branch               : NOTHING
02-04 12:52:13.514 I/AdrenoGLES(30061): Build Config                     : C O 9.0.3 AArch64
02-04 12:52:13.519 I/AdrenoGLES(30061): PFP: 0x005ff112, ME: 0x005ff066
02-04 12:52:13.519 W/RecyclerView(30061): No adapter attached; skipping layout
02-04 12:52:13.619 W/Gralloc3(30061): mapper 3.x is not supported
02-04 12:52:13.632 D/ViewRootImpl[HomeActivity](30061): windowFocusChanged hasFocus=false inTouchMode=true
02-04 12:52:13.743 D/AndroidRuntime(30061): Shutting down VM
02-04 12:52:13.746 E/AndroidRuntime(30061): FATAL EXCEPTION: main
02-04 12:52:13.746 E/AndroidRuntime(30061): Process: xyz.hisname.fireflyiii, PID: 30061
02-04 12:52:13.746 E/AndroidRuntime(30061): java.util.NoSuchElementException: Char sequence is empty.
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at android.os.Handler.handleCallback(Handler.java:883)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at android.os.Looper.loop(Looper.java:214)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at java.lang.reflect.Method.invoke(Native Method)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-04 12:52:13.746 E/AndroidRuntime(30061): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
02-04 12:52:13.746 E/ACRA    (30061): ACRA caught a NoSuchElementException for xyz.hisname.fireflyiii
02-04 12:52:13.746 E/ACRA    (30061): java.util.NoSuchElementException: Char sequence is empty.
02-04 12:52:13.746 E/ACRA    (30061): 	at xyz.hisname.fireflyiii.ui.HomeActivity.$r8$lambda$m5_BfCzbKopEcr4W8HSTQOYhFWo(HomeActivity.kt:15)
02-04 12:52:13.746 E/ACRA    (30061): 	at xyz.hisname.fireflyiii.ui.HomeActivity$$ExternalSyntheticLambda5.onChanged(Unknown Source:10)
02-04 12:52:13.746 E/ACRA    (30061): 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:6)
02-04 12:52:13.746 E/ACRA    (30061): 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:8)
02-04 12:52:13.746 E/ACRA    (30061): 	at androidx.lifecycle.LiveData.setValue(LiveData.java:4)
02-04 12:52:13.746 E/ACRA    (30061): 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:1)
02-04 12:52:13.746 E/ACRA    (30061): 	at androidx.lifecycle.LiveData$1.run(LiveData.java:5)
02-04 12:52:13.746 E/ACRA    (30061): 	at android.os.Handler.handleCallback(Handler.java:883)
02-04 12:52:13.746 E/ACRA    (30061): 	at android.os.Handler.dispatchMessage(Handler.java:100)
02-04 12:52:13.746 E/ACRA    (30061): 	at android.os.Looper.loop(Looper.java:214)
02-04 12:52:13.746 E/ACRA    (30061): 	at android.app.ActivityThread.main(ActivityThread.java:7697)
02-04 12:52:13.746 E/ACRA    (30061): 	at java.lang.reflect.Method.invoke(Native Method)
02-04 12:52:13.746 E/ACRA    (30061): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
02-04 12:52:13.746 E/ACRA    (30061): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

USER_CRASH_DATE=2023-02-04T12:52:13.756+01:00

**Comment by JiriS97** [comment]
Oh, sorry, the Google Play store seems to not have the up-to-date version. Installed 5.0.5 from FDroid and works fine. Thanks!!!
