### ISSUE TITLE
Crash loops after upgrading to v1.2.2 (IllegalArgumentException: Unable to find GlideModule implementation)

### ISSUE THREAD

**Issue by hnrd** [emansih/FireflyMobile#28]
**Firefly III Server Version:**
4.7.10

**Firefly III Mobile Version:**
1.2.2 (from F-Droid)

**Android Version:**  
9

**Device Information:**  

- BRAND: Xiaomi
- MODEL: A1
--------------------------------------

## Expected Behavior
App would start ;)

## Current Behavior
App crashes immediately after starting, cleaning app cache and/or data does not help. 

## Steps to Reproduce
Install v1.2.2, watch the world burn.

Crash log:
```
REPORT_ID=aaf004d5-1bba-48b0-ae75-9d4590da11da
APP_VERSION_NAME=1.2.2
PHONE_MODEL=Mi A1
BRAND=xiaomi
PRODUCT=tissot
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2925)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
	at com.a.a.f.e.a(ManifestParser.java:69)
	at com.a.a.f.e.a(ManifestParser.java:47)
	at com.a.a.e.a(Glide.java:230)
	at com.a.a.e.d(Glide.java:221)
	at com.a.a.e.c(Glide.java:182)
	at com.a.a.e.a(Glide.java:166)
	at com.a.a.e.e(Glide.java:680)
	at com.a.a.e.b(Glide.java:707)
	at xyz.hisname.fireflyiii.ui.HomeActivity$c.a(HomeActivity.kt:136)
	at com.mikepenz.materialdrawer.e.b.a(DrawerImageLoader.java:65)
	at com.mikepenz.materialdrawer.b.a(AccountHeaderBuilder.java:1184)
	at com.mikepenz.materialdrawer.b.c(AccountHeaderBuilder.java:1079)
	at com.mikepenz.materialdrawer.b.a(AccountHeaderBuilder.java:862)
	at xyz.hisname.fireflyiii.ui.HomeActivity.a(HomeActivity.kt:120)
	at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:70)
	at android.app.Activity.performCreate(Activity.java:7136)
	at android.app.Activity.performCreate(Activity.java:7127)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
	... 11 more
Caused by: java.lang.ClassNotFoundException: com.bumptech.glide.integration.okhttp3.OkHttpGlideModule
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:453)
	at java.lang.Class.forName(Class.java:378)
	at com.a.a.f.e.a(ManifestParser.java:67)
	... 29 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.okhttp3.OkHttpGlideModule" on path: DexPathList[[zip file "/data/app/xyz.hisname.fireflyiii-i7r7FIdvkOZLHBqvFobLpQ==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.hisname.fireflyiii-i7r7FIdvkOZLHBqvFobLpQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 33 more

LOGCAT=02-07 10:59:22.476 I/OpenGLRenderer(21312): Initialized EGL, version 1.4
02-07 10:59:22.476 D/OpenGLRenderer(21312): Swap behavior 2
02-07 10:59:22.512 D/vndksupport(21312): Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
02-07 10:59:22.515 D/vndksupport(21312): Loading /vendor/lib64/hw/gralloc.msm8953.so from current namespace instead of sphal namespace.
02-07 10:59:22.966 W/ActivityThread(21312): handleWindowVisibility: no activity for token android.os.BinderProxy@c179085
02-07 10:59:22.989 I/FloatingActionButton(21312): Setting a custom background is not supported.
02-07 10:59:23.032 D/AndroidRuntime(21312): Shutting down VM
02-07 10:59:23.033 E/AndroidRuntime(21312): FATAL EXCEPTION: main
02-07 10:59:23.033 E/AndroidRuntime(21312): Process: xyz.hisname.fireflyiii, PID: 21312
02-07 10:59:23.033 E/AndroidRuntime(21312): java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2925)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.os.Looper.loop(Looper.java:193)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.ActivityThread.main(ActivityThread.java:6762)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at java.lang.reflect.Method.invoke(Native Method)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-07 10:59:23.033 E/AndroidRuntime(21312): Caused by: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.f.e.a(ManifestParser.java:69)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.f.e.a(ManifestParser.java:47)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.e.a(Glide.java:230)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.e.d(Glide.java:221)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.e.c(Glide.java:182)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.e.a(Glide.java:166)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.e.e(Glide.java:680)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.e.b(Glide.java:707)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at xyz.hisname.fireflyiii.ui.HomeActivity$c.a(HomeActivity.kt:136)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.mikepenz.materialdrawer.e.b.a(DrawerImageLoader.java:65)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.mikepenz.materialdrawer.b.a(AccountHeaderBuilder.java:1184)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.mikepenz.materialdrawer.b.c(AccountHeaderBuilder.java:1079)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.mikepenz.materialdrawer.b.a(AccountHeaderBuilder.java:862)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at xyz.hisname.fireflyiii.ui.HomeActivity.a(HomeActivity.kt:120)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:70)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.Activity.performCreate(Activity.java:7136)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.Activity.performCreate(Activity.java:7127)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	... 11 more
02-07 10:59:23.033 E/AndroidRuntime(21312): Caused by: java.lang.ClassNotFoundException: com.bumptech.glide.integration.okhttp3.OkHttpGlideModule
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at java.lang.Class.classForName(Native Method)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at java.lang.Class.forName(Class.java:453)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at java.lang.Class.forName(Class.java:378)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at com.a.a.f.e.a(ManifestParser.java:67)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	... 29 more
02-07 10:59:23.033 E/AndroidRuntime(21312): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.okhttp3.OkHttpGlideModule" on path: DexPathList[[zip file "/data/app/xyz.hisname.fireflyiii-i7r7FIdvkOZLHBqvFobLpQ==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.hisname.fireflyiii-i7r7FIdvkOZLHBqvFobLpQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-07 10:59:23.033 E/AndroidRuntime(21312): 	... 33 more
02-07 10:59:23.034 E/ACRA    (21312): ACRA caught a RuntimeException for xyz.hisname.fireflyiii
02-07 10:59:23.034 E/ACRA    (21312): java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2925)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1818)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.os.Looper.loop(Looper.java:193)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.ActivityThread.main(ActivityThread.java:6762)
02-07 10:59:23.034 E/ACRA    (21312): 	at java.lang.reflect.Method.invoke(Native Method)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-07 10:59:23.034 E/ACRA    (21312): Caused by: java.lang.IllegalArgumentException: Unable to find GlideModule implementation
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.f.e.a(ManifestParser.java:69)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.f.e.a(ManifestParser.java:47)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.e.a(Glide.java:230)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.e.d(Glide.java:221)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.e.c(Glide.java:182)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.e.a(Glide.java:166)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.e.e(Glide.java:680)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.e.b(Glide.java:707)
02-07 10:59:23.034 E/ACRA    (21312): 	at xyz.hisname.fireflyiii.ui.HomeActivity$c.a(HomeActivity.kt:136)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.mikepenz.materialdrawer.e.b.a(DrawerImageLoader.java:65)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.mikepenz.materialdrawer.b.a(AccountHeaderBuilder.java:1184)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.mikepenz.materialdrawer.b.c(AccountHeaderBuilder.java:1079)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.mikepenz.materialdrawer.b.a(AccountHeaderBuilder.java:862)
02-07 10:59:23.034 E/ACRA    (21312): 	at xyz.hisname.fireflyiii.ui.HomeActivity.a(HomeActivity.kt:120)
02-07 10:59:23.034 E/ACRA    (21312): 	at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:70)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.Activity.performCreate(Activity.java:7136)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.Activity.performCreate(Activity.java:7127)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
02-07 10:59:23.034 E/ACRA    (21312): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
02-07 10:59:23.034 E/ACRA    (21312): 	... 11 more
02-07 10:59:23.034 E/ACRA    (21312): Caused by: java.lang.ClassNotFoundException: com.bumptech.glide.integration.okhttp3.OkHttpGlideModule
02-07 10:59:23.034 E/ACRA    (21312): 	at java.lang.Class.classForName(Native Method)
02-07 10:59:23.034 E/ACRA    (21312): 	at java.lang.Class.forName(Class.java:453)
02-07 10:59:23.034 E/ACRA    (21312): 	at java.lang.Class.forName(Class.java:378)
02-07 10:59:23.034 E/ACRA    (21312): 	at com.a.a.f.e.a(ManifestParser.java:67)
02-07 10:59:23.034 E/ACRA    (21312): 	... 29 more
02-07 10:59:23.034 E/ACRA    (21312): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bumptech.glide.integration.okhttp3.OkHttpGlideModule" on path: DexPathList[[zip file "/data/app/xyz.hisname.fireflyiii-i7r7FIdvkOZLHBqvFobLpQ==/base.apk"],nativeLibraryDirectories=[/data/app/xyz.hisname.fireflyiii-i7r7FIdvkOZLHBqvFobLpQ==/lib/arm64, /system/lib64, /system/vendor/lib64]]
02-07 10:59:23.034 E/ACRA    (21312): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
02-07 10:59:23.034 E/ACRA    (21312): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
02-07 10:59:23.034 E/ACRA    (21312): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-07 10:59:23.034 E/ACRA    (21312): 	... 33 more
IS_SILENT=false
USER_CRASH_DATE=2019-02-07T10:59:23.037+01:00
```

**Comment by emansih** [comment]
sorry about that. I have fixed it in https://github.com/emansih/FireflyMobile/commit/77992795370bfe8b9262fb9a49b81d87d8c98835. I will push out the apk via Fdroid tonight.
