### ISSUE TITLE
lateinit property fireflyUrl has not been initialized

### ISSUE THREAD

**Issue by Ditti4** [emansih/FireflyMobile#3]
Hi! I just tried setting up the app on my phone running Android 6.0.1.

I was able to finish the authorization process and when I got back to the app, I got to the screen that says "Retrieving your data" (or something along those lines). There, I was stuck at around 30% for probably five minutes, so I tried to quit the app using the back button and reopen it. Upon reopening the app, this exception occurred:

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.onboarding.OnboardingActivity}: e.r: lateinit property fireflyUrl has not been initialized
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2455)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2515)
	at android.app.ActivityThread.access$1000(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1379)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5571)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
Caused by: e.r: lateinit property fireflyUrl has not been initialized
	at xyz.hisname.fireflyiii.ui.onboarding.f.ja(:4)
	at xyz.hisname.fireflyiii.ui.onboarding.f.a(:12)
	at b.k.a.u.a(:237)
	at b.k.a.u.e(:11)
	at b.k.a.u.b(:17)
	at b.k.a.a.d(:24)
	at b.k.a.u.b(:47)
	at b.k.a.u.a(:412)
	at b.k.a.u.b(:39)
	at b.k.a.u.i(:8)
	at b.k.a.u.e(:38)
	at b.k.a.u.q(:3)
	at b.k.a.l.f(:1)
	at b.k.a.j.onStart(:5)
	at androidx.appcompat.app.o.onStart(:1)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1238)
	at android.app.Activity.performStart(Activity.java:6374)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2418)
	... 9 more
```

**Comment by emansih** [comment]
Are you using v0.0.3? I fixed the bug in commit bdf8197d3f5fb71dc5555bd1466924fdefc85f43

**Comment by Ditti4** [comment]
I am indeed using 0.0.3 (just confirmed again by checking my system settings). So this should be fixed already?

**Comment by emansih** [comment]
I just tested it and I am affected by it too. This bug appears to stem from the project's proguard config since it only appears when on release builds and not debug builds.

**Comment by Ditti4** [comment]
It works perfectly now! Thanks for your quick help!
