### ISSUE TITLE
Parse Error for transaction in january

### ISSUE THREAD

**Issue by ImLemni** [emansih/FireflyMobile#44]
**Firefly III Server Version:4.7.17**

**Firefly III Mobile Version:1.2.14.1**

**Android Version:9**  
--------------------------------------

## Expected Behavior
I should be able to look at transactions that happened on january
## Current Behavior
When looking at transactions from the calendar view (either  withdrawal, revenue or transfer), I can correctly pick a date and get associated transactions. However if I do the same for any day in january, the app crashes.
## Steps to Reproduce
Pick any day from january (in any year) from the calendar in transactions view.

```
--------- beginning of crash
04-10 08:50:05.976 E/AndroidRuntime(12625): FATAL EXCEPTION: DefaultDispatcher-worker-3
04-10 08:50:05.976 E/AndroidRuntime(12625): Process: xyz.hisname.fireflyiii, PID: 12625
04-10 08:50:05.976 E/AndroidRuntime(12625): org.b.a.b.e: Text '2019-1-11' could not be parsed at index 5
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at org.b.a.b.b.a(DateTimeFormatter.java:1588)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at org.b.a.b.b.a(DateTimeFormatter.java:1491)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at org.b.a.f.a(LocalDate.java:367)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at org.b.a.f.a(LocalDate.java:352)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at xyz.hisname.fireflyiii.util.a.b(DateTimeUtil.kt:26)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at xyz.hisname.fireflyiii.repository.j.a.c(TransactionRepository.kt:103)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at xyz.hisname.fireflyiii.repository.j.b$ad$1.b(TransactionsViewModel.kt:456)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at b.c.b.a.a.a(ContinuationImpl.kt:32)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at kotlinx.coroutines.ar.run(Dispatched.kt:233)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:594)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:60)
04-10 08:50:05.976 E/AndroidRuntime(12625): 	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:742)
04-10 08:50:05.977 E/ACRA    (12625): ACRA caught a e for xyz.hisname.fireflyiii
04-10 08:50:05.977 E/ACRA    (12625): org.b.a.b.e: Text '2019-1-11' could not be parsed at index 5
04-10 08:50:05.977 E/ACRA    (12625): 	at org.b.a.b.b.a(DateTimeFormatter.java:1588)
04-10 08:50:05.977 E/ACRA    (12625): 	at org.b.a.b.b.a(DateTimeFormatter.java:1491)
04-10 08:50:05.977 E/ACRA    (12625): 	at org.b.a.f.a(LocalDate.java:367)
04-10 08:50:05.977 E/ACRA    (12625): 	at org.b.a.f.a(LocalDate.java:352)
04-10 08:50:05.977 E/ACRA    (12625): 	at xyz.hisname.fireflyiii.util.a.b(DateTimeUtil.kt:26)
04-10 08:50:05.977 E/ACRA    (12625): 	at xyz.hisname.fireflyiii.repository.j.a.c(TransactionRepository.kt:103)
04-10 08:50:05.977 E/ACRA    (12625): 	at xyz.hisname.fireflyiii.repository.j.b$ad$1.b(TransactionsViewModel.kt:456)
04-10 08:50:05.977 E/ACRA    (12625): 	at b.c.b.a.a.a(ContinuationImpl.kt:32)
04-10 08:50:05.977 E/ACRA    (12625): 	at kotlinx.coroutines.ar.run(Dispatched.kt:233)
04-10 08:50:05.977 E/ACRA    (12625): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:594)
04-10 08:50:05.977 E/ACRA    (12625): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:60)
04-10 08:50:05.977 E/ACRA    (12625): 	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:742)
```

**Comment by emansih** [comment]
Never noticed such a bug before

**Comment by ImLemni** [comment]
I can send you the full log file if it can bring any help

**Comment by emansih** [comment]
Well,I can replicate the bug. I will investigate when I get back on my computer

**Comment by emansih** [comment]
Fixed in the latest release
