### ISSUE TITLE
IllegalArgumentException during entering of access token

### ISSUE THREAD

**Issue by krichter722** [emansih/FireflyMobile#46]
**Firefly III Server Version:**
4.7.17

**Firefly III Mobile Version:**
2.1.15

**Android Version:**  
7 (LineagesOS 14.1)

**Device Information:**  

- BRAND: Motorola
- MODEL: Moto G 2014
--------------------------------------

## Expected Behavior
Login with access token should succeed or fail with an intuitive error message also if the user behaves erroneously.

## Current Behavior
The application crashes and opens the mail application with a draft containing the following stacktrace:

```
REPORT_ID=99bb3881-9396-42dd-b776-39175425a52b
APP_VERSION_NAME=1.2.15
PHONE_MODEL=Moto G 2014
BRAND=motorola
PRODUCT=lineage_titan
ANDROID_VERSION=7.1.2
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalArgumentException: Unexpected char 0xfeff at 7 in Authorization value: Bearer ﻿eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImRlOGU3YzIzNjhkYTJkNTEwNTQzOWI5MzhkODhjOTFkMmY1MGRlZDhlNTgwMWFkMzMyMjJlNmFkYjIxYWU0OTRkYzUyOGY3MDJjYTQwNzU3In0.eyJhdWQiOiIxIiwianRpIjoiZGU4ZTdjMjM2OGRhMmQ1MTA1NDM5YjkzOGQ4OGM5MWQyZjUwZGVkOGU1ODAxYWQzMzIyMmU2YWRiMjFhZTQ5NGRjNTI4ZjcwMmNhNDA3NTciLCJpYXQiOjE1NTUxNzA2NjcsIm5iZiI6MTU1NTE3MDY2NywiZXhwIjoxNTg2NzkzMDY3LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.ZDVDJBYo5utRIaDDKqNHN6KYSinpHQAp-8LbUl0SJrf54W3JOL1kJafLBDy_Psx66vwqw1wUHnspUIPSgTnUD9_jyfGonVuf45lZ_Z2O7HF_amwYE27eDtMZKxis48cFhcJOMBjMYO2jRwkaZPhQSTyIM7DdeKBWTftykkm9nhF0-BylFCf2vMqLJgOekOLLOjlgp8-a4HBgQCjfz9nmcMxnwRv_AYu1-TSNqFwYBkH1yfK9JkkrLirgOijbgj6sOE0Ut98iTvE-ORWhmgAVoNjA7CarXGXQfI6lbBOZ8-bncpCO78XKCEljXirJ7dHG6vvFSQVYTqKEctkp8w9YO8Z-u7dmPWZx7KBV26Q092q70x6rA4wfoRTEkAWUC052NsCPWv3YdWqOIk4Df5S8XjrfiCkxjBR-9U-PU8BSLl3xtIjcf34JUzU-_DpGQx__Wlc1ibwgJInmI-XhGbDCryqJG5vNSZCY9Axlnn5MLpQbGMiJYf_qxTskv0uO0lOYmrKJXsu7gIn7uYX25axAnciYSxYomiWn1jbPHJcQ_KdUvrgqpGJAopbQHepSSXjBBSuo_nDzupmRaud6H4HXrJjRU1yS8qpAFc8FaibBwqNyZTVEI0dFDDxlYqStheYiy_AFeNGzpYo4zOrMalgiDpLT5JzP7Ut4AXGc5crmCz4
	at okhttp3.s.a(Headers.java:272)
	at okhttp3.s$a.c(Headers.java:384)
	at okhttp3.aa$a.a(Request.java:184)
	at xyz.hisname.fireflyiii.util.c.c.a(HeaderInterceptor.kt:12)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:147)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:121)
	at okhttp3.z.g(RealCall.java:254)
	at okhttp3.z$a.c(RealCall.java:200)
	at okhttp3.internal.b.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

LOGCAT=04-13 17:50:25.076 I/MultiDex(29103): VM with version 2.1.0 has multidex support
04-13 17:50:25.076 I/MultiDex(29103): Installing application
04-13 17:50:25.076 I/MultiDex(29103): VM has multidex support, MultiDex support library is disabled.
04-13 17:50:25.389 I/art     (29103): Background partial concurrent mark sweep GC freed 15933(727KB) AllocSpace objects, 2(40KB) LOS objects, 53% free, 3MB/7MB, paused 5.685ms total 72.657ms
04-13 17:50:25.607 I/ACRA    (29103): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
04-13 17:50:26.129 I/Adreno-EGL(29103): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
04-13 17:50:26.142 I/OpenGLRenderer(29103): Initialized EGL, version 1.4
04-13 17:50:26.142 D/OpenGLRenderer(29103): Swap behavior 1
04-13 17:50:26.149 W/RenderThread(29130): type=1400 audit(0.0:434): avc: denied { read } for uid=10101 name="gpuclk" dev="sysfs" ino=16842 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
04-13 17:50:26.155 W/Adreno-ES20(29103): <get_gpu_clk:229>: open failed: errno 13
04-13 17:50:27.361 I/art     (29103): Do partial code cache collection, code=12KB, data=31KB
04-13 17:50:27.364 I/art     (29103): After code cache collection, code=8KB, data=27KB
04-13 17:50:27.364 I/art     (29103): Increasing code cache capacity to 128KB
04-13 17:50:30.190 I/art     (29103): Do partial code cache collection, code=54KB, data=62KB
04-13 17:50:30.193 I/art     (29103): After code cache collection, code=54KB, data=62KB
04-13 17:50:30.193 I/art     (29103): Increasing code cache capacity to 256KB
04-13 17:51:00.176 W/IInputConnectionWrapper(29103): finishComposingText on inactive InputConnection
04-13 17:51:15.284 W/IInputConnectionWrapper(29103): finishComposingText on inactive InputConnection
04-13 17:51:15.299 W/IInputConnectionWrapper(29103): reportFullscreenMode on inexistent InputConnection
04-13 17:51:15.300 W/IInputConnectionWrapper(29103): finishComposingText on inactive InputConnection
04-13 17:51:49.049 W/RenderThread(29130): type=1400 audit(0.0:436): avc: denied { read } for uid=10101 name="gpuclk" dev="sysfs" ino=16842 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
04-13 17:51:49.049 I/Adreno-EGL(29103): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
04-13 17:51:49.049 I/OpenGLRenderer(29103): Initialized EGL, version 1.4
04-13 17:51:49.049 D/OpenGLRenderer(29103): Swap behavior 1
04-13 17:51:49.052 W/Adreno-ES20(29103): <get_gpu_clk:229>: open failed: errno 13
04-13 17:51:54.098 W/art     (29103): Suspending all threads took: 10.590ms
04-13 17:51:54.109 I/art     (29103): Background sticky concurrent mark sweep GC freed 10891(631KB) AllocSpace objects, 5(260KB) LOS objects, 14% free, 5MB/6MB, paused 11.487ms total 118.253ms
04-13 17:51:54.231 D/NetworkSecurityConfig(29103): No Network Security Config specified, using platform default
04-13 17:51:54.594 I/Choreographer(29103): Skipped 68 frames!  The application may be doing too much work on its main thread.
04-13 17:51:54.648 E/ACRA    (29103): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
04-13 17:51:54.648 E/ACRA    (29103): java.lang.IllegalArgumentException: Unexpected char 0xfeff at 7 in Authorization value: Bearer ﻿eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImRlOGU3YzIzNjhkYTJkNTEwNTQzOWI5MzhkODhjOTFkMmY1MGRlZDhlNTgwMWFkMzMyMjJlNmFkYjIxYWU0OTRkYzUyOGY3MDJjYTQwNzU3In0.eyJhdWQiOiIxIiwianRpIjoiZGU4ZTdjMjM2OGRhMmQ1MTA1NDM5YjkzOGQ4OGM5MWQyZjUwZGVkOGU1ODAxYWQzMzIyMmU2YWRiMjFhZTQ5NGRjNTI4ZjcwMmNhNDA3NTciLCJpYXQiOjE1NTUxNzA2NjcsIm5iZiI6MTU1NTE3MDY2NywiZXhwIjoxNTg2NzkzMDY3LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.ZDVDJBYo5utRIaDDKqNHN6KYSinpHQAp-8LbUl0SJrf54W3JOL1kJafLBDy_Psx66vwqw1wUHnspUIPSgTnUD9_jyfGonVuf45lZ_Z2O7HF_amwYE27eDtMZKxis48cFhcJOMBjMYO2jRwkaZPhQSTyIM7DdeKBWTftykkm9nhF0-BylFCf2vMqLJgOekOLLOjlgp8-a4HBgQCjfz9nmcMxnwRv_AYu1-TSNqFwYBkH1yfK9JkkrLirgOijbgj6sOE0Ut98iTvE-ORWhmgAVoNjA7CarXGXQfI6lbBOZ8-bncpCO78XKCEljXirJ7dHG6vvFSQVYTqKEctkp8w9YO8Z-u7dmPWZx7KBV26Q092q70x6rA4wfoRTEkAWUC052NsCPWv3YdWqOIk4Df5S8XjrfiCkxjBR-9U-PU8BSLl3xtIjcf34JUzU-_DpGQx__Wlc1ibwgJInmI-XhGbDCryqJG5vNSZCY9Axlnn5MLpQbGMiJYf_qxTskv0uO0lOYmrKJXsu7gIn7uYX25axAnciYSxYomiWn1jbPHJcQ_KdUvrgqpGJAopbQHepSSXjBBSuo_nDzupmRaud6H4HXrJjRU1yS8qpAFc8FaibBwqNyZTVEI0dFDDxlYqStheYiy_AFeNGzpYo4zOrMalgiDpLT5JzP7Ut4AXGc5crmCz4
04-13 17:51:54.648 E/ACRA    (29103): 	at okhttp3.s.a(Headers.java:272)
04-13 17:51:54.648 E/ACRA    (29103): 	at okhttp3.s$a.c(Headers.java:384)
04-13 17:51:54.648 E/ACRA    (29103): 	at okhttp3.aa$a.a(Request.java:184)
04-13 17:51:54.648 E/ACRA    (29103): 	at xyz.hisname.fireflyiii.util.c.c.a(HeaderInterceptor.kt:12)
04-13 17:51:54.648 E/ACRA    (29103): 	at okhttp3.internal.c.g.a(RealInterceptorChain.java:147)
04-13 17:51:54.648 E/ACRA    (29103): 	at okhttp3.internal.c.g.a(RealInterceptorChain.java:121)
04-13 17:51:54.648 E/ACRA    (29103): 	at okhttp3.z.g(RealCall.java:254)
04-13 17:51:54.648 E/ACRA    (29103): 	at okhttp3.z$a.c(RealCall.java:200)
04-13 17:51:54.648 E/ACRA    (29103): 	at okhttp3.internal.b.run(NamedRunnable.java:32)
04-13 17:51:54.648 E/ACRA    (29103): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-13 17:51:54.648 E/ACRA    (29103): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-13 17:51:54.648 E/ACRA    (29103): 	at java.lang.Thread.run(Thread.java:761)
04-13 17:51:55.068 I/art     (29103): Background partial concurrent mark sweep GC freed 20119(1123KB) AllocSpace objects, 5(220KB) LOS objects, 46% free, 4MB/8MB, paused 12.046ms total 112.907ms
04-13 17:51:55.457 I/Process (29103): Sending signal. PID: 29103 SIG: 9
04-13 17:51:55.616 W/System  (29797): ClassLoader referenced unknown path: /mnt/expand/b32ddf81-96df-41c5-8325-c800da2115a1/app/xyz.hisname.fireflyiii-2/lib/arm
04-13 17:51:55.718 I/MultiDex(29797): VM with version 2.1.0 has multidex support
04-13 17:51:55.718 I/MultiDex(29797): Installing application
04-13 17:51:55.718 I/MultiDex(29797): VM has multidex support, MultiDex support library is disabled.
04-13 17:51:56.335 W/art     (29797): Suspending all threads took: 7.823ms
04-13 17:51:56.878 I/ACRA    (29797): Sending report /mnt/expand/b32ddf81-96df-41c5-8325-c800da2115a1/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2019-04-13T17:51:54.692+02:00-IS_SILENT.stacktrace
04-13 17:52:01.490 W/System  (29954): ClassLoader referenced unknown path: /mnt/expand/b32ddf81-96df-41c5-8325-c800da2115a1/app/xyz.hisname.fireflyiii-2/lib/arm
04-13 17:52:01.877 I/art     (29954): Background partial concurrent mark sweep GC freed 15706(672KB) AllocSpace objects, 1(20KB) LOS objects, 57% free, 2MB/6MB, paused 10.392ms total 80.922ms
04-13 17:52:01.883 I/MultiDex(29954): VM with version 2.1.0 has multidex support
04-13 17:52:01.884 I/MultiDex(29954): Installing application
04-13 17:52:01.884 I/MultiDex(29954): VM has multidex support, MultiDex support library is disabled.
04-13 17:52:02.832 I/ACRA    (29954): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
04-13 17:52:03.716 I/Adreno-EGL(29954): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
04-13 17:52:03.722 I/OpenGLRenderer(29954): Initialized EGL, version 1.4
04-13 17:52:03.722 D/OpenGLRenderer(29954): Swap behavior 1
04-13 17:52:03.729 W/RenderThread(30016): type=1400 audit(0.0:437): avc: denied { read } for uid=10101 name="gpuclk" dev="sysfs" ino=16842 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
04-13 17:52:03.733 W/Adreno-ES20(29954): <get_gpu_clk:229>: open failed: errno 13
04-13 17:52:05.064 I/art     (29954): Do partial code cache collection, code=12KB, data=30KB
04-13 17:52:05.067 I/art     (29954): After code cache collection, code=8KB, data=26KB
04-13 17:52:05.067 I/art     (29954): Increasing code cache capacity to 128KB
04-13 17:52:18.759 W/RenderThread(30016): type=1400 audit(0.0:438): avc: denied { read } for uid=10101 name="gpuclk" dev="sysfs" ino=16842 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
04-13 17:52:18.760 I/Adreno-EGL(29954): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
04-13 17:52:18.760 I/OpenGLRenderer(29954): Initialized EGL, version 1.4
04-13 17:52:18.761 D/OpenGLRenderer(29954): Swap behavior 1
04-13 17:52:18.764 W/Adreno-ES20(29954): <get_gpu_clk:229>: open failed: errno 13
04-13 17:52:22.928 I/art     (29954): Do partial code cache collection, code=52KB, data=62KB
04-13 17:52:22.929 I/art     (29954): After code cache collection, code=52KB, data=62KB
04-13 17:52:22.929 I/art     (29954): Increasing code cache capacity to 256KB
04-13 17:52:29.356 W/IInputConnectionWrapper(29954): finishComposingText on inactive InputConnection
04-13 17:52:29.359 W/IInputConnectionWrapper(29954): finishComposingText on inactive InputConnection
04-13 17:52:29.359 W/IInputConnectionWrapper(29954): reportFullscreenMode on inexistent InputConnection
04-13 17:52:29.359 W/IInputConnectionWrapper(29954): finishComposingText on inactive InputConnection
04-13 17:53:58.522 W/RenderThread(30016): type=1400 audit(0.0:439): avc: denied { read } for uid=10101 name="gpuclk" dev="sysfs" ino=16842 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
04-13 17:53:58.525 I/Adreno-EGL(29954): <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
04-13 17:53:58.526 I/OpenGLRenderer(29954): Initialized EGL, version 1.4
04-13 17:53:58.526 D/OpenGLRenderer(29954): Swap behavior 1
04-13 17:53:58.528 W/Adreno-ES20(29954): <get_gpu_clk:229>: open failed: errno 13
04-13 17:54:19.406 W/IInputConnectionWrapper(29954): finishComposingText on inactive InputConnection
04-13 17:54:30.909 I/art     (29954): Background sticky concurrent mark sweep GC freed 15622(973KB) AllocSpace objects, 4(240KB) LOS objects, 15% free, 5MB/6MB, paused 720us total 152.906ms
04-13 17:54:31.095 D/NetworkSecurityConfig(29954): No Network Security Config specified, using platform default
04-13 17:54:31.459 I/Choreographer(29954): Skipped 78 frames!  The application may be doing too much work on its main thread.
04-13 17:54:31.482 E/ACRA    (29954): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
04-13 17:54:31.482 E/ACRA    (29954): java.lang.IllegalArgumentException: Unexpected char 0xfeff at 7 in Authorization value: Bearer ﻿eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImRlOGU3YzIzNjhkYTJkNTEwNTQzOWI5MzhkODhjOTFkMmY1MGRlZDhlNTgwMWFkMzMyMjJlNmFkYjIxYWU0OTRkYzUyOGY3MDJjYTQwNzU3In0.eyJhdWQiOiIxIiwianRpIjoiZGU4ZTdjMjM2OGRhMmQ1MTA1NDM5YjkzOGQ4OGM5MWQyZjUwZGVkOGU1ODAxYWQzMzIyMmU2YWRiMjFhZTQ5NGRjNTI4ZjcwMmNhNDA3NTciLCJpYXQiOjE1NTUxNzA2NjcsIm5iZiI6MTU1NTE3MDY2NywiZXhwIjoxNTg2NzkzMDY3LCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.ZDVDJBYo5utRIaDDKqNHN6KYSinpHQAp-8LbUl0SJrf54W3JOL1kJafLBDy_Psx66vwqw1wUHnspUIPSgTnUD9_jyfGonVuf45lZ_Z2O7HF_amwYE27eDtMZKxis48cFhcJOMBjMYO2jRwkaZPhQSTyIM7DdeKBWTftykkm9nhF0-BylFCf2vMqLJgOekOLLOjlgp8-a4HBgQCjfz9nmcMxnwRv_AYu1-TSNqFwYBkH1yfK9JkkrLirgOijbgj6sOE0Ut98iTvE-ORWhmgAVoNjA7CarXGXQfI6lbBOZ8-bncpCO78XKCEljXirJ7dHG6vvFSQVYTqKEctkp8w9YO8Z-u7dmPWZx7KBV26Q092q70x6rA4wfoRTEkAWUC052NsCPWv3YdWqOIk4Df5S8XjrfiCkxjBR-9U-PU8BSLl3xtIjcf34JUzU-_DpGQx__Wlc1ibwgJInmI-XhGbDCryqJG5vNSZCY9Axlnn5MLpQbGMiJYf_qxTskv0uO0lOYmrKJXsu7gIn7uYX25axAnciYSxYomiWn1jbPHJcQ_KdUvrgqpGJAopbQHepSSXjBBSuo_nDzupmRaud6H4HXrJjRU1yS8qpAFc8FaibBwqNyZTVEI0dFDDxlYqStheYiy_AFeNGzpYo4zOrMalgiDpLT5JzP7Ut4AXGc5crmCz4
04-13 17:54:31.482 E/ACRA    (29954): 	at okhttp3.s.a(Headers.java:272)
04-13 17:54:31.482 E/ACRA    (29954): 	at okhttp3.s$a.c(Headers.java:384)
04-13 17:54:31.482 E/ACRA    (29954): 	at okhttp3.aa$a.a(Request.java:184)
04-13 17:54:31.482 E/ACRA    (29954): 	at xyz.hisname.fireflyiii.util.c.c.a(HeaderInterceptor.kt:12)
04-13 17:54:31.482 E/ACRA    (29954): 	at okhttp3.internal.c.g.a(RealInterceptorChain.java:147)
04-13 17:54:31.482 E/ACRA    (29954): 	at okhttp3.internal.c.g.a(RealInterceptorChain.java:121)
04-13 17:54:31.482 E/ACRA    (29954): 	at okhttp3.z.g(RealCall.java:254)
04-13 17:54:31.482 E/ACRA    (29954): 	at okhttp3.z$a.c(RealCall.java:200)
04-13 17:54:31.482 E/ACRA    (29954): 	at okhttp3.internal.b.run(NamedRunnable.java:32)
04-13 17:54:31.482 E/ACRA    (29954): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
04-13 17:54:31.482 E/ACRA    (29954): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
04-13 17:54:31.482 E/ACRA    (29954): 	at java.lang.Thread.run(Thread.java:761)
IS_SILENT=false
USER_CRASH_DATE=2019-04-13T17:54:31.505+02:00
```

## Steps to Reproduce
* Start server with `docker-compose up` and generate access token
* Open application and choose login with access token
* specify address, e.g. http://192.168.1.2:8090 and enter the access token (copied from server in order to avoid typos)

**Comment by emansih** [comment]
I just setup a fresh docker container to test it out. I can't replicate this issue. The reason there is a crash is because it appears that there is a unicode character in your Bearer Token.

> Bearer ﻿eyJ0eXAiO
        ^
Try regenerating a new client. If it fails again please open a bug report on Firefly III main repo.

**Comment by krichter722** [comment]
>The reason there is a crash is because it appears that there is a unicode character in your Bearer Token.
>
>>    Bearer ﻿eyJ0eXAiO

My intention to open this report was to get this behaviour fixed because a UI component like a dialog explaining that an unsupported character has been entered is a much better solution that let the application crash. I doubt that it makes any sense to report this to the main repo as this is clearly a client issue.

**Comment by emansih** [comment]
Yeah I agree. But the server should not output an invalid char in the first place.

**Comment by emansih** [comment]
I will still fix it anyway

**Comment by JC5** [comment]
What OS are you running docker compose on? Did a full reset of the docker stack work?

**Comment by emansih** [comment]
probably just a fluke? 


P.S. this software is unrelated to James Cole.

**Comment by krichter722** [comment]
> probably just a fluke?

What do you mean by that?

> P.S. this software is unrelated to James Cole.

And by that?

**Comment by emansih** [comment]
By "fluke" i mean it's one in a million chance that the bug happened since we can't replicate the issue.

**Comment by krichter722** [comment]
It'd be appreciated if you'd fix the application crash and provide feedback for the users - it's probably a one-liner.

**Comment by JC5** [comment]
I’m pretty sure he was going to do that already. No need to be sharp about it.

**Comment by krichter722** [comment]
@JC5 That's what seem to be the intention based on the first comments, however the issue is closed without a fix (in terms of the expected behaviour) or an explanation why it's invalid (which would be fine as well), so there no reason for me to believe that he was going to do that. Issue trackers exist in order to avoid that kind of ping pong.

**Comment by emansih** [comment]
It was a fixed in the latest release. (Check the release page)
