### ISSUE TITLE
Using transaction shortcut results in exception

### ISSUE THREAD

**Issue by Ditti4** [emansih/FireflyMobile#5]
I'm running the latest release 0.04 on Android 6.0.1.

When I enable "Add transactions anytime anywhere" and try to use one of the transaction shortcuts, this exception is thrown:

```
java.lang.RuntimeException: Unable to start receiver xyz.hisname.fireflyiii.GenericReceiver: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2771)
	at android.app.ActivityThread.access$1900(ActivityThread.java:154)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1458)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5571)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:682)
	at android.app.ContextImpl.startActivity(ContextImpl.java:669)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:341)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:341)
	at xyz.hisname.fireflyiii.GenericReceiver.onReceive(:81)
	at android.app.ActivityThread.handleReceiver(ActivityThread.java:2764)
	... 8 more
```

**Comment by emansih** [comment]
My current device is running android 8.0.0(security patch date: 1 September 2018) and I am not seeing this issue. I will attempt to replicate this bug in an emulator.
