### ISSUE TITLE
Unable to Login via PAT or OAUTH

### ISSUE THREAD

**Issue by dIELERx** [emansih/FireflyMobile#53]
**Firefly III Server Version:** 4.7.17

**Firefly III Mobile Version:** 1.3.5

**Android Version:**  9

**Device Information:**  

- BRAND: Xiaomi 
- MODEL: Redmi Note 5
--------------------------------------

## Expected Behavior
App logs in to Firefly after entering the correct credentials.

## Current Behavior
Firefly is running via Docker on default Port 9001 and on Port 443 via Nginx Reverse Proxy to have SSL/TLS Support.

I am able to access Firefly with the following URLs:
- http://hostname.domain:9001
- https://hostname.domain

I have configured Oauth and PAT.

### PAT
When I enter the URL and the PAT, and click Login, the App is just showing the loading animation. Nothing else happens.
![grafik](https://user-images.githubusercontent.com/32218246/61133977-d4a78280-a4be-11e9-8daf-275146865e0c.png)

### OAUTH
When I enter URL, Client-ID and Secret, my Browser opens and I have to login to Firefly. After successful login, I can click "Authorize" or "Cancel".
When I click "Authorize", the Browser opens the URL "http://emtpy/?code=XXX. This is the URL I entered as Callback_URL in the OAUTH Settings in Firefly.
Afterwards I switch back to the App and I am just seeing the loading animation. Nothing else happens.
![grafik](https://user-images.githubusercontent.com/32218246/61133966-ceb1a180-a4be-11e9-8887-5af33d5fffca.png)
![grafik](https://user-images.githubusercontent.com/32218246/61133972-d2452880-a4be-11e9-9bcd-76beae8070c6.png)

I first thought it might be a problem caused by the reverse proxy, therefore I tried these steps with the non https URL... but no difference.

Am I doing something wrong? 

Hope there is someone who can help me.
Sorry for those big screenshots, I did not find a way to resize them. Simple markdown does not work.

Thanks

Regards Dieler

**Comment by dIELERx** [comment]
NVM.. seems to be a problem of my Android Browser. I tried a few different ones and with Firefox or Chrome its working.

**Comment by emansih** [comment]
Regarding PAT, https://github.com/emansih/FireflyMobile/issues/52#issuecomment-510898557 . I admit there is a bug in it. Which browsers have you tried? I can take a look at it.

**Comment by dIELERx** [comment]
Fennec Browser (Fork of Firefox) and FOSS Browser didnt work for me. Then I tried Firefox and Chrome and on both the OAUTH worked. 

But PAT is still not working for me. I do not see any log entries on my webserver.... seems like the app is not connecting to the webserver at all.

I have one more question: Right now, I got the error **"java.security.CertPathValidatorException: Trust anchor for certification path not found"**... this is caused by a self signed certificate. On my LAN, I got my own Root CA and a few Sub CA's to manage all my local certificates for Servers, VPNs and stuff like that. 

Is there a way to get the app running with a self signed certificate?

Thanks a lot

**Comment by emansih** [comment]
Have you added your cert to Android's trust store?

**Comment by dIELERx** [comment]
Yes, added my Root CA and 2 SubCA's to the trust store. Under trusted credentials "User" I can see all of them.

**Comment by emansih** [comment]
@dIELERx  
> java.security.CertPathValidatorException: Trust anchor for certification path not found

would you like to try this APK? https://drive.google.com/open?id=1CscoUQI1Uo0A30n1k_GY1n1KoXGolhfw

**Comment by dIELERx** [comment]
This seems to work, no more warning regarding SSL/TLS.
But I got the next warning; **Failed to connect to hostname.domain** (i replaced my hostname)

**Comment by dIELERx** [comment]
Ah sorry, forget about my previous post. I had a permission error for this apk. Did not have permission to access the internet. 

still the same problem: java.security.CertPathValidatorException: Trust anchor for certification path not found

**Comment by emansih** [comment]
Yup. That's normal. 

> Apps that target API Level 24 and above no longer trust user or admin-added CAs for secure connections, by default.





https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html?m=1

**Comment by emansih** [comment]
I will just add an _advanced_  option allowing users to use their own cert.

**Comment by dIELERx** [comment]
As my device is rooted, I just installed my certificates via adb as "system" certificates. 
But still the same problem... none of my apps seem to accept those certificates... But as it is part of the system-wide trusted ca's, this shouldn't be a problem... it should work on all apps...

maybe theres a bug with my rom or something.

**Comment by emansih** [comment]
@dIELERx I just tried Fennec,it works for me. The steps are same as Firefox.

**Comment by emansih** [comment]
> Afterwards I rebooted my device

ah the good old, have you tried turning off and on again

**Comment by emansih** [comment]
OK, I just tried FOSS browser. Here's the instructions: https://github.com/emansih/FireflyMobile/wiki/Authentication#foss-browser

**Comment by dIELERx** [comment]
> @dIELERx I just tried Fennec,it works for me. The steps are same as Firefox.

I updated my Fennec Version from 67.0.2 to 67.0.3 (latest) and this seems to fix this problem. After refresh, I see the Android Icon.

**Comment by dIELERx** [comment]
I installed your current version 1.3.6 and logged in via OAUTH (Browser does not seem to matter, I tried Fennec, Firefox and FOSS). As soon as I get redirected to the app, it just crashs.

Here are two crash logs:
```
REPORT_ID=8df9f6e6-a528-4eb5-8e86-0fae8346c64a
APP_VERSION_NAME=1.3.6
PHONE_MODEL=Redmi Note 5
BRAND=Xiaomi
PRODUCT=whyred
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter value
	at xyz.hisname.fireflyiii.a.a.b.a.f(Unknown Source:2)
	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:4)
	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:1)
	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
	at i.l.run(DefaultCallAdapterFactory.java:3)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

LOGCAT=07-13 08:36:52.298 E/AndroidRuntime( 9999): Process: xyz.hisname.fireflyiii, PID: 9999
07-13 08:36:52.298 E/AndroidRuntime( 9999): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter value
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at xyz.hisname.fireflyiii.a.a.b.a.f(Unknown Source:2)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:4)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:1)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at i.l.run(DefaultCallAdapterFactory.java:3)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at android.os.Handler.handleCallback(Handler.java:873)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at android.os.Looper.loop(Looper.java:193)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at java.lang.reflect.Method.invoke(Native Method)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
07-13 08:36:52.299 E/ACRA    ( 9999): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
07-13 08:36:52.299 E/ACRA    ( 9999): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter value
07-13 08:36:52.299 E/ACRA    ( 9999): 	at xyz.hisname.fireflyiii.a.a.b.a.f(Unknown Source:2)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:4)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:1)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at i.l.run(DefaultCallAdapterFactory.java:3)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at android.os.Handler.handleCallback(Handler.java:873)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at android.os.Looper.loop(Looper.java:193)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at java.lang.reflect.Method.invoke(Native Method)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
07-13 08:36:52.352 I/ACRA    ( 9999): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2019-07-13T08:36:52.313+02:00.stacktrace
07-13 08:36:52.387 I/Process ( 9999): Sending signal. PID: 9999 SIG: 9
07-13 08:36:52.919 E/fireflyiii:acr(12756): Not starting debugger since process cannot load the jdwp agent.
07-13 08:36:52.980 I/MultiDex(12756): VM with version 2.1.0 has multidex support
07-13 08:36:52.980 I/MultiDex(12756): Installing application
07-13 08:36:52.980 I/MultiDex(12756): VM has multidex support, MultiDex support library is disabled.
07-13 08:39:31.140 E/name.fireflyii(13455): Not starting debugger since process cannot load the jdwp agent.
07-13 08:39:31.188 I/MultiDex(13455): VM with version 2.1.0 has multidex support
07-13 08:39:31.188 I/MultiDex(13455): Installing application
07-13 08:39:31.188 I/MultiDex(13455): VM has multidex support, MultiDex support library is disabled.
07-13 08:39:31.272 I/ACRA    (13455): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
07-13 08:39:31.350 D/NetworkSecurityConfig(13455): Using Network Security Config from resource network_security_config debugBuild: false
07-13 08:39:31.358 I/MaterialDrawer(13455): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-13 08:39:31.579 D/OpenGLRenderer(13455): Skia GL Pipeline
07-13 08:39:31.580 I/ViewRootImpl(13455): CPU Rendering VSync enable = true
07-13 08:39:31.677 I/MaterialDrawer(13455): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-13 08:39:31.808 I/ViewRootImpl(13455): CPU Rendering VSync enable = true
07-13 08:39:31.950 I/Adreno  (13455): QUALCOMM build                   : 9128d71, Ib33d3e8e13
07-13 08:39:31.950 I/Adreno  (13455): Build Date                       : 10/23/18
07-13 08:39:31.950 I/Adreno  (13455): OpenGL ES Shader Compiler Version: EV031.25.03.01
07-13 08:39:31.950 I/Adreno  (13455): Local Branch                     : 
07-13 08:39:31.950 I/Adreno  (13455): Remote Branch                    : 
07-13 08:39:31.950 I/Adreno  (13455): Remote Branch                    : 
07-13 08:39:31.950 I/Adreno  (13455): Reconstruct Branch               : 
07-13 08:39:31.950 I/Adreno  (13455): Build Config                     : S L 6.0.7 AArch64
07-13 08:39:31.954 I/Adreno  (13455): PFP: 0x005ff087, ME: 0x005ff063
07-13 08:39:31.959 I/ConfigStore(13455): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-13 08:39:31.960 I/ConfigStore(13455): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
07-13 08:39:31.962 I/OpenGLRenderer(13455): Initialized EGL, version 1.4
07-13 08:39:31.962 D/OpenGLRenderer(13455): Swap behavior 2
07-13 08:39:32.010 E/RecyclerView(13455): No adapter attached; skipping layout
07-13 08:39:33.457 W/PropertyValuesHolder(13455): Method setPhaseY() with type float not found on target class class b.c.a.a.a.a
07-13 08:40:40.839 W/ListPreference(13455): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
07-13 08:40:43.781 W/ActivityThread(13455): handleWindowVisibility: no activity for token android.os.BinderProxy@a64c2ab
07-13 08:40:43.801 I/ViewRootImpl(13455): CPU Rendering VSync enable = true
07-13 08:40:43.856 D/OpenGLRenderer(13455): endAllActiveAnimators on 0x790dc60500 (RippleDrawable) with handle 0x790dcc8da0
07-13 08:40:44.356 W/ActivityThread(13455): handleWindowVisibility: no activity for token android.os.BinderProxy@c48403c
07-13 08:40:44.395 W/ActivityThread(13455): handleWindowVisibility: no activity for token android.os.BinderProxy@33a306c
07-13 08:40:44.420 I/ViewRootImpl(13455): CPU Rendering VSync enable = true
07-13 08:40:47.366 I/ViewRootImpl(13455): CPU Rendering VSync enable = true
07-13 08:40:47.427 I/ViewRootImpl(13455): CPU Rendering VSync enable = true
07-13 08:41:03.893 I/ViewRootImpl(13455): CPU Rendering VSync enable = true
07-13 08:41:04.161 D/AndroidRuntime(13455): Shutting down VM
07-13 08:41:04.161 E/AndroidRuntime(13455): FATAL EXCEPTION: main
07-13 08:41:04.161 E/AndroidRuntime(13455): Process: xyz.hisname.fireflyiii, PID: 13455
07-13 08:41:04.161 E/AndroidRuntime(13455): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter value
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at xyz.hisname.fireflyiii.a.a.b.a.f(Unknown Source:2)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:4)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:1)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at i.l.run(DefaultCallAdapterFactory.java:3)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at android.os.Handler.handleCallback(Handler.java:873)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at android.os.Looper.loop(Looper.java:193)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at java.lang.reflect.Method.invoke(Native Method)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-13 08:41:04.161 E/AndroidRuntime(13455): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
07-13 08:41:04.162 E/ACRA    (13455): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
07-13 08:41:04.162 E/ACRA    (13455): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter value
07-13 08:41:04.162 E/ACRA    (13455): 	at xyz.hisname.fireflyiii.a.a.b.a.f(Unknown Source:2)
07-13 08:41:04.162 E/ACRA    (13455): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:4)
07-13 08:41:04.162 E/ACRA    (13455): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:1)
07-13 08:41:04.162 E/ACRA    (13455): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
07-13 08:41:04.162 E/ACRA    (13455): 	at i.l.run(DefaultCallAdapterFactory.java:3)
07-13 08:41:04.162 E/ACRA    (13455): 	at android.os.Handler.handleCallback(Handler.java:873)
07-13 08:41:04.162 E/ACRA    (13455): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 08:41:04.162 E/ACRA    (13455): 	at android.os.Looper.loop(Looper.java:193)
07-13 08:41:04.162 E/ACRA    (13455): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-13 08:41:04.162 E/ACRA    (13455): 	at java.lang.reflect.Method.invoke(Native Method)
07-13 08:41:04.162 E/ACRA    (13455): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-13 08:41:04.162 E/ACRA    (13455): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
IS_SILENT=false
USER_CRASH_DATE=2019-07-13T08:41:04.168+02:00
```

```
REPORT_ID=932c1dc4-bfbd-46ee-a883-f2d379b59229
APP_VERSION_NAME=1.3.6
PHONE_MODEL=Redmi Note 5
BRAND=Xiaomi
PRODUCT=whyred
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter value
	at xyz.hisname.fireflyiii.a.a.b.a.f(Unknown Source:2)
	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:4)
	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:1)
	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
	at i.l.run(DefaultCallAdapterFactory.java:3)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

LOGCAT=--------- beginning of main
07-13 08:29:27.747 E/name.fireflyii( 9999): Not starting debugger since process cannot load the jdwp agent.
07-13 08:29:27.848 I/MultiDex( 9999): VM with version 2.1.0 has multidex support
07-13 08:29:27.848 I/MultiDex( 9999): Installing application
07-13 08:29:27.848 I/MultiDex( 9999): VM has multidex support, MultiDex support library is disabled.
07-13 08:29:27.919 I/ACRA    ( 9999): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
07-13 08:29:27.948 W/ActivityThread( 9999): handleWindowVisibility: no activity for token android.os.BinderProxy@9837ce0
07-13 08:29:27.996 D/OpenGLRenderer( 9999): Skia GL Pipeline
07-13 08:29:28.000 I/ViewRootImpl( 9999): CPU Rendering VSync enable = true
07-13 08:29:28.039 I/Adreno  ( 9999): QUALCOMM build                   : 9128d71, Ib33d3e8e13
07-13 08:29:28.039 I/Adreno  ( 9999): Build Date                       : 10/23/18
07-13 08:29:28.039 I/Adreno  ( 9999): OpenGL ES Shader Compiler Version: EV031.25.03.01
07-13 08:29:28.039 I/Adreno  ( 9999): Local Branch                     : 
07-13 08:29:28.039 I/Adreno  ( 9999): Remote Branch                    : 
07-13 08:29:28.039 I/Adreno  ( 9999): Remote Branch                    : 
07-13 08:29:28.039 I/Adreno  ( 9999): Reconstruct Branch               : 
07-13 08:29:28.039 I/Adreno  ( 9999): Build Config                     : S L 6.0.7 AArch64
07-13 08:29:28.044 I/Adreno  ( 9999): PFP: 0x005ff087, ME: 0x005ff063
07-13 08:29:28.050 I/ConfigStore( 9999): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-13 08:29:28.050 I/ConfigStore( 9999): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
07-13 08:29:28.051 I/OpenGLRenderer( 9999): Initialized EGL, version 1.4
07-13 08:29:28.051 D/OpenGLRenderer( 9999): Swap behavior 2
07-13 08:36:28.504 I/ViewRootImpl( 9999): CPU Rendering VSync enable = true
07-13 08:36:28.564 I/ViewRootImpl( 9999): CPU Rendering VSync enable = true
07-13 08:36:50.921 D/NetworkSecurityConfig( 9999): Using Network Security Config from resource network_security_config debugBuild: false
07-13 08:36:51.747 I/ViewRootImpl( 9999): CPU Rendering VSync enable = true
07-13 08:36:52.297 D/AndroidRuntime( 9999): Shutting down VM
--------- beginning of crash
07-13 08:36:52.298 E/AndroidRuntime( 9999): FATAL EXCEPTION: main
07-13 08:36:52.298 E/AndroidRuntime( 9999): Process: xyz.hisname.fireflyiii, PID: 9999
07-13 08:36:52.298 E/AndroidRuntime( 9999): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter value
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at xyz.hisname.fireflyiii.a.a.b.a.f(Unknown Source:2)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:4)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:1)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at i.l.run(DefaultCallAdapterFactory.java:3)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at android.os.Handler.handleCallback(Handler.java:873)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at android.os.Looper.loop(Looper.java:193)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at java.lang.reflect.Method.invoke(Native Method)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-13 08:36:52.298 E/AndroidRuntime( 9999): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
07-13 08:36:52.299 E/ACRA    ( 9999): ACRA caught a IllegalArgumentException for xyz.hisname.fireflyiii
07-13 08:36:52.299 E/ACRA    ( 9999): java.lang.IllegalArgumentException: Parameter specified as non-null is null: method d.f.b.j.b, parameter value
07-13 08:36:52.299 E/ACRA    ( 9999): 	at xyz.hisname.fireflyiii.a.a.b.a.f(Unknown Source:2)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:4)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at xyz.hisname.fireflyiii.b.l.a.a(UserInfoViewModel.kt:1)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at i.l.run(DefaultCallAdapterFactory.java:3)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at android.os.Handler.handleCallback(Handler.java:873)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at android.os.Looper.loop(Looper.java:193)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at java.lang.reflect.Method.invoke(Native Method)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-13 08:36:52.299 E/ACRA    ( 9999): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

IS_SILENT=false
USER_CRASH_DATE=2019-07-13T08:36:52.313+02:00
```

**Comment by emansih** [comment]
That's a really weird bug you have there. Do you have owner or email displayed in your navigation drawer?


![](https://user-images.githubusercontent.com/5896415/61168947-9080b480-a588-11e9-8574-86574e6df899.jpg)

**Comment by dIELERx** [comment]
Just the email is displayed.

**Comment by emansih** [comment]
Ah, I have never tested such a use case before since I'm using a single user Firefly installation. This bug occurs because you are not an owner of a Firefly III installation.

**Comment by dIELERx** [comment]
Ah ok understand. Maybe I should have mentioned it, that I enabled multi user instance.

As a few more people are going to use my Firefly instance and your App, I am trying to test as much as possible. I hope thats ok for you ;)

**Comment by emansih** [comment]
Fixed. https://github.com/emansih/FireflyMobile/commit/8fb547fc7adfcfdf93120371b3da2e1dc2a562a3
