### ISSUE TITLE
App Crash: Open PDF Attachement

### ISSUE THREAD

**Issue by dIELERx** [emansih/FireflyMobile#54]
**Firefly III Server Version:** 4.7.1.7

**Firefly III Mobile Version:** 1.3.5

**Android Version:**  Android 9

**Device Information:**  

- BRAND: Xiaomi 
- MODEL: Redmi Note 5
--------------------------------------

## Expected Behavior
Open the attached PDF

## Current Behavior
When I try to open a PDF attached to a booking, the App constantly crashes. I was not able to open a PDF.
## Steps to Reproduce
Use the Webinterface and attach a PDF to a booking or upload it via App. Afterwards open this booking inside the App and try to open the attachement.

```
REPORT_ID=c139c1b5-48c6-4521-8f6e-6bf208435a09
APP_VERSION_NAME=1.3.5
PHONE_MODEL=Redmi Note 5
BRAND=Xiaomi
PRODUCT=whyred
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=kotlinx.coroutines.A: Exception in completion handler InvokeOnCompletion[na@6145f6] for Ga{Completed}@effedf7
	at kotlinx.coroutines.va.a(JobSupport.kt:52)
	at kotlinx.coroutines.va.b(JobSupport.kt:6)
	at kotlinx.coroutines.va.a(JobSupport.kt:95)
	at kotlinx.coroutines.va.b(JobSupport.kt:38)
	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
	at d.c.b.a.a.a(ContinuationImpl.kt:10)
	at kotlinx.coroutines.X.run(Dispatched.kt:15)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)
Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at xyz.hisname.fireflyiii.util.f.a(FileUtils.kt:20)
	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:4)
	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:1)
	at kotlinx.coroutines.na.b(JobSupport.kt:1)
	at kotlinx.coroutines.va.a(JobSupport.kt:51)
	... 9 more

LOGCAT=07-12 22:45:31.360 E/RecyclerView(28331): No adapter attached; skipping layout
07-12 22:45:32.768 D/OpenGLRenderer(28331): endAllActiveAnimators on 0x778b874800 (RippleDrawable) with handle 0x778dd65a00
07-12 22:45:32.776 I/ViewRootImpl(28331): CPU Rendering VSync enable = true
07-12 22:45:33.302 D/OpenGLRenderer(28331): endAllActiveAnimators on 0x778b873900 (RippleDrawable) with handle 0x778dc57380
07-12 22:45:33.328 I/ViewRootImpl(28331): CPU Rendering VSync enable = true
07-12 22:45:33.707 D/OpenGLRenderer(28331): endAllActiveAnimators on 0x778b81cb00 (RippleDrawable) with handle 0x778dcf3840
07-12 22:45:33.723 I/ViewRootImpl(28331): CPU Rendering VSync enable = true
07-12 22:45:35.222 E/RecyclerView(28331): No adapter attached; skipping layout
07-12 22:45:43.145 E/RecyclerView(28331): No adapter attached; skipping layout
07-12 22:45:43.145 E/RecyclerView(28331): No adapter attached; skipping layout
07-12 22:45:44.938 E/RecyclerView(28331): No adapter attached; skipping layout
07-12 22:54:34.048 W/ActivityThread(28331): handleWindowVisibility: no activity for token android.os.BinderProxy@4cdfdd5
07-12 22:54:34.106 I/MaterialDrawer(28331): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-12 22:54:34.168 I/ViewRootImpl(28331): CPU Rendering VSync enable = true
07-12 22:54:34.230 E/RecyclerView(28331): No adapter attached; skipping layout
07-12 22:54:50.857 E/name.fireflyii(29297): Not starting debugger since process cannot load the jdwp agent.
07-12 22:54:50.902 I/MultiDex(29297): VM with version 2.1.0 has multidex support
07-12 22:54:50.902 I/MultiDex(29297): Installing application
07-12 22:54:50.902 I/MultiDex(29297): VM has multidex support, MultiDex support library is disabled.
07-12 22:54:50.965 I/ACRA    (29297): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
07-12 22:54:51.044 D/NetworkSecurityConfig(29297): No Network Security Config specified, using platform default
07-12 22:54:51.052 I/MaterialDrawer(29297): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-12 22:54:51.273 D/OpenGLRenderer(29297): Skia GL Pipeline
07-12 22:54:51.275 I/ViewRootImpl(29297): CPU Rendering VSync enable = true
07-12 22:54:51.432 I/Adreno  (29297): QUALCOMM build                   : 9128d71, Ib33d3e8e13
07-12 22:54:51.432 I/Adreno  (29297): Build Date                       : 10/23/18
07-12 22:54:51.432 I/Adreno  (29297): OpenGL ES Shader Compiler Version: EV031.25.03.01
07-12 22:54:51.432 I/Adreno  (29297): Local Branch                     : 
07-12 22:54:51.432 I/Adreno  (29297): Remote Branch                    : 
07-12 22:54:51.432 I/Adreno  (29297): Remote Branch                    : 
07-12 22:54:51.432 I/Adreno  (29297): Reconstruct Branch               : 
07-12 22:54:51.432 I/Adreno  (29297): Build Config                     : S L 6.0.7 AArch64
07-12 22:54:51.438 I/Adreno  (29297): PFP: 0x005ff087, ME: 0x005ff063
07-12 22:54:51.443 I/ConfigStore(29297): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-12 22:54:51.443 I/ConfigStore(29297): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
07-12 22:54:51.445 I/OpenGLRenderer(29297): Initialized EGL, version 1.4
07-12 22:54:51.445 D/OpenGLRenderer(29297): Swap behavior 2
07-12 22:54:51.497 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:51.647 I/MaterialDrawer(29297): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-12 22:54:51.757 I/ViewRootImpl(29297): CPU Rendering VSync enable = true
07-12 22:54:51.809 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:52.527 W/PropertyValuesHolder(29297): Method setPhaseY() with type float not found on target class class b.c.a.a.a.a
07-12 22:54:56.970 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:57.059 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:57.242 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.021 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.044 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.060 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.077 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.210 I/chatty  (29297): uid=10274(xyz.hisname.fireflyiii) identical 8 lines
07-12 22:54:58.226 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.259 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.375 I/chatty  (29297): uid=10274(xyz.hisname.fireflyiii) identical 7 lines
07-12 22:54:58.393 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.409 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.425 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.442 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.459 I/chatty  (29297): uid=10274(xyz.hisname.fireflyiii) identical 1 line
07-12 22:54:58.475 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:58.742 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:54:59.292 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:00.359 I/chatty  (29297): uid=10274(xyz.hisname.fireflyiii) identical 44 lines
07-12 22:55:00.376 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:01.778 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:01.859 I/chatty  (29297): uid=10274(xyz.hisname.fireflyiii) identical 1 line
07-12 22:55:02.042 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:02.820 I/TextInputLayout(29297): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 22:55:02.868 I/chatty  (29297): uid=10274(xyz.hisname.fireflyiii) identical 4 lines
07-12 22:55:02.871 I/TextInputLayout(29297): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 22:55:12.901 I/ViewRootImpl(29297): CPU Rendering VSync enable = true
07-12 22:55:14.050 D/OpenGLRenderer(29297): endAllActiveAnimators on 0x77a5959000 (DropDownListView) with handle 0x778a543ea0
07-12 22:55:15.328 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:15.333 I/ViewRootImpl(29297): CPU Rendering VSync enable = true
07-12 22:55:17.998 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:24.555 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:30.224 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:30.224 E/RecyclerView(29297): No adapter attached; skipping layout
07-12 22:55:32.101 E/ACRA    (29297): ACRA caught a A for xyz.hisname.fireflyiii
07-12 22:55:32.101 E/ACRA    (29297): kotlinx.coroutines.A: Exception in completion handler InvokeOnCompletion[na@6145f6] for Ga{Completed}@effedf7
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.va.a(JobSupport.kt:52)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.va.b(JobSupport.kt:6)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.va.a(JobSupport.kt:95)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.va.b(JobSupport.kt:38)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
07-12 22:55:32.101 E/ACRA    (29297): 	at d.c.b.a.a.a(ContinuationImpl.kt:10)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.X.run(Dispatched.kt:15)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)
07-12 22:55:32.101 E/ACRA    (29297): Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
07-12 22:55:32.101 E/ACRA    (29297): 	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
07-12 22:55:32.101 E/ACRA    (29297): 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
07-12 22:55:32.101 E/ACRA    (29297): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
07-12 22:55:32.101 E/ACRA    (29297): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
07-12 22:55:32.101 E/ACRA    (29297): 	at xyz.hisname.fireflyiii.util.f.a(FileUtils.kt:20)
07-12 22:55:32.101 E/ACRA    (29297): 	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:4)
07-12 22:55:32.101 E/ACRA    (29297): 	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:1)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.na.b(JobSupport.kt:1)
07-12 22:55:32.101 E/ACRA    (29297): 	at kotlinx.coroutines.va.a(JobSupport.kt:51)
07-12 22:55:32.101 E/ACRA    (29297): 	... 9 more
IS_SILENT=false
USER_CRASH_DATE=2019-07-12T22:55:32.105+02:00
```
Another crash. This time the attachement was an image uploaded via app.
```
REPORT_ID=1ea838dc-9e98-496d-9b16-63e67a7ad59c
APP_VERSION_NAME=1.3.5
PHONE_MODEL=Redmi Note 5
BRAND=Xiaomi
PRODUCT=whyred
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=kotlinx.coroutines.A: Exception in completion handler InvokeOnCompletion[na@adb3366] for Ga{Completed}@fe226a7
	at kotlinx.coroutines.va.a(JobSupport.kt:52)
	at kotlinx.coroutines.va.b(JobSupport.kt:6)
	at kotlinx.coroutines.va.a(JobSupport.kt:95)
	at kotlinx.coroutines.va.b(JobSupport.kt:38)
	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
	at d.c.b.a.a.a(ContinuationImpl.kt:10)
	at kotlinx.coroutines.X.run(Dispatched.kt:15)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)
Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
	at xyz.hisname.fireflyiii.util.f.a(FileUtils.kt:20)
	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:4)
	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:1)
	at kotlinx.coroutines.na.b(JobSupport.kt:1)
	at kotlinx.coroutines.va.a(JobSupport.kt:51)
	... 9 more

LOGCAT=07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.va.b(JobSupport.kt:6)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.va.a(JobSupport.kt:95)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.va.b(JobSupport.kt:38)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
07-12 23:01:57.912 E/ACRA    (29721): 	at d.c.b.a.a.a(ContinuationImpl.kt:10)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.X.run(Dispatched.kt:15)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)
07-12 23:01:57.912 E/ACRA    (29721): Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
07-12 23:01:57.912 E/ACRA    (29721): 	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
07-12 23:01:57.912 E/ACRA    (29721): 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
07-12 23:01:57.912 E/ACRA    (29721): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
07-12 23:01:57.912 E/ACRA    (29721): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
07-12 23:01:57.912 E/ACRA    (29721): 	at xyz.hisname.fireflyiii.util.f.a(FileUtils.kt:20)
07-12 23:01:57.912 E/ACRA    (29721): 	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:4)
07-12 23:01:57.912 E/ACRA    (29721): 	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:1)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.na.b(JobSupport.kt:1)
07-12 23:01:57.912 E/ACRA    (29721): 	at kotlinx.coroutines.va.a(JobSupport.kt:51)
07-12 23:01:57.912 E/ACRA    (29721): 	... 9 more
07-12 23:01:58.050 I/ACRA    (29721): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2019-07-12T23:01:57.918+02:00.stacktrace
07-12 23:01:58.085 I/Process (29721): Sending signal. PID: 29721 SIG: 9
07-12 23:03:43.482 E/name.fireflyii(30177): Not starting debugger since process cannot load the jdwp agent.
07-12 23:03:43.530 I/MultiDex(30177): VM with version 2.1.0 has multidex support
07-12 23:03:43.530 I/MultiDex(30177): Installing application
07-12 23:03:43.530 I/MultiDex(30177): VM has multidex support, MultiDex support library is disabled.
07-12 23:03:43.609 I/ACRA    (30177): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
07-12 23:03:43.689 D/NetworkSecurityConfig(30177): No Network Security Config specified, using platform default
07-12 23:03:43.697 I/MaterialDrawer(30177): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-12 23:03:43.906 D/OpenGLRenderer(30177): Skia GL Pipeline
07-12 23:03:43.908 I/ViewRootImpl(30177): CPU Rendering VSync enable = true
07-12 23:03:44.060 I/Adreno  (30177): QUALCOMM build                   : 9128d71, Ib33d3e8e13
07-12 23:03:44.060 I/Adreno  (30177): Build Date                       : 10/23/18
07-12 23:03:44.060 I/Adreno  (30177): OpenGL ES Shader Compiler Version: EV031.25.03.01
07-12 23:03:44.060 I/Adreno  (30177): Local Branch                     : 
07-12 23:03:44.060 I/Adreno  (30177): Remote Branch                    : 
07-12 23:03:44.060 I/Adreno  (30177): Remote Branch                    : 
07-12 23:03:44.060 I/Adreno  (30177): Reconstruct Branch               : 
07-12 23:03:44.061 I/Adreno  (30177): Build Config                     : S L 6.0.7 AArch64
07-12 23:03:44.070 I/Adreno  (30177): PFP: 0x005ff087, ME: 0x005ff063
07-12 23:03:44.074 I/ConfigStore(30177): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-12 23:03:44.074 I/ConfigStore(30177): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
07-12 23:03:44.078 I/OpenGLRenderer(30177): Initialized EGL, version 1.4
07-12 23:03:44.079 D/OpenGLRenderer(30177): Swap behavior 2
07-12 23:03:44.123 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:03:44.255 I/MaterialDrawer(30177): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-12 23:03:44.383 I/ViewRootImpl(30177): CPU Rendering VSync enable = true
07-12 23:03:44.443 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:03:45.606 W/PropertyValuesHolder(30177): Method setPhaseY() with type float not found on target class class b.c.a.a.a.a
07-12 23:03:46.512 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:03:48.465 W/ActivityThread(30177): handleWindowVisibility: no activity for token android.os.BinderProxy@18112cc
07-12 23:03:48.549 I/TextInputLayout(30177): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 23:03:48.604 I/chatty  (30177): uid=10274(xyz.hisname.fireflyiii) identical 4 lines
07-12 23:03:48.609 I/TextInputLayout(30177): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 23:03:48.641 I/ViewRootImpl(30177): CPU Rendering VSync enable = true
07-12 23:03:55.850 I/TextInputLayout(30177): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 23:03:58.551 I/chatty  (30177): uid=10274(xyz.hisname.fireflyiii) identical 10 lines
07-12 23:03:58.556 I/TextInputLayout(30177): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 23:04:01.564 I/TextInputLayout(30177): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 23:04:03.287 I/chatty  (30177): uid=10274(xyz.hisname.fireflyiii) identical 10 lines
07-12 23:04:03.290 I/TextInputLayout(30177): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 23:04:12.230 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:04:13.649 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:04:13.649 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:04:16.104 I/ViewRootImpl(30177): CPU Rendering VSync enable = true
07-12 23:04:16.857 I/TextInputLayout(30177): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 23:04:16.882 I/chatty  (30177): uid=10274(xyz.hisname.fireflyiii) identical 4 lines
07-12 23:04:16.885 I/TextInputLayout(30177): EditText added is not a TextInputEditText. Please switch to using that class instead.
07-12 23:04:27.434 I/ViewRootImpl(30177): CPU Rendering VSync enable = true
07-12 23:04:27.456 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:04:28.710 W/InputEventReceiver(30177): Attempted to finish an input event but the input event receiver has already been disposed.
07-12 23:04:33.928 I/ViewRootImpl(30177): CPU Rendering VSync enable = true
07-12 23:04:33.995 I/WM-WorkerWrapper(30177): Worker result SUCCESS for Work [ id=67f06307-43cb-4660-8ede-c56938df4f8b, tags={ attachment_worker, xyz.hisname.fireflyiii.workers.transaction.AttachmentWorker } ]
07-12 23:04:39.304 I/ViewRootImpl(30177): CPU Rendering VSync enable = true
07-12 23:04:39.347 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:04:40.999 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:04:40.999 E/RecyclerView(30177): No adapter attached; skipping layout
07-12 23:04:42.954 E/ACRA    (30177): ACRA caught a A for xyz.hisname.fireflyiii
07-12 23:04:42.954 E/ACRA    (30177): kotlinx.coroutines.A: Exception in completion handler InvokeOnCompletion[na@adb3366] for Ga{Completed}@fe226a7
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.va.a(JobSupport.kt:52)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.va.b(JobSupport.kt:6)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.va.a(JobSupport.kt:95)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.va.b(JobSupport.kt:38)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
07-12 23:04:42.954 E/ACRA    (30177): 	at d.c.b.a.a.a(ContinuationImpl.kt:10)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.X.run(Dispatched.kt:15)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:31)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.c.a.a(CoroutineScheduler.kt:4)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.c.a$b.run(CoroutineScheduler.kt:9)
07-12 23:04:42.954 E/ACRA    (30177): Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
07-12 23:04:42.954 E/ACRA    (30177): 	at android.app.ContextImpl.startActivity(ContextImpl.java:912)
07-12 23:04:42.954 E/ACRA    (30177): 	at android.app.ContextImpl.startActivity(ContextImpl.java:888)
07-12 23:04:42.954 E/ACRA    (30177): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
07-12 23:04:42.954 E/ACRA    (30177): 	at android.content.ContextWrapper.startActivity(ContextWrapper.java:379)
07-12 23:04:42.954 E/ACRA    (30177): 	at xyz.hisname.fireflyiii.util.f.a(FileUtils.kt:20)
07-12 23:04:42.954 E/ACRA    (30177): 	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:4)
07-12 23:04:42.954 E/ACRA    (30177): 	at xyz.hisname.fireflyiii.b.b.d.a(AttachmentViewModel.kt:1)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.na.b(JobSupport.kt:1)
07-12 23:04:42.954 E/ACRA    (30177): 	at kotlinx.coroutines.va.a(JobSupport.kt:51)
07-12 23:04:42.954 E/ACRA    (30177): 	... 9 more
IS_SILENT=false
USER_CRASH_DATE=2019-07-12T23:04:42.958+02:00
```

I hope those infos help. If you need any further information, just let me know.

Thanks

**Comment by emansih** [comment]
Thanks for your reports. Appreciate it. A new build will be rolling out soon

**Comment by emansih** [comment]
Fix in latest release.
