### ISSUE TITLE
App Crash: Edit Piggy Banks

### ISSUE THREAD

**Issue by dIELERx** [emansih/FireflyMobile#55]
**Firefly III Server Version:** 4.7.1.7

**Firefly III Mobile Version:** 1.3.5

**Android Version:**  Android 9

**Device Information:**  

- BRAND: Xiaomi 
- MODEL: Redmi Note 5
--------------------------------------

## Expected Behavior
Change Amount and Name of Piggy.

## Current Behavior
1. Editing a Piggy Bank leads to a crash. I created a few different piggy banks and the app crashs on each of them.
2. And there is one more thing i noticed. When I open one piggy bank, I am not able to return to the overview / click the return arrow. I am still able to scroll inside the piggy bank and open the action menu, but I am not able to go back / return.

## Steps to Reproduce
1. First create a piggy bank if you did not before. Then open one piggy bank and click on "edit". Afterwards the app crashs.
2. Just open one piggy bank and try to return to the overview by clicking the Android return button or the "return arrow". 

```
REPORT_ID=f3e5d74f-79a4-4f8b-aae5-547795e9ba30
APP_VERSION_NAME=1.3.5
PHONE_MODEL=Redmi Note 5
BRAND=Xiaomi
PRODUCT=whyred
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=d.t: lateinit property accountAdapter has not been initialized
	at xyz.hisname.fireflyiii.ui.i.o.a(AddPiggyFragment.kt:1)
	at xyz.hisname.fireflyiii.ui.i.b.a(LiveData.kt:3)
	at androidx.lifecycle.LiveData.b(LiveData.java:6)
	at androidx.lifecycle.LiveData.a(LiveData.java:8)
	at androidx.lifecycle.LiveData.b(LiveData.java:14)
	at androidx.lifecycle.v.b(MutableLiveData.java:1)
	at androidx.lifecycle.s.run(LiveData.java:5)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6740)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)

LOGCAT=07-12 23:12:05.654 E/AndroidRuntime(31793): 	at xyz.hisname.fireflyiii.ui.i.b.a(LiveData.kt:3)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at androidx.lifecycle.LiveData.a(LiveData.java:8)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at androidx.lifecycle.LiveData.b(LiveData.java:14)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at androidx.lifecycle.v.b(MutableLiveData.java:1)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at androidx.lifecycle.s.run(LiveData.java:5)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at android.os.Handler.handleCallback(Handler.java:873)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at android.os.Looper.loop(Looper.java:193)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-12 23:12:05.654 E/AndroidRuntime(31793): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
07-12 23:12:05.654 E/ACRA    (31793): ACRA caught a t for xyz.hisname.fireflyiii
07-12 23:12:05.654 E/ACRA    (31793): d.t: lateinit property accountAdapter has not been initialized
07-12 23:12:05.654 E/ACRA    (31793): 	at xyz.hisname.fireflyiii.ui.i.o.a(AddPiggyFragment.kt:1)
07-12 23:12:05.654 E/ACRA    (31793): 	at xyz.hisname.fireflyiii.ui.i.b.a(LiveData.kt:3)
07-12 23:12:05.654 E/ACRA    (31793): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
07-12 23:12:05.654 E/ACRA    (31793): 	at androidx.lifecycle.LiveData.a(LiveData.java:8)
07-12 23:12:05.654 E/ACRA    (31793): 	at androidx.lifecycle.LiveData.b(LiveData.java:14)
07-12 23:12:05.654 E/ACRA    (31793): 	at androidx.lifecycle.v.b(MutableLiveData.java:1)
07-12 23:12:05.654 E/ACRA    (31793): 	at androidx.lifecycle.s.run(LiveData.java:5)
07-12 23:12:05.654 E/ACRA    (31793): 	at android.os.Handler.handleCallback(Handler.java:873)
07-12 23:12:05.654 E/ACRA    (31793): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 23:12:05.654 E/ACRA    (31793): 	at android.os.Looper.loop(Looper.java:193)
07-12 23:12:05.654 E/ACRA    (31793): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-12 23:12:05.654 E/ACRA    (31793): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 23:12:05.654 E/ACRA    (31793): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-12 23:12:05.654 E/ACRA    (31793): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
07-12 23:12:05.686 I/ACRA    (31793): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2019-07-12T23:12:05.667+02:00.stacktrace
07-12 23:12:05.714 I/Process (31793): Sending signal. PID: 31793 SIG: 9
07-12 23:12:07.504 E/name.fireflyii(31996): Not starting debugger since process cannot load the jdwp agent.
07-12 23:12:07.566 I/MultiDex(31996): VM with version 2.1.0 has multidex support
07-12 23:12:07.566 I/MultiDex(31996): Installing application
07-12 23:12:07.566 I/MultiDex(31996): VM has multidex support, MultiDex support library is disabled.
07-12 23:12:07.644 I/ACRA    (31996): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
07-12 23:12:07.725 D/NetworkSecurityConfig(31996): No Network Security Config specified, using platform default
07-12 23:12:07.734 I/MaterialDrawer(31996): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-12 23:12:07.953 D/OpenGLRenderer(31996): Skia GL Pipeline
07-12 23:12:07.954 I/ViewRootImpl(31996): CPU Rendering VSync enable = true
07-12 23:12:08.110 I/Adreno  (31996): QUALCOMM build                   : 9128d71, Ib33d3e8e13
07-12 23:12:08.110 I/Adreno  (31996): Build Date                       : 10/23/18
07-12 23:12:08.110 I/Adreno  (31996): OpenGL ES Shader Compiler Version: EV031.25.03.01
07-12 23:12:08.110 I/Adreno  (31996): Local Branch                     : 
07-12 23:12:08.110 I/Adreno  (31996): Remote Branch                    : 
07-12 23:12:08.110 I/Adreno  (31996): Remote Branch                    : 
07-12 23:12:08.110 I/Adreno  (31996): Reconstruct Branch               : 
07-12 23:12:08.110 I/Adreno  (31996): Build Config                     : S L 6.0.7 AArch64
07-12 23:12:08.115 I/Adreno  (31996): PFP: 0x005ff087, ME: 0x005ff063
07-12 23:12:08.119 I/ConfigStore(31996): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
07-12 23:12:08.120 I/ConfigStore(31996): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
07-12 23:12:08.121 I/OpenGLRenderer(31996): Initialized EGL, version 1.4
07-12 23:12:08.121 D/OpenGLRenderer(31996): Swap behavior 2
07-12 23:12:08.167 E/RecyclerView(31996): No adapter attached; skipping layout
07-12 23:12:08.305 I/MaterialDrawer(31996): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
07-12 23:12:08.432 I/ViewRootImpl(31996): CPU Rendering VSync enable = true
07-12 23:12:08.489 E/RecyclerView(31996): No adapter attached; skipping layout
07-12 23:12:09.567 W/PropertyValuesHolder(31996): Method setPhaseY() with type float not found on target class class b.c.a.a.a.a
07-12 23:12:11.689 E/RecyclerView(31996): No adapter attached; skipping layout
07-12 23:12:14.681 I/ViewRootImpl(31996): CPU Rendering VSync enable = true
07-12 23:12:20.398 I/ViewRootImpl(31996): CPU Rendering VSync enable = true
07-12 23:12:21.623 I/ViewRootImpl(31996): CPU Rendering VSync enable = true
07-12 23:12:21.826 D/OpenGLRenderer(31996): endAllActiveAnimators on 0x778bee3900 (W$a) with handle 0x778be82d40
07-12 23:12:23.106 D/OpenGLRenderer(31996): endAllActiveAnimators on 0x778bf95d00 (RippleDrawable) with handle 0x778be828c0
07-12 23:12:23.737 I/ViewRootImpl(31996): CPU Rendering VSync enable = true
07-12 23:12:24.410 I/FloatingActionButton(31996): Setting a custom background is not supported.
07-12 23:12:24.489 D/AndroidRuntime(31996): Shutting down VM
07-12 23:12:24.490 E/AndroidRuntime(31996): FATAL EXCEPTION: main
07-12 23:12:24.490 E/AndroidRuntime(31996): Process: xyz.hisname.fireflyiii, PID: 31996
07-12 23:12:24.490 E/AndroidRuntime(31996): d.t: lateinit property accountAdapter has not been initialized
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at xyz.hisname.fireflyiii.ui.i.o.a(AddPiggyFragment.kt:1)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at xyz.hisname.fireflyiii.ui.i.b.a(LiveData.kt:3)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at androidx.lifecycle.LiveData.a(LiveData.java:8)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at androidx.lifecycle.LiveData.b(LiveData.java:14)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at androidx.lifecycle.v.b(MutableLiveData.java:1)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at androidx.lifecycle.s.run(LiveData.java:5)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at android.os.Handler.handleCallback(Handler.java:873)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at android.os.Looper.loop(Looper.java:193)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-12 23:12:24.490 E/AndroidRuntime(31996): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
07-12 23:12:24.490 E/ACRA    (31996): ACRA caught a t for xyz.hisname.fireflyiii
07-12 23:12:24.490 E/ACRA    (31996): d.t: lateinit property accountAdapter has not been initialized
07-12 23:12:24.490 E/ACRA    (31996): 	at xyz.hisname.fireflyiii.ui.i.o.a(AddPiggyFragment.kt:1)
07-12 23:12:24.490 E/ACRA    (31996): 	at xyz.hisname.fireflyiii.ui.i.b.a(LiveData.kt:3)
07-12 23:12:24.490 E/ACRA    (31996): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
07-12 23:12:24.490 E/ACRA    (31996): 	at androidx.lifecycle.LiveData.a(LiveData.java:8)
07-12 23:12:24.490 E/ACRA    (31996): 	at androidx.lifecycle.LiveData.b(LiveData.java:14)
07-12 23:12:24.490 E/ACRA    (31996): 	at androidx.lifecycle.v.b(MutableLiveData.java:1)
07-12 23:12:24.490 E/ACRA    (31996): 	at androidx.lifecycle.s.run(LiveData.java:5)
07-12 23:12:24.490 E/ACRA    (31996): 	at android.os.Handler.handleCallback(Handler.java:873)
07-12 23:12:24.490 E/ACRA    (31996): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-12 23:12:24.490 E/ACRA    (31996): 	at android.os.Looper.loop(Looper.java:193)
07-12 23:12:24.490 E/ACRA    (31996): 	at android.app.ActivityThread.main(ActivityThread.java:6740)
07-12 23:12:24.490 E/ACRA    (31996): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 23:12:24.490 E/ACRA    (31996): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:495)
07-12 23:12:24.490 E/ACRA    (31996): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:859)
IS_SILENT=false
USER_CRASH_DATE=2019-07-12T23:12:24.501+02:00
```

I hope those infos help. If you need any further information, just let me know.

Thanks

**Comment by emansih** [comment]
Oops

**Comment by emansih** [comment]
Fix in latest release.

**Comment by dIELERx** [comment]
Thanks for the quick fix. The App is no more crashing. But I have another problem now. When I open one piggy bank and click **edit** via action menu, I am no more able to save it, because the following message appears: `current amount must be larger than zero`

I am running Version 1.3.6

It does not matter which amount I enter, I always get that error.
![grafik](https://user-images.githubusercontent.com/32218246/61169110-138a1680-a559-11e9-9a00-4f7b7582e102.png)

**Comment by emansih** [comment]
I can't replicate this bug at all.

**Comment by dIELERx** [comment]
hmm strange. This is happening on all my piggy banks. Does not matter if I create a new one or use an existing one.

**Comment by emansih** [comment]
Oh, I can replicate the bug when editing piggy bank. I thought you were talking about adding a new piggy bank

**Comment by emansih** [comment]
It appears to be a bug in Firefly III itself. https://github.com/firefly-iii/firefly-iii/issues/2333
