### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by agilob** [emansih/FireflyMobile#64]
**Firefly III Server Version:**
4.8.0

```
REPORT_ID=9c3b1983-6e38-4520-8a43-41f4e35ef606
APP_VERSION_NAME=1.3.6
PHONE_MODEL=Moto G Play
BRAND=motorola
PRODUCT=harpia_n
ANDROID_VERSION=7.1.1
BUILD_CONFIG=
STACK_TRACE=b.d.c.E: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$a.a(ReflectiveTypeAdapterFactory.java:13)
	at b.d.c.q.a(Gson.java:101)
	at b.d.c.q.a(Gson.java:90)
	at b.d.c.q.a(Gson.java:88)
	at b.d.c.q.a(Gson.java:85)
	at xyz.hisname.fireflyiii.b.g.t.a(CurrencyViewModel.kt:14)
	at xyz.hisname.fireflyiii.b.g.t.a(CurrencyViewModel.kt:1)
	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
	at i.l.run(DefaultCallAdapterFactory.java:3)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6165)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
	at b.d.c.c.b.s(JsonReader.java:5)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$a.a(ReflectiveTypeAdapterFactory.java:4)
	... 15 more

LOGCAT=08-10 08:34:12.529 I/art     (14411): Background partial concurrent mark sweep GC freed 22170(1069KB) AllocSpace objects, 2(40KB) LOS objects, 24% free, 7MB/9MB, paused 3.402ms total 156.403ms
08-10 08:34:12.640 W/Glide   (14411): Load failed for https://images.unsplash.com/photo-1531987428847-95ad50737a07?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&w=1001&q=80 with size [112x112]
08-10 08:34:12.640 W/Glide   (14411): class com.bumptech.glide.load.b.B: Failed to load resource
08-10 08:34:12.640 W/Glide   (14411): There was 1 cause:
08-10 08:34:12.640 W/Glide   (14411): java.net.UnknownHostException(Unable to resolve host "images.unsplash.com": No address associated with hostname)
08-10 08:34:12.640 W/Glide   (14411):  call GlideException#logRootCauses(String) for more detail
08-10 08:34:12.640 W/Glide   (14411):   Cause (1 of 1): class com.bumptech.glide.load.b.B: Fetching data failed, class java.io.InputStream, REMOTE
08-10 08:34:12.640 W/Glide   (14411): There was 1 cause:
08-10 08:34:12.640 W/Glide   (14411): java.net.UnknownHostException(Unable to resolve host "images.unsplash.com": No address associated with hostname)
08-10 08:34:12.640 W/Glide   (14411):  call GlideException#logRootCauses(String) for more detail
08-10 08:34:12.640 W/Glide   (14411):     Cause (1 of 1): class com.bumptech.glide.load.b.B: Fetch failed
08-10 08:34:12.640 W/Glide   (14411): There was 1 cause:
08-10 08:34:12.640 W/Glide   (14411): java.net.UnknownHostException(Unable to resolve host "images.unsplash.com": No address associated with hostname)
08-10 08:34:12.640 W/Glide   (14411):  call GlideException#logRootCauses(String) for more detail
08-10 08:34:12.640 W/Glide   (14411):       Cause (1 of 1): class java.net.UnknownHostException: Unable to resolve host "images.unsplash.com": No address associated with hostname
08-10 08:34:12.641 I/Glide   (14411): Root cause (1 of 1)
08-10 08:34:21.373 E/RecyclerView(14411): No adapter attached; skipping layout
08-10 08:34:21.693 D/AndroidRuntime(14411): Shutting down VM
08-10 08:34:21.704 E/ACRA    (14411): ACRA caught a E for xyz.hisname.fireflyiii
08-10 08:34:21.704 E/ACRA    (14411): b.d.c.E: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
08-10 08:34:21.704 E/ACRA    (14411): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$a.a(ReflectiveTypeAdapterFactory.java:13)
08-10 08:34:21.704 E/ACRA    (14411): 	at b.d.c.q.a(Gson.java:101)
08-10 08:34:21.704 E/ACRA    (14411): 	at b.d.c.q.a(Gson.java:90)
08-10 08:34:21.704 E/ACRA    (14411): 	at b.d.c.q.a(Gson.java:88)
08-10 08:34:21.704 E/ACRA    (14411): 	at b.d.c.q.a(Gson.java:85)
08-10 08:34:21.704 E/ACRA    (14411): 	at xyz.hisname.fireflyiii.b.g.t.a(CurrencyViewModel.kt:14)
08-10 08:34:21.704 E/ACRA    (14411): 	at xyz.hisname.fireflyiii.b.g.t.a(CurrencyViewModel.kt:1)
08-10 08:34:21.704 E/ACRA    (14411): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
08-10 08:34:21.704 E/ACRA    (14411): 	at i.l.run(DefaultCallAdapterFactory.java:3)
08-10 08:34:21.704 E/ACRA    (14411): 	at android.os.Handler.handleCallback(Handler.java:751)
08-10 08:34:21.704 E/ACRA    (14411): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-10 08:34:21.704 E/ACRA    (14411): 	at android.os.Looper.loop(Looper.java:154)
08-10 08:34:21.704 E/ACRA    (14411): 	at android.app.ActivityThread.main(ActivityThread.java:6165)
08-10 08:34:21.704 E/ACRA    (14411): 	at java.lang.reflect.Method.invoke(Native Method)
08-10 08:34:21.704 E/ACRA    (14411): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
08-10 08:34:21.704 E/ACRA    (14411): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
08-10 08:34:21.704 E/ACRA    (14411): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
08-10 08:34:21.704 E/ACRA    (14411): 	at b.d.c.c.b.s(JsonReader.java:5)
08-10 08:34:21.704 E/ACRA    (14411): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$a.a(ReflectiveTypeAdapterFactory.java:4)
08-10 08:34:21.704 E/ACRA    (14411): 	... 15 more
08-10 08:34:21.973 I/Process (14411): Sending signal. PID: 14411 SIG: 9
08-10 08:34:22.140 I/art     (14813): Starting a blocking GC AddRemoveAppImageSpace
08-10 08:34:22.163 W/System  (14813): ClassLoader referenced unknown path: /data/app/xyz.hisname.fireflyiii-2/lib/arm
08-10 08:34:22.219 I/MultiDex(14813): VM with version 2.1.0 has multidex support
08-10 08:34:22.219 I/MultiDex(14813): Installing application
08-10 08:34:22.219 I/MultiDex(14813): VM has multidex support, MultiDex support library is disabled.
08-10 08:34:22.389 I/ACRA    (14813): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2019-08-10T08:34:21.728+01:00.stacktrace
08-10 08:34:22.496 W/art     (14813): Suspending all threads took: 6.345ms
08-10 08:34:25.088 I/art     (14858): Starting a blocking GC AddRemoveAppImageSpace
08-10 08:34:25.094 W/System  (14858): ClassLoader referenced unknown path: /data/app/xyz.hisname.fireflyiii-2/lib/arm
08-10 08:34:25.135 I/MultiDex(14858): VM with version 2.1.0 has multidex support
08-10 08:34:25.135 I/MultiDex(14858): Installing application
08-10 08:34:25.135 I/MultiDex(14858): VM has multidex support, MultiDex support library is disabled.
08-10 08:34:25.246 I/art     (14858): Background sticky concurrent mark sweep GC freed 6824(350KB) AllocSpace objects, 5(152KB) LOS objects, 7% free, 3MB/3MB, paused 9.113ms total 44.869ms
08-10 08:34:25.367 I/ACRA    (14858): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
08-10 08:34:25.505 D/NetworkSecurityConfig(14858): Using Network Security Config from resource network_security_config debugBuild: false
08-10 08:34:25.519 I/MaterialDrawer(14858): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
08-10 08:34:25.582 I/ViewConfigCompat(14858): Could not find method getScaledScrollFactor() on ViewConfiguration
08-10 08:34:25.763 W/art     (14858): Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
08-10 08:34:25.764 W/art     (14858): Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
08-10 08:34:25.764 W/art     (14858): Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
08-10 08:34:25.911 I/art     (14858): Background sticky concurrent mark sweep GC freed 11384(504KB) AllocSpace objects, 3(112KB) LOS objects, 1% free, 5MB/5MB, paused 5.475ms total 38.244ms
08-10 08:34:26.008 I/Adreno-EGL(14858): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.9_RB1__release_AU (I750f7f2fa6)
08-10 08:34:26.008 I/Adreno-EGL(14858): OpenGL ES Shader Compiler Version: XE031.09.00.03
08-10 08:34:26.008 I/Adreno-EGL(14858): Build Date: 02/18/17 Sat
08-10 08:34:26.008 I/Adreno-EGL(14858): Local Branch: 
08-10 08:34:26.008 I/Adreno-EGL(14858): Remote Branch: quic/LA.BR.1.2.9_rb1.12
08-10 08:34:26.008 I/Adreno-EGL(14858): Local Patches: NONE
08-10 08:34:26.008 I/Adreno-EGL(14858): Reconstruct Branch: NOTHING
08-10 08:34:26.011 I/OpenGLRenderer(14858): Initialized EGL, version 1.4
08-10 08:34:26.011 D/OpenGLRenderer(14858): Swap behavior 1
08-10 08:34:26.014 W/RenderThread(14887): type=1400 audit(0.0:435): avc: denied { read } for uid=10136 name="gpuclk" dev="sysfs" ino=11572 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
08-10 08:34:26.014 W/Adreno-ES20(14858): <get_gpu_clk:229>: open failed: errno 13
08-10 08:34:26.058 E/RecyclerView(14858): No adapter attached; skipping layout
08-10 08:34:26.220 I/MaterialDrawer(14858): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
08-10 08:34:26.460 I/Choreographer(14858): Skipped 33 frames!  The application may be doing too much work on its main thread.
08-10 08:34:26.592 E/RecyclerView(14858): No adapter attached; skipping layout
08-10 08:34:26.678 D/AndroidRuntime(14858): Shutting down VM
08-10 08:34:26.685 E/ACRA    (14858): ACRA caught a E for xyz.hisname.fireflyiii
08-10 08:34:26.685 E/ACRA    (14858): b.d.c.E: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
08-10 08:34:26.685 E/ACRA    (14858): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$a.a(ReflectiveTypeAdapterFactory.java:13)
08-10 08:34:26.685 E/ACRA    (14858): 	at b.d.c.q.a(Gson.java:101)
08-10 08:34:26.685 E/ACRA    (14858): 	at b.d.c.q.a(Gson.java:90)
08-10 08:34:26.685 E/ACRA    (14858): 	at b.d.c.q.a(Gson.java:88)
08-10 08:34:26.685 E/ACRA    (14858): 	at b.d.c.q.a(Gson.java:85)
08-10 08:34:26.685 E/ACRA    (14858): 	at xyz.hisname.fireflyiii.b.g.t.a(CurrencyViewModel.kt:14)
08-10 08:34:26.685 E/ACRA    (14858): 	at xyz.hisname.fireflyiii.b.g.t.a(CurrencyViewModel.kt:1)
08-10 08:34:26.685 E/ACRA    (14858): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
08-10 08:34:26.685 E/ACRA    (14858): 	at i.l.run(DefaultCallAdapterFactory.java:3)
08-10 08:34:26.685 E/ACRA    (14858): 	at android.os.Handler.handleCallback(Handler.java:751)
08-10 08:34:26.685 E/ACRA    (14858): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-10 08:34:26.685 E/ACRA    (14858): 	at android.os.Looper.loop(Looper.java:154)
08-10 08:34:26.685 E/ACRA    (14858): 	at android.app.ActivityThread.main(ActivityThread.java:6165)
08-10 08:34:26.685 E/ACRA    (14858): 	at java.lang.reflect.Method.invoke(Native Method)
08-10 08:34:26.685 E/ACRA    (14858): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
08-10 08:34:26.685 E/ACRA    (14858): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
08-10 08:34:26.685 E/ACRA    (14858): Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 4 path $
08-10 08:34:26.685 E/ACRA    (14858): 	at b.d.c.c.b.s(JsonReader.java:5)
08-10 08:34:26.685 E/ACRA    (14858): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$a.a(ReflectiveTypeAdapterFactory.java:4)
08-10 08:34:26.685 E/ACRA    (14858): 	... 15 more
IS_SILENT=false
USER_CRASH_DATE=2019-08-10T08:34:26.697+01:00
```

**Comment by emansih** [comment]
yea....The transactions API has gone through massive updates. I am sorry I do not have the time now to update the app. I will be available close to the end of Aug.

**Comment by emansih** [comment]
Are you able to test the [pre-release](https://github.com/emansih/FireflyMobile/releases/tag/v1.4.0)? Thanks!

**Comment by agilob** [comment]
I'll test it when I can, unfortunately can't do this in the next few days.

**Comment by porjo** [comment]
I've just tested the 1.4.0 pre-release using latest Firefly 4.8.1 server, but it is still crashing.

Here is the crash report:
```
REPORT_ID=669edc53-2166-477c-8de9-2bbc3211640c
APP_VERSION_NAME=1.4.0
PHONE_MODEL=Redmi Note 4
BRAND=Xiaomi
PRODUCT=lineage_mido
ANDROID_VERSION=8.1.0
BUILD_CONFIG=
STACK_TRACE=java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	... 1 more
Caused by: org.json.JSONException: No value for left-to-spend-in-AUD
	at org.json.JSONObject.get(JSONObject.java:392)
	at org.json.JSONObject.getJSONObject(JSONObject.java:612)
	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)
	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)
	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
	at i.l.run(DefaultCallAdapterFactory.java:3)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	... 3 more

LOGCAT=--------- beginning of main
09-10 10:00:44.481 I/MultiDex( 4220): VM with version 2.1.0 has multidex support
09-10 10:00:44.481 I/MultiDex( 4220): Installing application
09-10 10:00:44.481 I/MultiDex( 4220): VM has multidex support, MultiDex support library is disabled.
09-10 10:00:44.629 I/ACRA    ( 4220): Migrating unsent ACRA reports to new file locations
09-10 10:00:44.630 I/ACRA    ( 4220): Migrated 0 unsent reports
09-10 10:00:44.635 I/ACRA    ( 4220): Converting unsent ACRA reports to json
09-10 10:00:44.636 I/ACRA    ( 4220): Converted 0 unsent reports
09-10 10:00:44.636 I/ACRA    ( 4220): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
09-10 10:00:44.691 D/OpenGLRenderer( 4220): HWUI GL Pipeline
09-10 10:00:44.722 I/Adreno  ( 4220): QUALCOMM build                   : 2371bd1, I8ebe47d372
09-10 10:00:44.722 I/Adreno  ( 4220): Build Date                       : 03/12/18
09-10 10:00:44.722 I/Adreno  ( 4220): OpenGL ES Shader Compiler Version: EV031.22.00.01
09-10 10:00:44.722 I/Adreno  ( 4220): Local Branch                     : 
09-10 10:00:44.722 I/Adreno  ( 4220): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r36-rel
09-10 10:00:44.722 I/Adreno  ( 4220): Remote Branch                    : NONE
09-10 10:00:44.722 I/Adreno  ( 4220): Reconstruct Branch               : NOTHING
09-10 10:00:44.733 I/Adreno  ( 4220): PFP: 0x005ff087, ME: 0x005ff063
09-10 10:00:44.744 I/zygote64( 4220): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
09-10 10:00:44.756 I/OpenGLRenderer( 4220): Initialized EGL, version 1.4
09-10 10:00:44.756 D/OpenGLRenderer( 4220): Swap behavior 2
09-10 10:00:45.760 I/zygote64( 4220): Do partial code cache collection, code=21KB, data=30KB
09-10 10:00:45.760 I/zygote64( 4220): After code cache collection, code=21KB, data=30KB
09-10 10:00:45.760 I/zygote64( 4220): Increasing code cache capacity to 128KB
09-10 10:00:52.813 I/zygote64( 4220): Do partial code cache collection, code=55KB, data=54KB
09-10 10:00:52.813 I/zygote64( 4220): After code cache collection, code=55KB, data=54KB
09-10 10:00:52.813 I/zygote64( 4220): Increasing code cache capacity to 256KB
09-10 10:00:54.693 I/zygote64( 4220): Do full code cache collection, code=124KB, data=80KB
09-10 10:00:54.693 I/zygote64( 4220): After code cache collection, code=112KB, data=61KB
09-10 10:00:58.339 I/zygote64( 4220): Do partial code cache collection, code=124KB, data=67KB
09-10 10:00:58.339 I/zygote64( 4220): After code cache collection, code=124KB, data=67KB
09-10 10:00:58.339 I/zygote64( 4220): Increasing code cache capacity to 512KB
09-10 10:02:22.317 D/SelectionMetricsLogger( 4220): Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
09-10 10:03:04.505 D/NetworkSecurityConfig( 4220): Using Network Security Config from resource network_security_config debugBuild: false
09-10 10:03:06.163 I/MaterialDrawer( 4220): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)
09-10 10:03:06.398 I/zygote64( 4220): Do full code cache collection, code=253KB, data=145KB
09-10 10:03:06.398 I/zygote64( 4220): After code cache collection, code=246KB, data=121KB
09-10 10:03:06.434 I/zygote64( 4220): Do partial code cache collection, code=250KB, data=133KB
09-10 10:03:06.435 I/zygote64( 4220): After code cache collection, code=250KB, data=133KB
09-10 10:03:06.435 I/zygote64( 4220): Increasing code cache capacity to 1024KB
09-10 10:03:06.435 I/zygote64( 4220): Deoptimizing void androidx.appcompat.widget.ContentFrameLayout.onMeasure(int, int) due to JIT inline cache
09-10 10:03:06.484 I/zygote64( 4220): Deoptimizing void a.g.j.z.E(android.view.View) due to JIT inline cache
09-10 10:03:06.532 E/RecyclerView( 4220): No adapter attached; skipping layout
09-10 10:03:06.537 I/zygote64( 4220): Deoptimizing void a.e.b.a.i.L() due to JIT inline cache
09-10 10:03:06.538 I/zygote64( 4220): Deoptimizing void a.e.b.a.u.I() due to JIT inline cache
09-10 10:03:06.705 E/RecyclerView( 4220): No adapter attached; skipping layout
09-10 10:03:07.613 D/AndroidRuntime( 4220): Shutting down VM
--------- beginning of crash
09-10 10:03:07.614 E/AndroidRuntime( 4220): FATAL EXCEPTION: main
09-10 10:03:07.614 E/AndroidRuntime( 4220): Process: xyz.hisname.fireflyiii, PID: 4220
09-10 10:03:07.614 E/AndroidRuntime( 4220): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-10 10:03:07.614 E/AndroidRuntime( 4220): Caused by: java.lang.reflect.InvocationTargetException
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at java.lang.reflect.Method.invoke(Native Method)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	... 1 more
09-10 10:03:07.614 E/AndroidRuntime( 4220): Caused by: org.json.JSONException: No value for left-to-spend-in-AUD
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at org.json.JSONObject.get(JSONObject.java:392)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at org.json.JSONObject.getJSONObject(JSONObject.java:612)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at i.l.run(DefaultCallAdapterFactory.java:3)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at android.os.Handler.handleCallback(Handler.java:790)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at android.os.Looper.loop(Looper.java:164)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-10 10:03:07.614 E/AndroidRuntime( 4220): 	... 3 more
09-10 10:03:07.614 E/ACRA    ( 4220): ACRA caught a RuntimeException for xyz.hisname.fireflyiii
09-10 10:03:07.614 E/ACRA    ( 4220): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
09-10 10:03:07.614 E/ACRA    ( 4220): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:450)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
09-10 10:03:07.614 E/ACRA    ( 4220): Caused by: java.lang.reflect.InvocationTargetException
09-10 10:03:07.614 E/ACRA    ( 4220): 	at java.lang.reflect.Method.invoke(Native Method)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
09-10 10:03:07.614 E/ACRA    ( 4220): 	... 1 more
09-10 10:03:07.614 E/ACRA    ( 4220): Caused by: org.json.JSONException: No value for left-to-spend-in-AUD
09-10 10:03:07.614 E/ACRA    ( 4220): 	at org.json.JSONObject.get(JSONObject.java:392)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at org.json.JSONObject.getJSONObject(JSONObject.java:612)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at i.l.run(DefaultCallAdapterFactory.java:3)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at android.os.Handler.handleCallback(Handler.java:790)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at android.os.Looper.loop(Looper.java:164)
09-10 10:03:07.614 E/ACRA    ( 4220): 	at android.app.ActivityThread.main(ActivityThread.java:6494)
09-10 10:03:07.614 E/ACRA    ( 4220): 	... 3 more

IS_SILENT=false
USER_CRASH_DATE=2019-09-10T10:03:07.632+10:00
```

**Comment by emansih** [comment]
I would need some information. Look at your dashboard, does it have a "Left To Spend" category at the top in AUD?

**Comment by porjo** [comment]
> I would need some information. Look at your dashboard, does it have a "Left To Spend" category at the top in AUD?

Yes it does

**Comment by emansih** [comment]
Are you comfortable using the command line?

**Comment by porjo** [comment]
Yes, I can do command line. I'm no expert but happy to follow instructions.

**Comment by emansih** [comment]
curl -X GET "https://YOUR_FIREFLY_URL/api/v1/summary/basic?start=2019-09-01&end=2019-09-10&currency_code=EUR" -H "accept: application/json" -H "Authorization: Bearer YOUR_PERSONAL_ACCESS_TOKEN"

I don't need the values. I need to know the name of all the keys displayed.

**Comment by porjo** [comment]
```
{
  "net-worth-in-AUD": {
    "key": "net-worth-in-AUD",
    "title": "Net worth (A$)",
    "monetary_value": 0.95,
    "currency_id": 11,
    "currency_code": "AUD",
    "currency_symbol": "A$",
    "currency_decimal_places": 2,
    "value_parsed": "A$0.95",
    "local_icon": "line-chart",
    "sub_title": ""
  }
}
```

**Comment by emansih** [comment]
It seems strange that this is the only output.

**Comment by emansih** [comment]
It's a bug in Firefly III https://github.com/firefly-iii/firefly-iii/issues/2609
