### ISSUE TITLE
App Crash: Immediately upon startup (JSONException)

### ISSUE THREAD

**Issue by scar45** [emansih/FireflyMobile#68]
**Firefly III Server Version:** 4.8.1.1

**Firefly III Mobile Version:** 1.4.0

**Android Version:** 9

--------------------------------------

## Expected Behavior
App logs in without issue
## Current Behavior
With a fresh install of Firefly-III, and a new login (auth'd successfully via OAUTH), I get the following stack traces:

**USD as default currency:**
```
STACK_TRACE=java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        ... 1 more
Caused by: org.json.JSONException: Value [] of type org.json.JSONArray cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONObject.<init>(JSONObject.java:163)
        at org.json.JSONObject.<init>(JSONObject.java:176)
        at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:4)
        at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)
        at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
        at i.l.run(DefaultCallAdapterFactory.java:3)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
```

**Another default currency:**
```
STACK_TRACE=java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        ... 1 more
Caused by: org.json.JSONException: No value for left-to-spend-in-CURRENCY_CODE
        at org.json.JSONObject.get(JSONObject.java:392)
        at org.json.JSONObject.getJSONObject(JSONObject.java:612)
        at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)
        at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)
        at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)
        at i.l.run(DefaultCallAdapterFactory.java:3)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
```

I can provide more information if necessary. I currently have a single OAUTH Client with a single authorized application. I haven't yet created a PAT, but can for troubleshooting purposes of course.

Thanks in advance for any insight / fixing the issue!

**Comment by emansih** [comment]
It's a bug in Firefly III firefly-iii/firefly-iii#2609
