### ISSUE TITLE
Crashes after connection with personal access token 

### ISSUE THREAD

**Issue by natrius** [emansih/FireflyMobile#69]
So, i finally wanna try this app :)

**Firefly III Server Version:** 4.8.1.1

**Firefly III Mobile Version:** 1.4.0

**Android Version:**  9

**Device Information:**  

- BRAND: Xiaomi
- MODEL: Mi9
--------------------------------------

## Expected Behavior

App opens and i can do things. 

## Current Behavior

After putting in the personal token, the app opens short and it seems to view the dashboard for half a second and then app just crashes. 

## Steps to Reproduce

```
REPORT_ID=37be9d31-cc02-4a2c-b430-0de98fa75bd2

APP_VERSION_NAME=1.4.0

PHONE_MODEL=MI 9

BRAND=Xiaomi

PRODUCT=cepheus

ANDROID_VERSION=9

BUILD_CONFIG=

STACK_TRACE=java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:35)

	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

Caused by: java.lang.reflect.InvocationTargetException

	at java.lang.reflect.Method.invoke(Native Method)

	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)

	... 1 more

Caused by: org.json.JSONException: No value for left-to-spend-in-EUR

	at org.json.JSONObject.get(JSONObject.java:392)

	at org.json.JSONObject.getJSONObject(JSONObject.java:612)

	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)

	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)

	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)

	at i.l.run(DefaultCallAdapterFactory.java:3)

	at android.os.Handler.handleCallback(Unknown Source:2)

	at android.os.Handler.dispatchMessage(Unknown Source:4)

	at android.os.Looper.loop(Unknown Source:208)

	at android.app.ActivityThread.main(Unknown Source:107)

	... 3 more



LOGCAT=09-26 02:43:28.860 E/AndroidRuntime(11486): 	at org.json.JSONObject.get(JSONObject.java:392)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at org.json.JSONObject.getJSONObject(JSONObject.java:612)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at i.l.run(DefaultCallAdapterFactory.java:3)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at android.os.Handler.handleCallback(Unknown Source:2)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at android.os.Handler.dispatchMessage(Unknown Source:4)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at android.os.Looper.loop(Unknown Source:208)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	at android.app.ActivityThread.main(Unknown Source:107)

09-26 02:43:28.860 E/AndroidRuntime(11486): 	... 3 more

09-26 02:43:28.869 E/ACRA    (11486): ACRA caught a RuntimeException for xyz.hisname.fireflyiii

09-26 02:43:28.869 E/ACRA    (11486): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

09-26 02:43:28.869 E/ACRA    (11486): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:35)

09-26 02:43:28.869 E/ACRA    (11486): 	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

09-26 02:43:28.869 E/ACRA    (11486): Caused by: java.lang.reflect.InvocationTargetException

09-26 02:43:28.869 E/ACRA    (11486): 	at java.lang.reflect.Method.invoke(Native Method)

09-26 02:43:28.869 E/ACRA    (11486): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)

09-26 02:43:28.869 E/ACRA    (11486): 	... 1 more

09-26 02:43:28.869 E/ACRA    (11486): Caused by: org.json.JSONException: No value for left-to-spend-in-EUR

09-26 02:43:28.869 E/ACRA    (11486): 	at org.json.JSONObject.get(JSONObject.java:392)

09-26 02:43:28.869 E/ACRA    (11486): 	at org.json.JSONObject.getJSONObject(JSONObject.java:612)

09-26 02:43:28.869 E/ACRA    (11486): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)

09-26 02:43:28.869 E/ACRA    (11486): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)

09-26 02:43:28.869 E/ACRA    (11486): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)

09-26 02:43:28.869 E/ACRA    (11486): 	at i.l.run(DefaultCallAdapterFactory.java:3)

09-26 02:43:28.869 E/ACRA    (11486): 	at android.os.Handler.handleCallback(Unknown Source:2)

09-26 02:43:28.869 E/ACRA    (11486): 	at android.os.Handler.dispatchMessage(Unknown Source:4)

09-26 02:43:28.869 E/ACRA    (11486): 	at android.os.Looper.loop(Unknown Source:208)

09-26 02:43:28.869 E/ACRA    (11486): 	at android.app.ActivityThread.main(Unknown Source:107)

09-26 02:43:28.869 E/ACRA    (11486): 	... 3 more

09-26 02:43:29.004 I/ACRA    (11486): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2019-09-26T02:43:28.872+02:00.stacktrace

09-26 02:43:29.007 I/Timeline(11486): Timeline: Activity_launch_request time:464457111

09-26 02:43:29.023 I/Process (11486): Sending signal. PID: 11486 SIG: 9

09-26 02:43:33.984 E/name.fireflyii(12622): Not starting debugger since process cannot load the jdwp agent.

09-26 02:43:34.051 I/Perf    (12622): Connecting to perf service.

09-26 02:43:34.057 I/MultiDex(12622): VM with version 2.1.0 has multidex support

09-26 02:43:34.057 I/MultiDex(12622): Installing application

09-26 02:43:34.057 I/MultiDex(12622): VM has multidex support, MultiDex support library is disabled.

09-26 02:43:34.092 I/ACRA    (12622): ACRA is enabled for xyz.hisname.fireflyiii, initializing...

09-26 02:43:34.119 D/NetworkSecurityConfig(12622): Using Network Security Config from resource network_security_config debugBuild: false

09-26 02:43:34.123 I/MaterialDrawer(12622): You have not specified a ImageLoader implementation through the DrawerImageLoader.init() method, or you are still overriding the deprecated method set(ImageView iv, Uri u, Drawable d) instead of set(ImageView iv, Uri u, Drawable d, String tag)

09-26 02:43:34.235 I/Adreno  (12622): QUALCOMM build                   : f618f24, I3646c1b6a8

09-26 02:43:34.235 I/Adreno  (12622): Build Date                       : 12/13/18

09-26 02:43:34.235 I/Adreno  (12622): OpenGL ES Shader Compiler Version: EV031.25.16.00

09-26 02:43:34.235 I/Adreno  (12622): Local Branch                     : mybranche8ff427b-d2d8-f176-a8c8-5cb90179c3d8

09-26 02:43:34.235 I/Adreno  (12622): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r50

09-26 02:43:34.235 I/Adreno  (12622): Remote Branch                    : NONE

09-26 02:43:34.235 I/Adreno  (12622): Reconstruct Branch               : NOTHING

09-26 02:43:34.236 I/Adreno  (12622): Build Config                     : S P 6.0.9 AArch64

09-26 02:43:34.226 W/RenderThread(12622): type=1400 audit(0.0:146850): avc: denied { search } for name="12622" dev="debugfs" ino=17989617 scontext=u:r:untrusted_app:s0:c215,c256,c512,c768 tcontext=u:object_r:kgsl_debugfs:s0 tclass=dir permissive=0

09-26 02:43:34.226 W/RenderThread(12622): type=1400 audit(0.0:146851): avc: denied { search } for name="12622" dev="debugfs" ino=17989617 scontext=u:r:untrusted_app:s0:c215,c256,c512,c768 tcontext=u:object_r:kgsl_debugfs:s0 tclass=dir permissive=0

09-26 02:43:34.242 I/Adreno  (12622): PFP: 0x016ee180, ME: 0x00000000

09-26 02:43:34.246 I/ConfigStore(12622): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1

09-26 02:43:34.246 I/ConfigStore(12622): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 1

09-26 02:43:34.247 I/OpenGLRenderer(12622): Initialized EGL, version 1.4

09-26 02:43:34.247 D/OpenGLRenderer(12622): Swap behavior 2

09-26 02:43:34.249 E/RecyclerView(12622): No adapter attached; skipping layout

09-26 02:43:34.615 D/AndroidRuntime(12622): Shutting down VM

09-26 02:43:34.615 E/AndroidRuntime(12622): FATAL EXCEPTION: main

09-26 02:43:34.615 E/AndroidRuntime(12622): Process: xyz.hisname.fireflyiii, PID: 12622

09-26 02:43:34.615 E/AndroidRuntime(12622): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:35)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

09-26 02:43:34.615 E/AndroidRuntime(12622): Caused by: java.lang.reflect.InvocationTargetException

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at java.lang.reflect.Method.invoke(Native Method)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	... 1 more

09-26 02:43:34.615 E/AndroidRuntime(12622): Caused by: org.json.JSONException: No value for left-to-spend-in-EUR

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at org.json.JSONObject.get(JSONObject.java:392)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at org.json.JSONObject.getJSONObject(JSONObject.java:612)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at i.l.run(DefaultCallAdapterFactory.java:3)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at android.os.Handler.handleCallback(Unknown Source:2)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at android.os.Handler.dispatchMessage(Unknown Source:4)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at android.os.Looper.loop(Unknown Source:208)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	at android.app.ActivityThread.main(Unknown Source:107)

09-26 02:43:34.615 E/AndroidRuntime(12622): 	... 3 more

09-26 02:43:34.619 E/ACRA    (12622): ACRA caught a RuntimeException for xyz.hisname.fireflyiii

09-26 02:43:34.619 E/ACRA    (12622): java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

09-26 02:43:34.619 E/ACRA    (12622): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:35)

09-26 02:43:34.619 E/ACRA    (12622): 	at com.android.internal.os.ZygoteInit.main(Unknown Source:274)

09-26 02:43:34.619 E/ACRA    (12622): Caused by: java.lang.reflect.InvocationTargetException

09-26 02:43:34.619 E/ACRA    (12622): 	at java.lang.reflect.Method.invoke(Native Method)

09-26 02:43:34.619 E/ACRA    (12622): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)

09-26 02:43:34.619 E/ACRA    (12622): 	... 1 more

09-26 02:43:34.619 E/ACRA    (12622): Caused by: org.json.JSONException: No value for left-to-spend-in-EUR

09-26 02:43:34.619 E/ACRA    (12622): 	at org.json.JSONObject.get(JSONObject.java:392)

09-26 02:43:34.619 E/ACRA    (12622): 	at org.json.JSONObject.getJSONObject(JSONObject.java:612)

09-26 02:43:34.619 E/ACRA    (12622): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:9)

09-26 02:43:34.619 E/ACRA    (12622): 	at xyz.hisname.fireflyiii.b.j.a.a(SummaryViewModel.kt:1)

09-26 02:43:34.619 E/ACRA    (12622): 	at xyz.hisname.fireflyiii.util.c.a.a(CallbackUtil.kt:1)

09-26 02:43:34.619 E/ACRA    (12622): 	at i.l.run(DefaultCallAdapterFactory.java:3)

09-26 02:43:34.619 E/ACRA    (12622): 	at android.os.Handler.handleCallback(Unknown Source:2)

09-26 02:43:34.619 E/ACRA    (12622): 	at android.os.Handler.dispatchMessage(Unknown Source:4)

09-26 02:43:34.619 E/ACRA    (12622): 	at android.os.Looper.loop(Unknown Source:208)

09-26 02:43:34.619 E/ACRA    (12622): 	at android.app.ActivityThread.main(Unknown Source:107)

09-26 02:43:34.619 E/ACRA    (12622): 	... 3 more

IS_SILENT=false

USER_CRASH_DATE=2019-09-26T02:43:34.624+02:00
```

**Comment by natrius** [comment]
Maybe this is related to https://github.com/emansih/FireflyMobile/issues/67 or https://github.com/emansih/FireflyMobile/issues/66 ?

**Comment by emansih** [comment]
See #64 and #68

**Comment by emansih** [comment]
It's fixed in the develop branch of firefly-iii

**Comment by natrius** [comment]
Ah, so i have to wait for a firefly-iii update, thanks. :)

**Comment by natrius** [comment]
Just to inform you, updated f-droid version and its now working. No change with firefly itself. *shrug*

@emansih

**Comment by emansih** [comment]
Yeah, but did you notice that `LEFT TO SPEND` box is not 0? ;)
