### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by Nijin22** [emansih/FireflyMobile#76]
**Firefly III Server Version:**
4.8.2

**Firefly III Mobile Version:**
1.4.6

**Android Version:**  
9

**Device Information:**  

- BRAND: Samsung
- MODEL: Note 9
--------------------------------------

## Expected Behavior
Clicking on the app icon on the android launcher, launches the app

## Current Behavior
Clicking on the app icon opens the mail client, with the subject pre-filled to "PLEASE POST THE ATTACHED STACK TRACE ON GITHUB IF POSSIBLE".

The stack trace reads:
```
REPORT_ID=5a804723-0173-4a35-8c51-56f37b3d8de7
APP_VERSION_NAME=1.4.6
PHONE_MODEL=SM-N960F
BRAND=samsung
PRODUCT=crownltexx
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.floatingactionbutton.FloatingActionButton.setVisibility(int)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5017)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4926)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4976)
	at android.app.ActivityThread.access$3300(ActivityThread.java:235)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1936)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:6990)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.floatingactionbutton.FloatingActionButton.setVisibility(int)' on a null object reference
	at xyz.hisname.fireflyiii.ui.h.a.a(DashboardFragment.kt:195)
	at androidx.fragment.app.Fragment.a0(Fragment.java:4)
	at androidx.fragment.app.r.a(FragmentStateManager.java:19)
	at androidx.fragment.app.m.a(FragmentManager.java:133)
	at androidx.fragment.app.m.j(FragmentManager.java:1)
	at androidx.fragment.app.m.i(FragmentManager.java:4)
	at androidx.fragment.app.m.a(FragmentManager.java:188)
	at androidx.fragment.app.m.c(FragmentManager.java:40)
	at androidx.fragment.app.m.e(FragmentManager.java:4)
	at androidx.fragment.app.h.b(FragmentController.java:1)
	at androidx.fragment.app.d.onCreate(FragmentActivity.java:18)
	at androidx.appcompat.app.e.onCreate(AppCompatActivity.java:4)
	at xyz.hisname.fireflyiii.ui.base.b.onCreate(BaseActivity.kt:1)
	at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:1)
	at android.app.Activity.performCreate(Activity.java:7326)
	at android.app.Activity.performCreate(Activity.java:7317)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
	... 16 more

LOGCAT=01-04 13:56:27.798 D/skia    (12960): approximate: numPoints=4, lengths[0]=0.000000, totalLength=3.448155, segmentPoints[0]=[0.000000,0.100000]
01-04 13:56:27.798 D/skia    (12960): approximate: approximation[0]=0.000000, approximation[1]=0.000000, approximation[2]=0.100000
01-04 13:56:27.798 D/skia    (12960): approximate: numPoints=4, lengths[3]=3.448155, totalLength=3.448155, segmentPoints[3]=[3.000000,0.100000]
01-04 13:56:27.798 D/skia    (12960): approximate: approximation[9]=1.000000, approximation[10]=3.000000, approximation[11]=0.100000
01-04 13:56:27.799 D/skia    (12960): approximate: numPoints=43, lengths[0]=0.000000, totalLength=722.199951, segmentPoints[0]=[-522.599976,0.000000]
01-04 13:56:27.799 D/skia    (12960): approximate: approximation[0]=0.000000, approximation[1]=-522.599976, approximation[2]=0.000000
01-04 13:56:27.799 D/skia    (12960): approximate: numPoints=43, lengths[42]=722.199951, totalLength=722.199951, segmentPoints[42]=[199.600006,0.000000]
01-04 13:56:27.799 D/skia    (12960): approximate: approximation[126]=1.000000, approximation[127]=199.600006, approximation[128]=0.000000
01-04 13:56:27.799 D/skia    (12960): approximate: numPoints=3, lengths[0]=0.000000, totalLength=2.472497, segmentPoints[0]=[0.000000,0.100000]
01-04 13:56:27.799 D/skia    (12960): approximate: approximation[0]=0.000000, approximation[1]=0.000000, approximation[2]=0.100000
01-04 13:56:27.799 D/skia    (12960): approximate: numPoints=3, lengths[2]=2.472497, totalLength=2.472497, segmentPoints[2]=[2.000000,0.100000]
01-04 13:56:27.799 D/skia    (12960): approximate: approximation[6]=1.000000, approximation[7]=2.000000, approximation[8]=0.100000
01-04 13:56:27.809 D/TcpOptimizer(12960): TcpOptimizer-ON
01-04 13:56:27.842 D/OpenGLRenderer(12960): Skia GL Pipeline
01-04 13:56:27.846 D/EmergencyMode(12960): [EmergencyManager] android createPackageContext successful
01-04 13:56:27.863 D/InputTransport(12960): Input channel constructed: fd=71
01-04 13:56:27.863 D/ViewRootImpl@8726465[HomeActivity](12960): setView = DecorView@e69b53a[HomeActivity] TM=true MM=false
01-04 13:56:27.871 D/ViewRootImpl@8726465[HomeActivity](12960): dispatchDetachedFromWindow
01-04 13:56:27.872 D/ViewRootImpl@8726465[HomeActivity](12960): Surface release. android.view.ViewRootImpl.doDie:7954 android.view.ViewRootImpl.die:7922 android.view.WindowManagerGlobal.removeViewLocked:497 android.view.WindowManagerGlobal.removeView:435 android.view.WindowManagerImpl.removeViewImmediate:124 android.app.ActivityThread.handleDestroyActivity:4731 android.app.ActivityThread.handleRelaunchActivityInner:4993 android.app.ActivityThread.handleRelaunchActivity:4926 
01-04 13:56:27.876 D/InputTransport(12960): Input channel destroyed: fd=71
01-04 13:56:27.888 D/AndroidRuntime(12960): Shutting down VM
01-04 13:56:27.888 E/AndroidRuntime(12960): FATAL EXCEPTION: main
01-04 13:56:27.888 E/AndroidRuntime(12960): Process: xyz.hisname.fireflyiii, PID: 12960
01-04 13:56:27.888 E/AndroidRuntime(12960): java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.floatingactionbutton.FloatingActionButton.setVisibility(int)' on a null object reference
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5017)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4926)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4976)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread.access$3300(ActivityThread.java:235)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1936)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.os.Looper.loop(Looper.java:214)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread.main(ActivityThread.java:6990)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at java.lang.reflect.Method.invoke(Native Method)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
01-04 13:56:27.888 E/AndroidRuntime(12960): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.floatingactionbutton.FloatingActionButton.setVisibility(int)' on a null object reference
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at xyz.hisname.fireflyiii.ui.h.a.a(DashboardFragment.kt:195)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.Fragment.a0(Fragment.java:4)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.r.a(FragmentStateManager.java:19)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.m.a(FragmentManager.java:133)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.m.j(FragmentManager.java:1)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.m.i(FragmentManager.java:4)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.m.a(FragmentManager.java:188)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.m.c(FragmentManager.java:40)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.m.e(FragmentManager.java:4)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.h.b(FragmentController.java:1)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.fragment.app.d.onCreate(FragmentActivity.java:18)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at androidx.appcompat.app.e.onCreate(AppCompatActivity.java:4)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at xyz.hisname.fireflyiii.ui.base.b.onCreate(BaseActivity.kt:1)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:1)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.Activity.performCreate(Activity.java:7326)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.Activity.performCreate(Activity.java:7317)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
01-04 13:56:27.888 E/AndroidRuntime(12960): 	... 16 more
01-04 13:56:27.888 E/ACRA    (12960): ACRA caught a RuntimeException for xyz.hisname.fireflyiii
01-04 13:56:27.888 E/ACRA    (12960): java.lang.RuntimeException: Unable to start activity ComponentInfo{xyz.hisname.fireflyiii/xyz.hisname.fireflyiii.ui.HomeActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.floatingactionbutton.FloatingActionButton.setVisibility(int)' on a null object reference
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5017)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4926)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:59)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4976)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread.access$3300(ActivityThread.java:235)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1936)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.os.Handler.dispatchMessage(Handler.java:106)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.os.Looper.loop(Looper.java:214)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread.main(ActivityThread.java:6990)
01-04 13:56:27.888 E/ACRA    (12960): 	at java.lang.reflect.Method.invoke(Native Method)
01-04 13:56:27.888 E/ACRA    (12960): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
01-04 13:56:27.888 E/ACRA    (12960): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
01-04 13:56:27.888 E/ACRA    (12960): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.google.android.material.floatingactionbutton.FloatingActionButton.setVisibility(int)' on a null object reference
01-04 13:56:27.888 E/ACRA    (12960): 	at xyz.hisname.fireflyiii.ui.h.a.a(DashboardFragment.kt:195)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.Fragment.a0(Fragment.java:4)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.r.a(FragmentStateManager.java:19)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.m.a(FragmentManager.java:133)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.m.j(FragmentManager.java:1)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.m.i(FragmentManager.java:4)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.m.a(FragmentManager.java:188)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.m.c(FragmentManager.java:40)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.m.e(FragmentManager.java:4)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.h.b(FragmentController.java:1)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.fragment.app.d.onCreate(FragmentActivity.java:18)
01-04 13:56:27.888 E/ACRA    (12960): 	at androidx.appcompat.app.e.onCreate(AppCompatActivity.java:4)
01-04 13:56:27.888 E/ACRA    (12960): 	at xyz.hisname.fireflyiii.ui.base.b.onCreate(BaseActivity.kt:1)
01-04 13:56:27.888 E/ACRA    (12960): 	at xyz.hisname.fireflyiii.ui.HomeActivity.onCreate(HomeActivity.kt:1)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.Activity.performCreate(Activity.java:7326)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.Activity.performCreate(Activity.java:7317)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
01-04 13:56:27.888 E/ACRA    (12960): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
01-04 13:56:27.888 E/ACRA    (12960): 	... 16 more
IS_SILENT=false
USER_CRASH_DATE=2020-01-04T13:56:27.894+01:00
```

## Steps to Reproduce
1. Click on the app icon

## Additional hints
- Clearing the app's cache does NOT fix the problem
- Clearing the app's entire data DID FIX the problem
- Stoping the app (via "last apps" button --> "Close all") will put the app back into a state where it will crash on launch.
- I don't have a lot of experience with android development, but I could imagine that the issue is related to a variable (of type `FloatingActionButton`) not being correctly initialized on a second start of the app (but NOT from memory)

**Comment by emansih** [comment]
Hi, there was new release that fix this issue. (version 1.4.7)

**Comment by emansih** [comment]
https://github.com/emansih/FireflyMobile/releases/tag/v1.4.7

**Comment by Nijin22** [comment]
Wonderful, thanks! It's not yet available for me on [F-Droid](https://f-droid.org/packages/xyz.hisname.fireflyiii/), but I'll just wait a little longer than. :)

**Comment by emansih** [comment]
install the apk from github or my self hosted f-droid
