### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TobiasDev** [emansih/FireflyMobile#79]
REPORT_ID=90d47307-f087-424b-9f60-647613130ffa
APP_VERSION_NAME=1.4.7
PHONE_MODEL=ONEPLUS A3003
BRAND=OnePlus
PRODUCT=lineage_oneplus3
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=g.t: lateinit property accountType has not been initialized
	at xyz.hisname.fireflyiii.ui.c.a.b(AccountDetailFragment.kt:28)
	at androidx.fragment.app.Fragment.d(Fragment.java:11)
	at androidx.fragment.app.m.b(FragmentManager.java:81)
	at androidx.fragment.app.h.b(FragmentController.java:4)
	at androidx.fragment.app.d.onMenuItemSelected(FragmentActivity.java:3)
	at androidx.appcompat.app.e.onMenuItemSelected(AppCompatActivity.java:1)
	at d.a.o.i.onMenuItemSelected(WindowCallbackWrapper.java:1)
	at d.a.o.i.onMenuItemSelected(WindowCallbackWrapper.java:1)
	at androidx.appcompat.app.l$b.onMenuItemClick(ToolbarActionBar.java:1)
	at androidx.appcompat.widget.Toolbar$a.onMenuItemClick(Toolbar.java:2)
	at androidx.appcompat.widget.ActionMenuView$d.a(ActionMenuView.java:2)
	at androidx.appcompat.view.menu.g.a(MenuBuilder.java:48)
	at androidx.appcompat.view.menu.j.g(MenuItemImpl.java:2)
	at androidx.appcompat.view.menu.g.a(MenuBuilder.java:84)
	at androidx.appcompat.view.menu.l.onItemClick(MenuPopup.java:6)
	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
	at android.widget.AbsListView$3.run(AbsListView.java:4052)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

LOGCAT=01-12 06:29:56.508 W/ActivityThread(29227): handleWindowVisibility: no activity for token android.os.BinderProxy@f128a9b
01-12 06:29:56.580 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:29:56.628 I/chatty  (29227): uid=10096(xyz.hisname.fireflyiii) identical 14 lines
01-12 06:29:56.633 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:30:16.874 D/OpenGLRenderer(29227): endAllActiveAnimators on 0x6f61c27400 (RippleDrawable) with handle 0x6f61f88580
01-12 06:30:20.139 D/OpenGLRenderer(29227): endAllActiveAnimators on 0x6f61c27900 (DropDownListView) with handle 0x6f61f88a60
01-12 06:30:27.489 W/name.fireflyii(29227): Accessing hidden method Landroid/view/View;->setTransitionVisibility(I)V (dark greylist, linking)
01-12 06:30:27.544 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:30:28.852 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:30:45.536 D/OpenGLRenderer(29227): endAllActiveAnimators on 0x6f6196ba00 (DropDownListView) with handle 0x6f63175880
01-12 06:30:48.208 D/OpenGLRenderer(29227): endAllActiveAnimators on 0x6f6196dd00 (DropDownListView) with handle 0x6f63175aa0
01-12 06:31:01.169 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:31:01.171 I/name.fireflyii(29227): Background concurrent copying GC freed 99915(4MB) AllocSpace objects, 4(64KB) LOS objects, 50% free, 8MB/17MB, paused 177us total 121.547ms
01-12 06:31:16.724 W/ActivityThread(29227): handleWindowVisibility: no activity for token android.os.BinderProxy@ab36800
01-12 06:31:16.775 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:31:16.790 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:31:16.812 I/chatty  (29227): uid=10096(xyz.hisname.fireflyiii) identical 7 lines
01-12 06:31:16.818 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:31:22.136 E/SpannableStringBuilder(29227): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-12 06:31:22.136 E/SpannableStringBuilder(29227): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-12 06:31:24.944 E/SpannableStringBuilder(29227): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-12 06:31:24.944 E/SpannableStringBuilder(29227): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-12 06:31:35.950 D/OpenGLRenderer(29227): endAllActiveAnimators on 0x6f61044c00 (DropDownListView) with handle 0x6f61fe8300
01-12 06:31:44.450 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:31:58.302 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:31:58.412 I/name.fireflyii(29227): Background concurrent copying GC freed 199196(8MB) AllocSpace objects, 22(472KB) LOS objects, 50% free, 8MB/17MB, paused 142us total 106.507ms
01-12 06:32:16.590 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:32:33.620 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:32:34.938 W/ActivityThread(29227): handleWindowVisibility: no activity for token android.os.BinderProxy@d284297
01-12 06:32:34.985 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:32:35.026 I/TextInputLayout(29227): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-12 06:32:35.207 I/name.fireflyii(29227): Background concurrent copying GC freed 199534(8MB) AllocSpace objects, 14(372KB) LOS objects, 49% free, 8MB/17MB, paused 162us total 122.090ms
01-12 06:32:45.993 W/InputEventReceiver(29227): Attempted to finish an input event but the input event receiver has already been disposed.
01-12 06:32:52.650 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:32:59.204 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:33:28.086 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:33:33.003 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:33:33.055 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:33:33.137 I/name.fireflyii(29227): Background concurrent copying GC freed 191977(7MB) AllocSpace objects, 8(212KB) LOS objects, 49% free, 9MB/19MB, paused 185us total 160.416ms
01-12 06:33:36.094 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:33:38.456 I/chatty  (29227): uid=10096(xyz.hisname.fireflyiii) identical 1 line
01-12 06:33:38.486 E/RecyclerView(29227): No adapter attached; skipping layout
01-12 06:33:39.805 D/AndroidRuntime(29227): Shutting down VM
01-12 06:33:39.806 E/AndroidRuntime(29227): FATAL EXCEPTION: main
01-12 06:33:39.806 E/AndroidRuntime(29227): Process: xyz.hisname.fireflyiii, PID: 29227
01-12 06:33:39.806 E/AndroidRuntime(29227): g.t: lateinit property accountType has not been initialized
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at xyz.hisname.fireflyiii.ui.c.a.b(AccountDetailFragment.kt:28)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.fragment.app.Fragment.d(Fragment.java:11)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.fragment.app.m.b(FragmentManager.java:81)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.fragment.app.h.b(FragmentController.java:4)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.fragment.app.d.onMenuItemSelected(FragmentActivity.java:3)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.appcompat.app.e.onMenuItemSelected(AppCompatActivity.java:1)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at d.a.o.i.onMenuItemSelected(WindowCallbackWrapper.java:1)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at d.a.o.i.onMenuItemSelected(WindowCallbackWrapper.java:1)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.appcompat.app.l$b.onMenuItemClick(ToolbarActionBar.java:1)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.appcompat.widget.Toolbar$a.onMenuItemClick(Toolbar.java:2)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.appcompat.widget.ActionMenuView$d.a(ActionMenuView.java:2)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.appcompat.view.menu.g.a(MenuBuilder.java:48)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.appcompat.view.menu.j.g(MenuItemImpl.java:2)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.appcompat.view.menu.g.a(MenuBuilder.java:84)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at androidx.appcompat.view.menu.l.onItemClick(MenuPopup.java:6)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at android.widget.AbsListView$3.run(AbsListView.java:4052)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at android.os.Handler.handleCallback(Handler.java:873)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at android.os.Looper.loop(Looper.java:193)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at java.lang.reflect.Method.invoke(Native Method)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-12 06:33:39.806 E/AndroidRuntime(29227): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
01-12 06:33:39.806 E/ACRA    (29227): ACRA caught a t for xyz.hisname.fireflyiii
01-12 06:33:39.806 E/ACRA    (29227): g.t: lateinit property accountType has not been initialized
01-12 06:33:39.806 E/ACRA    (29227): 	at xyz.hisname.fireflyiii.ui.c.a.b(AccountDetailFragment.kt:28)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.fragment.app.Fragment.d(Fragment.java:11)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.fragment.app.m.b(FragmentManager.java:81)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.fragment.app.h.b(FragmentController.java:4)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.fragment.app.d.onMenuItemSelected(FragmentActivity.java:3)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.appcompat.app.e.onMenuItemSelected(AppCompatActivity.java:1)
01-12 06:33:39.806 E/ACRA    (29227): 	at d.a.o.i.onMenuItemSelected(WindowCallbackWrapper.java:1)
01-12 06:33:39.806 E/ACRA    (29227): 	at d.a.o.i.onMenuItemSelected(WindowCallbackWrapper.java:1)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.appcompat.app.l$b.onMenuItemClick(ToolbarActionBar.java:1)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.appcompat.widget.Toolbar$a.onMenuItemClick(Toolbar.java:2)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.appcompat.widget.ActionMenuView$d.a(ActionMenuView.java:2)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.appcompat.view.menu.g.a(MenuBuilder.java:48)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.appcompat.view.menu.j.g(MenuItemImpl.java:2)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.appcompat.view.menu.g.a(MenuBuilder.java:84)
01-12 06:33:39.806 E/ACRA    (29227): 	at androidx.appcompat.view.menu.l.onItemClick(MenuPopup.java:6)
01-12 06:33:39.806 E/ACRA    (29227): 	at android.widget.AdapterView.performItemClick(AdapterView.java:318)
01-12 06:33:39.806 E/ACRA    (29227): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1159)
01-12 06:33:39.806 E/ACRA    (29227): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3136)
01-12 06:33:39.806 E/ACRA    (29227): 	at android.widget.AbsListView$3.run(AbsListView.java:4052)
01-12 06:33:39.806 E/ACRA    (29227): 	at android.os.Handler.handleCallback(Handler.java:873)
01-12 06:33:39.806 E/ACRA    (29227): 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-12 06:33:39.806 E/ACRA    (29227): 	at android.os.Looper.loop(Looper.java:193)
01-12 06:33:39.806 E/ACRA    (29227): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
01-12 06:33:39.806 E/ACRA    (29227): 	at java.lang.reflect.Method.invoke(Native Method)
01-12 06:33:39.806 E/ACRA    (29227): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
01-12 06:33:39.806 E/ACRA    (29227): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
IS_SILENT=false
USER_CRASH_DATE=2020-01-12T06:33:39.827+01:00

**Comment by emansih** [comment]
Hi can you tell me the steps you took to crash the app? thanks

**Comment by TobiasDev** [comment]
Sorry! Was too tired when I got this and forgot that part.

1. Go into assets accounts
2. Select an account
3. Click edit
4. 100% crash for me

**Comment by emansih** [comment]
I noticed you are using 1.4.7, 1.4.8 is out a few days ago. Try that. I have fixed it.

**Comment by TobiasDev** [comment]
Ah. I havent gotten that update through f-droid yet, so didn't know. Sorry!

**Comment by emansih** [comment]
Get it from the release page
