### ISSUE TITLE
Invalid accounts when creating transactions

### ISSUE THREAD

**Issue by chickenskitchen** [emansih/FireflyMobile#81]
**Firefly III Server Version:**
5.0.4

**Firefly III Mobile Version:**
2.0.0

**Android Version:**  
10

--------------------------------------

## Expected Behavior
Creating transactions (withdrawals, deposits) should work.
I select an existing Asset account for my source account. For destination account, I type in some freeform text.
I enter something like "5.00" in Amount and add a description like "test".

NOTE: Doing other operations such as deleting an existing transaction works fine.

## Current Behavior
Error message.
Withdrawals: "Invalid Source Account"
Deposits: "Invalid Destination Account"

REPORT_ID=f0976c1d-7687-4900-8890-abdee0db51b6
APP_VERSION_NAME=2.0.0
PHONE_MODEL=Pixel 3
BRAND=google
PRODUCT=blueline
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List xyz.hisname.fireflyiii.repository.models.error.Errors.getTransactions_currency()' on a null object reference
	at xyz.hisname.fireflyiii.d.q.b$a.a(TransactionsViewModel.kt:5)
	at xyz.hisname.fireflyiii.d.q.b$a.a(TransactionsViewModel.kt:1)
	at xyz.hisname.fireflyiii.util.s.a$a.a(CallbackUtil.kt:1)
	at l.i$b$a.a(DefaultCallAdapterFactory.java:4)
	at l.a.run(Unknown Source:6)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

LOGCAT=--------- beginning of main
01-27 21:41:29.809 W/ActivityThread(26612): handleWindowVisibility: no activity for token android.os.BinderProxy@5688c75
01-27 21:41:29.965 E/RecyclerView(26612): No adapter attached; skipping layout
01-27 21:41:30.000 W/name.fireflyii(26612): Reducing the number of considered missed Gc histogram windows from 141 to 100
01-27 21:41:41.649 W/ActivityThread(26612): handleWindowVisibility: no activity for token android.os.BinderProxy@c4e26
01-27 21:41:41.698 I/TextInputLayout(26612): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-27 21:41:41.717 I/chatty  (26612): uid=10273(xyz.hisname.fireflyiii) identical 4 lines
01-27 21:41:41.720 I/TextInputLayout(26612): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-27 21:41:47.493 I/AssistStructure(26612): Flattened final assist data: 12056 bytes, containing 1 windows, 88 views
01-27 21:41:49.494 E/SpannableStringBuilder(26612): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-27 21:41:49.494 E/SpannableStringBuilder(26612): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-27 21:41:51.598 E/SpannableStringBuilder(26612): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-27 21:41:51.599 E/SpannableStringBuilder(26612): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
01-27 21:42:11.176 D/OpenGLRenderer(26612): endAllActiveAnimators on 0x704dffd100 (DropDownListView) with handle 0x706e344c60
01-27 21:42:36.424 I/TextInputLayout(26612): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-27 21:42:36.441 I/chatty  (26612): uid=10273(xyz.hisname.fireflyiii) identical 4 lines
01-27 21:42:36.443 I/TextInputLayout(26612): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-27 21:42:39.541 I/AssistStructure(26612): Flattened final assist data: 12056 bytes, containing 1 windows, 88 views
01-27 21:42:48.348 D/OpenGLRenderer(26612): endAllActiveAnimators on 0x70c6313f00 (DropDownListView) with handle 0x70ca018400
01-27 21:43:00.499 D/OpenGLRenderer(26612): endAllActiveAnimators on 0x70c6316c00 (DropDownListView) with handle 0x70ca0106e0
01-27 21:43:03.433 D/OpenGLRenderer(26612): endAllActiveAnimators on 0x70506f2500 (DropDownListView) with handle 0x70ca010c40
01-27 21:43:06.491 D/OpenGLRenderer(26612): endAllActiveAnimators on 0x7050778300 (DropDownListView) with handle 0x70ca010760
01-27 21:43:06.497 W/InputEventReceiver(26612): Attempted to finish an input event but the input event receiver has already been disposed.
01-27 21:43:10.506 D/OpenGLRenderer(26612): endAllActiveAnimators on 0x70507a4100 (DropDownListView) with handle 0x704dd8f5c0
01-27 21:43:28.315 W/ListPreference(26612): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
01-27 21:43:36.489 W/ListPreference(26612): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
01-27 21:43:53.439 W/ListPreference(26612): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
01-27 21:43:54.351 E/RecyclerView(26612): No adapter attached; skipping layout
01-27 21:44:00.548 W/ListPreference(26612): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
01-27 21:44:17.355 W/ListPreference(26612): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
01-27 21:44:18.169 E/RecyclerView(26612): No adapter attached; skipping layout
01-27 21:44:21.982 W/ActivityThread(26612): handleWindowVisibility: no activity for token android.os.BinderProxy@18a87f3
01-27 21:44:22.021 I/TextInputLayout(26612): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-27 21:44:22.038 I/chatty  (26612): uid=10273(xyz.hisname.fireflyiii) identical 4 lines
01-27 21:44:22.040 I/TextInputLayout(26612): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-27 21:44:23.774 I/AssistStructure(26612): Flattened final assist data: 12056 bytes, containing 1 windows, 88 views
01-27 21:44:28.760 I/TextInputLayout(26612): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-27 21:44:28.780 I/chatty  (26612): uid=10273(xyz.hisname.fireflyiii) identical 4 lines
01-27 21:44:28.783 I/TextInputLayout(26612): EditText added is not a TextInputEditText. Please switch to using that class instead.
01-27 21:44:30.195 I/AssistStructure(26612): Flattened final assist data: 12056 bytes, containing 1 windows, 88 views
01-27 21:44:35.346 D/OpenGLRenderer(26612): endAllActiveAnimators on 0x70c59ab400 (DropDownListView) with handle 0x70ca18e1e0
01-27 21:44:42.450 D/AndroidRuntime(26612): Shutting down VM
--------- beginning of crash
01-27 21:44:42.451 E/AndroidRuntime(26612): FATAL EXCEPTION: main
01-27 21:44:42.451 E/AndroidRuntime(26612): Process: xyz.hisname.fireflyiii, PID: 26612
01-27 21:44:42.451 E/AndroidRuntime(26612): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List xyz.hisname.fireflyiii.repository.models.error.Errors.getTransactions_currency()' on a null object reference
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at xyz.hisname.fireflyiii.d.q.b$a.a(TransactionsViewModel.kt:5)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at xyz.hisname.fireflyiii.d.q.b$a.a(TransactionsViewModel.kt:1)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at xyz.hisname.fireflyiii.util.s.a$a.a(CallbackUtil.kt:1)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at l.i$b$a.a(DefaultCallAdapterFactory.java:4)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at l.a.run(Unknown Source:6)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at android.os.Handler.handleCallback(Handler.java:883)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at android.os.Looper.loop(Looper.java:214)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at java.lang.reflect.Method.invoke(Native Method)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-27 21:44:42.451 E/AndroidRuntime(26612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-27 21:44:42.451 E/ACRA    (26612): ACRA caught a NullPointerException for xyz.hisname.fireflyiii
01-27 21:44:42.451 E/ACRA    (26612): java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.List xyz.hisname.fireflyiii.repository.models.error.Errors.getTransactions_currency()' on a null object reference
01-27 21:44:42.451 E/ACRA    (26612): 	at xyz.hisname.fireflyiii.d.q.b$a.a(TransactionsViewModel.kt:5)
01-27 21:44:42.451 E/ACRA    (26612): 	at xyz.hisname.fireflyiii.d.q.b$a.a(TransactionsViewModel.kt:1)
01-27 21:44:42.451 E/ACRA    (26612): 	at xyz.hisname.fireflyiii.util.s.a$a.a(CallbackUtil.kt:1)
01-27 21:44:42.451 E/ACRA    (26612): 	at l.i$b$a.a(DefaultCallAdapterFactory.java:4)
01-27 21:44:42.451 E/ACRA    (26612): 	at l.a.run(Unknown Source:6)
01-27 21:44:42.451 E/ACRA    (26612): 	at android.os.Handler.handleCallback(Handler.java:883)
01-27 21:44:42.451 E/ACRA    (26612): 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-27 21:44:42.451 E/ACRA    (26612): 	at android.os.Looper.loop(Looper.java:214)
01-27 21:44:42.451 E/ACRA    (26612): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
01-27 21:44:42.451 E/ACRA    (26612): 	at java.lang.reflect.Method.invoke(Native Method)
01-27 21:44:42.451 E/ACRA    (26612): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-27 21:44:42.451 E/ACRA    (26612): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

IS_SILENT=false
USER_CRASH_DATE=2020-01-27T21:44:42.455-08:00

**Comment by lbausch** [comment]
Same here. Enabled debug log on the server and it says:
```
Going to loop 1 transaction(s)
Transaction type for validator is now Withdrawal
Now in AccountValidator::validateSource(0, "")
Now in validateWithdrawalSource(0, "")
Can we create any of these types? ["Asset account","Loan","Debt","Mortgage"]
NO, we cant create any of those.
```

**Comment by emansih** [comment]
Sorry for the late reply, I know what's the issue. Will push out a fix in a couple of hours.
