### ISSUE TITLE
Crash when trying to log in

### ISSUE THREAD

**Issue by TobiasDev** [emansih/FireflyMobile#84]
REPORT_ID=c3b52124-3730-40c1-93e9-309f643c990a
APP_VERSION_NAME=2.0.1
PHONE_MODEL=ONEPLUS A3003
BRAND=OnePlus
PRODUCT=lineage_oneplus3
ANDROID_VERSION=9
BUILD_CONFIG=
STACK_TRACE=kotlinx.coroutines.z: Exception in completion handler InvokeOnCompletion[o1@4c073ec] for f2{Completed}@dcb73b5
	at kotlinx.coroutines.w1.b(JobSupport.kt:39)
	at kotlinx.coroutines.w1.a(JobSupport.kt:53)
	at kotlinx.coroutines.w1.a(JobSupport.kt:31)
	at kotlinx.coroutines.w1.c(JobSupport.kt:17)
	at kotlinx.coroutines.w1.b(JobSupport.kt:28)
	at kotlinx.coroutines.w1.e(JobSupport.kt:2)
	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
	at g.y.i.a.a.a(ContinuationImpl.kt:10)
	at kotlinx.coroutines.v0.run(DispatchedTask.kt:15)
	at kotlinx.coroutines.s2.a.a(CoroutineScheduler.kt:58)
	at kotlinx.coroutines.s2.a$b.a(CoroutineScheduler.kt:25)
	at kotlinx.coroutines.s2.a$b.f(CoroutineScheduler.kt:4)
	at kotlinx.coroutines.s2.a$b.run(CoroutineScheduler.kt:1)
Caused by: java.lang.IllegalStateException: Cannot invoke setValue on a background thread
	at androidx.lifecycle.LiveData.a(LiveData.java:34)
	at androidx.lifecycle.LiveData.b(LiveData.java:11)
	at androidx.lifecycle.w.b(MutableLiveData.java:1)
	at xyz.hisname.fireflyiii.d.h.a$b.a(AuthViewModel.kt:9)
	at xyz.hisname.fireflyiii.d.h.a$b.a(AuthViewModel.kt:1)
	at kotlinx.coroutines.o1.b(JobSupport.kt:1)
	at kotlinx.coroutines.w1.b(JobSupport.kt:37)
	... 12 more

LOGCAT=--------- beginning of main
02-04 15:44:07.316 W/ListPreference( 4279): Setting a summary with a String formatting marker is no longer supported. You should use a SummaryProvider instead.
02-04 15:44:09.232 W/InputEventReceiver( 4279): Attempted to finish an input event but the input event receiver has already been disposed.
02-04 15:44:10.712 W/ActivityThread( 4279): handleWindowVisibility: no activity for token android.os.BinderProxy@210df6f
02-04 15:44:10.794 D/OpenGLRenderer( 4279): endAllActiveAnimators on 0x7c3891d400 (RippleDrawable) with handle 0x7c3949a960
02-04 15:44:11.311 W/ActivityThread( 4279): handleWindowVisibility: no activity for token android.os.BinderProxy@4362d40
02-04 15:44:11.348 W/ActivityThread( 4279): handleWindowVisibility: no activity for token android.os.BinderProxy@acf6670
02-04 15:45:10.499 I/AssistStructure( 4279): Flattened final assist data: 7876 bytes, containing 2 windows, 29 views
02-04 15:45:11.366 D/OpenGLRenderer( 4279): endAllActiveAnimators on 0x7c3c4bff00 (RippleDrawable) with handle 0x7c3b328460
02-04 15:45:12.800 I/AssistStructure( 4279): Flattened final assist data: 8032 bytes, containing 2 windows, 29 views
02-04 15:45:15.246 I/AssistStructure( 4279): Flattened final assist data: 7792 bytes, containing 1 windows, 28 views
02-04 15:45:21.260 D/OpenGLRenderer( 4279): endAllActiveAnimators on 0x7c395ed500 (RippleDrawable) with handle 0x7c3949a760
02-04 15:45:43.668 W/IInputConnectionWrapper( 4279): clearMetaKeyStates on inactive InputConnection
02-04 15:45:43.671 W/IInputConnectionWrapper( 4279): clearMetaKeyStates on inactive InputConnection
02-04 15:45:44.139 D/AutofillManager( 4279): onActivityFinishing(): calling cancelLocked()
02-04 15:45:44.867 W/ActivityThread( 4279): handleWindowVisibility: no activity for token android.os.BinderProxy@92a0ce
02-04 15:45:44.930 W/ActivityThread( 4279): handleWindowVisibility: no activity for token android.os.BinderProxy@f4ed97e
02-04 15:53:22.920 I/AssistStructure( 4279): Flattened final assist data: 7876 bytes, containing 2 windows, 29 views
02-04 15:53:23.824 D/OpenGLRenderer( 4279): endAllActiveAnimators on 0x7c386c2400 (RippleDrawable) with handle 0x7c3a79a940
02-04 15:53:24.243 I/AssistStructure( 4279): Flattened final assist data: 7816 bytes, containing 1 windows, 28 views
02-04 15:53:25.390 I/AssistStructure( 4279): Flattened final assist data: 7816 bytes, containing 1 windows, 28 views
02-04 15:53:42.496 D/OpenGLRenderer( 4279): endAllActiveAnimators on 0x7c38f75d00 (RippleDrawable) with handle 0x7c3afec6c0
02-04 15:53:51.019 E/SpannableStringBuilder( 4279): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 15:53:51.019 E/SpannableStringBuilder( 4279): SPAN_EXCLUSIVE_EXCLUSIVE spans cannot have a zero length
02-04 15:54:09.892 E/ACRA    ( 4279): ACRA caught a z for xyz.hisname.fireflyiii
02-04 15:54:09.892 E/ACRA    ( 4279): kotlinx.coroutines.z: Exception in completion handler InvokeOnCompletion[o1@4c073ec] for f2{Completed}@dcb73b5
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.w1.b(JobSupport.kt:39)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.w1.a(JobSupport.kt:53)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.w1.a(JobSupport.kt:31)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.w1.c(JobSupport.kt:17)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.w1.b(JobSupport.kt:28)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.w1.e(JobSupport.kt:2)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.a.a(AbstractCoroutine.kt:2)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at g.y.i.a.a.a(ContinuationImpl.kt:10)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.v0.run(DispatchedTask.kt:15)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.s2.a.a(CoroutineScheduler.kt:58)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.s2.a$b.a(CoroutineScheduler.kt:25)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.s2.a$b.f(CoroutineScheduler.kt:4)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.s2.a$b.run(CoroutineScheduler.kt:1)
02-04 15:54:09.892 E/ACRA    ( 4279): Caused by: java.lang.IllegalStateException: Cannot invoke setValue on a background thread
02-04 15:54:09.892 E/ACRA    ( 4279): 	at androidx.lifecycle.LiveData.a(LiveData.java:34)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at androidx.lifecycle.LiveData.b(LiveData.java:11)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at androidx.lifecycle.w.b(MutableLiveData.java:1)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at xyz.hisname.fireflyiii.d.h.a$b.a(AuthViewModel.kt:9)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at xyz.hisname.fireflyiii.d.h.a$b.a(AuthViewModel.kt:1)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.o1.b(JobSupport.kt:1)
02-04 15:54:09.892 E/ACRA    ( 4279): 	at kotlinx.coroutines.w1.b(JobSupport.kt:37)
02-04 15:54:09.892 E/ACRA    ( 4279): 	... 12 more

IS_SILENT=false
USER_CRASH_DATE=2020-02-04T15:54:09.910+01:00

**Comment by emansih** [comment]
Can you tell me how to replicate the bug? Thanks

**Comment by TobiasDev** [comment]
I just tried logging in with Oauth, and when I wanted to go back to the app it crasched

**Comment by chickenskitchen** [comment]
I had this problem too with 2.0.1 and Firefly 5.0.4, but it only crashed for me on the first login attempt. Afterwards, the app worked just fine. Can post my crash log if you want.

**Comment by emansih** [comment]
sorry, I am busy these couple of days. Will take a look during the weekends.
