### ISSUE TITLE
Unable to connect to my server using tor

### ISSUE THREAD

**Issue by oliverpink** [emansih/FireflyMobile#86]
**Firefly III Server Version:**
5.1.0
**Firefly III Mobile Version:**
2.0.3
**Android Version:**  
9.0 LineageOS 16 official with root and microG
**Device Information:**  
- BRAND: Motorola
- MODEL: Moto G7
--------------------------------------

## Expected Behavior
The app logins to the server
## Current Behavior
The app throws the error
```
android_getaddrinfo failed: 
EAI_NODATA (No address associated with hostname)
```
## Steps to Reproduce
1. Make the server accessible through tor
2. Connect to the service using your hidden service address.
## Comment
The server is accessible from the browser and functioning properly. I am trying to login using Person Access Token and url (http://abrakadabra...onion).

**Comment by emansih** [comment]
Your situation is really unique. Can I email you an APK later this week which will print out sensitive debugging logs? Is your email `pgp.im [at] pm.me`?

**Comment by oliverpink** [comment]
Sure, go ahead :)

**Comment by emansih** [comment]
Could you try out this APK? https://drive.google.com/open?id=1GOaiK0zw6Oe6Rs948PhUxYRj-d9hJ8Xc. I am assuming you are using port 9050 for your onion service?

**Comment by oliverpink** [comment]
Thank you for the fast response. I tried the APK with checked checkbox and, unfortunately, it didn't work. I get the same error as I did earlier. I also didn't see any debugging info appearing anywhere.

> I am assuming you are using port 9050 for your onion service?

Sorry, I think I didn't understand your question. On my phone I use Orbot, and, as far as I know, it uses this port by default to connect apps to Tor network. On my server, however, the port is closed since there are no apps using it. My service is exposed on port 80.

I tried to capture packages on my phone, and it seems the app doesn't make any requests when I click the "SIGN IN" button and just throws the error. Also, I used "MatLog Libre" (shows system logs, the app is from F-droid), but I didn't find anything in logs related to the application.

**Comment by emansih** [comment]
Just to be clear. Is this your setup? `Your phone` -> `TOR` -> `Internet` -> `Your server`

**Comment by emansih** [comment]
Anyway you can't see any logs because all logs are stripped on all of my production builds.

**Comment by oliverpink** [comment]
> Just to be clear. Is this your setup? `Your phone` -> `TOR` -> `Internet` -> `Your server`

Yes.



> Anyway you can't see any logs because all logs are stripped on all of my production builds.

Ah, I didn't understand you properly then. I thought it will display logs to me :P

**Comment by oliverpink** [comment]
The log:

`REPORT_ID=d350d0e5-59bb-4d9a-8d1e-ad06a35f229a APP_VERSION_NAME=2.0.3 PHONE_MODEL=moto g(7) BRAND=motorola PRODUCT=river ANDROID_VERSION=9 BUILD_CONFIG= STACK_TRACE=g.t: lateinit property fileUri has not been initialized 	at xyz.hisname.fireflyiii.ui.onboarding.d.c(PatFragment.kt:1) 	at xyz.hisname.fireflyiii.ui.onboarding.d$h.onClick(PatFragment.kt:13) 	at android.view.View.performClick(View.java:6597) 	at android.view.View.performClickInternal(View.java:6574) 	at android.view.View.access$3100(View.java:778) 	at android.view.View$PerformClick.run(View.java:25906) 	at android.os.Handler.handleCallback(Handler.java:873) 	at android.os.Handler.dispatchMessage(Handler.java:99) 	at android.os.Looper.loop(Looper.java:193) 	at android.app.ActivityThread.main(ActivityThread.java:6718) 	at java.lang.reflect.Method.invoke(Native Method) 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) LOGCAT=--------- beginning of main 03-08 16:18:13.487 I/MultiDex(18165): VM with version 2.1.0 has multidex support 03-08 16:18:13.487 I/MultiDex(18165): Installing application 03-08 16:18:13.487 I/MultiDex(18165): VM has multidex support, MultiDex support library is disabled. 03-08 16:18:13.570 I/ACRA (18165): ACRA is enabled for xyz.hisname.fireflyiii, initializing... 03-08 16:18:13.600 W/ActivityThread(18165): handleWindowVisibility: no activity for token android.os.BinderProxy@91d4084 03-08 16:18:13.668 D/OpenGLRenderer(18165): Skia GL Pipeline 03-08 16:18:13.697 I/Adreno (18165): QUALCOMM build : 94a5458, I21281c58c8 03-08 16:18:13.697 I/Adreno (18165): Build Date : 12/18/18 03-08 16:18:13.697 I/Adreno (18165): OpenGL ES Shader Compiler Version: EV031.25.03.02 03-08 16:18:13.697 I/Adreno (18165): Local Branch : 03-08 16:18:13.697 I/Adreno (18165): Remote Branch : refs/tags/AU_LINUX_ANDROID_LA.UM.7.6.2.R1.09.00.00.463.046 03-08 16:18:13.697 I/Adreno (18165): Remote Branch : NONE 03-08 16:18:13.697 I/Adreno (18165): Reconstruct Branch : NOTHING 03-08 16:18:13.697 I/Adreno (18165): Build Config : S L 6.0.7 AArch64 03-08 16:18:13.703 I/Adreno (18165): PFP: 0x005ff112, ME: 0x005ff066 03-08 16:18:13.708 I/ConfigStore(18165): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 1 03-08 16:18:13.708 I/ConfigStore(18165): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0 03-08 16:18:13.709 I/OpenGLRenderer(18165): Initialized EGL, version 1.4 03-08 16:18:13.709 D/OpenGLRenderer(18165): Swap behavior 2 03-08 16:19:50.811 I/AssistStructure(18165): Flattened final assist data: 4768 bytes, containing 1 windows, 16 views 03-08 16:20:19.430 D/OpenGLRenderer(18165): endAllActiveAnimators on 0x724e727100 (RippleDrawable) with handle 0x724f82d740 03-08 16:20:50.712 D/OpenGLRenderer(18165): endAllActiveAnimators on 0x724e6f9c00 (RippleDrawable) with handle 0x724fbfef40 03-08 16:20:54.641 D/NetworkSecurityConfig(18165): Using Network Security Config from resource network_security_config debugBuild: false 03-08 16:23:28.324 D/OpenGLRenderer(18165): endAllActiveAnimators on 0x724e676600 (RippleDrawable) with handle 0x724f86e720 03-08 16:24:51.536 D/AndroidRuntime(18165): Shutting down VM --------- beginning of crash 03-08 16:24:51.536 E/AndroidRuntime(18165): FATAL EXCEPTION: main 03-08 16:24:51.536 E/AndroidRuntime(18165): Process: xyz.hisname.fireflyiii, PID: 18165 03-08 16:24:51.536 E/AndroidRuntime(18165): g.t: lateinit property fileUri has not been initialized 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at xyz.hisname.fireflyiii.ui.onboarding.d.c(PatFragment.kt:1) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at xyz.hisname.fireflyiii.ui.onboarding.d$h.onClick(PatFragment.kt:13) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at android.view.View.performClick(View.java:6597) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at android.view.View.performClickInternal(View.java:6574) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at android.view.View.access$3100(View.java:778) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at android.view.View$PerformClick.run(View.java:25906) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at android.os.Handler.handleCallback(Handler.java:873) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at android.os.Handler.dispatchMessage(Handler.java:99) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at android.os.Looper.loop(Looper.java:193) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at android.app.ActivityThread.main(ActivityThread.java:6718) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at java.lang.reflect.Method.invoke(Native Method) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 03-08 16:24:51.536 E/AndroidRuntime(18165): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 03-08 16:24:51.536 E/ACRA (18165): ACRA caught a t for xyz.hisname.fireflyiii 03-08 16:24:51.536 E/ACRA (18165): g.t: lateinit property fileUri has not been initialized 03-08 16:24:51.536 E/ACRA (18165): 	at xyz.hisname.fireflyiii.ui.onboarding.d.c(PatFragment.kt:1) 03-08 16:24:51.536 E/ACRA (18165): 	at xyz.hisname.fireflyiii.ui.onboarding.d$h.onClick(PatFragment.kt:13) 03-08 16:24:51.536 E/ACRA (18165): 	at android.view.View.performClick(View.java:6597) 03-08 16:24:51.536 E/ACRA (18165): 	at android.view.View.performClickInternal(View.java:6574) 03-08 16:24:51.536 E/ACRA (18165): 	at android.view.View.access$3100(View.java:778) 03-08 16:24:51.536 E/ACRA (18165): 	at android.view.View$PerformClick.run(View.java:25906) 03-08 16:24:51.536 E/ACRA (18165): 	at android.os.Handler.handleCallback(Handler.java:873) 03-08 16:24:51.536 E/ACRA (18165): 	at android.os.Handler.dispatchMessage(Handler.java:99) 03-08 16:24:51.536 E/ACRA (18165): 	at android.os.Looper.loop(Looper.java:193) 03-08 16:24:51.536 E/ACRA (18165): 	at android.app.ActivityThread.main(ActivityThread.java:6718) 03-08 16:24:51.536 E/ACRA (18165): 	at java.lang.reflect.Method.invoke(Native Method) 03-08 16:24:51.536 E/ACRA (18165): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491) 03-08 16:24:51.536 E/ACRA (18165): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) IS_SILENT=false USER_CRASH_DATE=2020-03-08T16:24:51.543+03:00`

**Comment by emansih** [comment]
Are you using self signed cert?

**Comment by oliverpink** [comment]
No, I didn't. I am not sure if there is a place to get one. 🤔 I run a few other different services and they work just fine.

**Comment by oliverpink** [comment]
> Just to be clear. Is this your setup? `Your phone` -> `TOR` -> `Internet` -> `Your server`

Ough, I just noticed that I wrote you a wrong answer. Sorry about that. As I noted in the issue, I try to connect to my service using onion address, therefore my server is never exposed to the clearnet.

So the setup is `My Phone` -> `Tor` -> ` My Server`.

**Comment by fabianski7** [comment]
I did the access test using [InviZible Pro](https://github.com/Gedsh/InviZible) to access the Tor network and it worked partially. 
In root mode, no problem.
But in VPN mode, that error is displayed: `stream was reset: INTERNAL_ERROR`
[Those were the logs captured](https://bin.privacytools.io/?64f367a599c59f48#9gVzS4PXdINmb1Iy9y5kKheSM6vHV2YTedt0ALlg5d8=)
I didn't try to create a new connection, I just used the one that already existed

**Comment by emansih** [comment]
@fabianski7 your logs does not tell me anything. I tried using InviZible Pro and I was able to access my self hosted Firefly and the demo site

**Comment by emansih** [comment]
Accessing my personal Firefly III instance over tor onion service. 

![screenshot](https://user-images.githubusercontent.com/5896415/85936189-7d9ef580-b93b-11ea-963b-5862e8aeab85.png)

**Comment by fabianski7** [comment]
> @fabianski7 your logs does not tell me anything. I tried using InviZible Pro and I was able to access my self hosted Firefly and the demo site

Yes, I did too. But not in vpn mode.

**Comment by emansih** [comment]
if you are using http in your onion url it will not work without some modifications to the source code
