### ISSUE TITLE
Can't use biometric scanner

### ISSUE THREAD

**Issue by acmzero** [emansih/FireflyMobile#90]
**Firefly III Server Version:**
Version 5.2.2
. 
**Firefly III Mobile Version:**
2.0.3

**Android Version:**  
10

**Device Information:**  
Samsung galaxy S10 +
- BRAND: Samsung
- MODEL: Galaxy S10 +
--------------------------------------

## Expected Behavior
App should be able to unlock and launch using biometric scanner
## Current Behavior
App doesn't get launched and it seems like it's sharing some information
## Steps to Reproduce
Set biometric scan
Close the app (from task manager if possible)
Launch app and scan valid fingerprint.

(If I hover and put new transaction it seems to work, this is my workaround)

![Screen_Recording_20200420-151055](https://user-images.githubusercontent.com/1408256/79796871-e7879700-831b-11ea-8c58-f61524c9e032.gif)

**Comment by emansih** [comment]
can you share the Firefly-iii.txt file? Samsung devices are notorious for biometric bugs

**Comment by gtrubach** [comment]
Hi @emansih, I have the same issue on Samsung device.
Here is crash log:
```
REPORT_ID=0479550a-880f-4445-8329-cac01617ebb1
APP_VERSION_NAME=2.0.7
PHONE_MODEL=SM-G980F
BRAND=samsung
PRODUCT=x1sser
ANDROID_VERSION=10
BUILD_CONFIG=
STACK_TRACE=java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at androidx.fragment.app.m.n(FragmentManager.java:2)
	at androidx.fragment.app.m.Q(FragmentManager.java:5)
	at androidx.fragment.app.a.w(BackStackRecord.java:12)
	at androidx.fragment.app.a.i(BackStackRecord.java:1)
	at xyz.hisname.fireflyiii.ui.HomeActivity.i0(HomeActivity.kt:30)
	at xyz.hisname.fireflyiii.ui.HomeActivity.d0(HomeActivity.kt:1)
	at xyz.hisname.fireflyiii.ui.HomeActivity.U(HomeActivity.kt:1)
	at xyz.hisname.fireflyiii.ui.HomeActivity$f.j(HomeActivity.kt:1)
	at xyz.hisname.fireflyiii.ui.HomeActivity$f.E(HomeActivity.kt:1)
	at xyz.hisname.fireflyiii.util.p.b$a.c(Authenticator.kt:2)
	at androidx.biometric.a$b$b.run(BiometricFragment.java:1)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8016)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)

LOGCAT=07-12 22:44:35.940 D/ViewRootImpl@221db04[HomeActivity](31738): Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)0 dur=5 res=0x1 s={true 539110903808} ch=false
07-12 22:44:35.940 D/ViewRootImpl@221db04[HomeActivity](31738): MSG_RESIZED: frame=(0,0,1080,2400) ci=(0,78,0,144) vi=(0,78,0,144) or=1
07-12 22:44:35.940 D/ViewRootImpl@221db04[HomeActivity](31738): MSG_WINDOW_FOCUS_CHANGED 1 1
07-12 22:44:35.940 D/InputMethodManager(31738): prepareNavigationBarInfo() DecorView@b05b21d[HomeActivity]
07-12 22:44:35.940 D/InputMethodManager(31738): getNavigationBarColor() -16777216
07-12 22:44:35.942 D/InputMethodManager(31738): prepareNavigationBarInfo() DecorView@b05b21d[HomeActivity]
07-12 22:44:35.942 D/InputMethodManager(31738): getNavigationBarColor() -16777216
07-12 22:44:35.942 V/InputMethodManager(31738): Starting input: tba=xyz.hisname.fireflyiii ic=null mNaviBarColor -16777216 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
07-12 22:44:35.942 D/InputMethodManager(31738): startInputInner - Id : 0
07-12 22:44:35.942 I/InputMethodManager(31738): startInputInner - mService.startInputOrWindowGainedFocus
07-12 22:44:35.950 D/ViewRootImpl@221db04[HomeActivity](31738): MSG_WINDOW_FOCUS_CHANGED 0 1
07-12 22:44:35.950 D/InputMethodManager(31738): prepareNavigationBarInfo() DecorView@b05b21d[HomeActivity]
07-12 22:44:35.950 D/InputMethodManager(31738): getNavigationBarColor() -16777216
07-12 22:44:36.580 D/OpenGLRenderer(31738): makeCurrent EglSurface : 0x7cf6e17a00 -> 0x0
07-12 22:44:36.580 D/OpenGLRenderer(31738): destroyEglSurface : 0x7cf6e17a00
07-12 22:44:36.580 I/mali_egl(31738): eglDestroySurface() in
07-12 22:44:36.583 I/mali_winsys(31738): delete_surface() [1080x2400] return
07-12 22:44:36.583 I/mali_egl(31738): eglDestroySurface() out
07-12 22:44:36.583 W/libEGL  (31738): EGLNativeWindowType 0x7c6b70c410 disconnect failed
07-12 22:44:36.583 D/OpenGLRenderer(31738): ~ReliableSurface : 0x7c6b70c400
07-12 22:44:36.585 D/ViewRootImpl@221db04[HomeActivity](31738): Relayout returned: old=(0,0,1080,2400) new=(0,0,1080,2400) req=(1080,2400)8 dur=2 res=0x5 s={false 0} ch=true
07-12 22:44:36.586 D/ViewRootImpl@221db04[HomeActivity](31738): stopped(true) old=false
07-12 22:44:38.484 D/BiometricPrompt(31738): onAuthenticationSucceeded
07-12 22:44:38.532 D/AndroidRuntime(31738): Shutting down VM
--------- beginning of crash
07-12 22:44:38.532 E/AndroidRuntime(31738): FATAL EXCEPTION: main
07-12 22:44:38.532 E/AndroidRuntime(31738): Process: xyz.hisname.fireflyiii, PID: 31738
07-12 22:44:38.532 E/AndroidRuntime(31738): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at androidx.fragment.app.m.n(FragmentManager.java:2)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at androidx.fragment.app.m.Q(FragmentManager.java:5)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at androidx.fragment.app.a.w(BackStackRecord.java:12)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at androidx.fragment.app.a.i(BackStackRecord.java:1)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity.i0(HomeActivity.kt:30)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity.d0(HomeActivity.kt:1)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity.U(HomeActivity.kt:1)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity$f.j(HomeActivity.kt:1)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity$f.E(HomeActivity.kt:1)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at xyz.hisname.fireflyiii.util.p.b$a.c(Authenticator.kt:2)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at androidx.biometric.a$b$b.run(BiometricFragment.java:1)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at android.os.Handler.handleCallback(Handler.java:883)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at android.os.Looper.loop(Looper.java:237)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-12 22:44:38.532 E/AndroidRuntime(31738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
07-12 22:44:38.532 E/ACRA    (31738): ACRA caught a IllegalStateException for xyz.hisname.fireflyiii
07-12 22:44:38.532 E/ACRA    (31738): java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
07-12 22:44:38.532 E/ACRA    (31738): 	at androidx.fragment.app.m.n(FragmentManager.java:2)
07-12 22:44:38.532 E/ACRA    (31738): 	at androidx.fragment.app.m.Q(FragmentManager.java:5)
07-12 22:44:38.532 E/ACRA    (31738): 	at androidx.fragment.app.a.w(BackStackRecord.java:12)
07-12 22:44:38.532 E/ACRA    (31738): 	at androidx.fragment.app.a.i(BackStackRecord.java:1)
07-12 22:44:38.532 E/ACRA    (31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity.i0(HomeActivity.kt:30)
07-12 22:44:38.532 E/ACRA    (31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity.d0(HomeActivity.kt:1)
07-12 22:44:38.532 E/ACRA    (31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity.U(HomeActivity.kt:1)
07-12 22:44:38.532 E/ACRA    (31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity$f.j(HomeActivity.kt:1)
07-12 22:44:38.532 E/ACRA    (31738): 	at xyz.hisname.fireflyiii.ui.HomeActivity$f.E(HomeActivity.kt:1)
07-12 22:44:38.532 E/ACRA    (31738): 	at xyz.hisname.fireflyiii.util.p.b$a.c(Authenticator.kt:2)
07-12 22:44:38.532 E/ACRA    (31738): 	at androidx.biometric.a$b$b.run(BiometricFragment.java:1)
07-12 22:44:38.532 E/ACRA    (31738): 	at android.os.Handler.handleCallback(Handler.java:883)
07-12 22:44:38.532 E/ACRA    (31738): 	at android.os.Handler.dispatchMessage(Handler.java:100)
07-12 22:44:38.532 E/ACRA    (31738): 	at android.os.Looper.loop(Looper.java:237)
07-12 22:44:38.532 E/ACRA    (31738): 	at android.app.ActivityThread.main(ActivityThread.java:8016)
07-12 22:44:38.532 E/ACRA    (31738): 	at java.lang.reflect.Method.invoke(Native Method)
07-12 22:44:38.532 E/ACRA    (31738): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-12 22:44:38.532 E/ACRA    (31738): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1076)
07-12 22:44:38.535 W/ExifInterface(31738): Invalid image: ExifInterface got an unsupported image format file(ExifInterface supports JPEG and some RAW image formats only) or a corrupted JPEG file to ExifInterface.
07-12 22:44:38.535 W/ExifInterface(31738): java.io.IOException: Invalid byte order: 5249
07-12 22:44:38.535 W/ExifInterface(31738): 	at android.media.ExifInterface.readByteOrder(ExifInterface.java:3135)
07-12 22:44:38.535 W/ExifInterface(31738): 	at android.media.ExifInterface.isOrfFormat(ExifInterface.java:2443)
07-12 22:44:38.535 W/ExifInterface(31738): 	at android.media.ExifInterface.getMimeType(ExifInterface.java:2321)
07-12 22:44:38.535 W/ExifInterface(31738): 	at android.media.ExifInterface.loadAttributes(ExifInterface.java:1755)
07-12 22:44:38.535 W/ExifInterface(31738): 	at android.media.ExifInterface.<init>(ExifInterface.java:1449)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.q.d.q.b(ExifInterfaceImageHeaderParser.java:1)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.f.a(ImageHeaderParserUtils.java:6)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.q.d.n.f(Downsampler.java:6)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.q.d.n.e(Downsampler.java:12)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.q.d.n.d(Downsampler.java:1)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.q.d.g.c(ByteBufferBitmapDecoder.java:2)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.q.d.g.a(ByteBufferBitmapDecoder.java:1)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.i.c(DecodePath.java:6)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.i.b(DecodePath.java:2)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.i.a(DecodePath.java:1)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.t.b(LoadPath.java:3)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.t.a(LoadPath.java:2)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.h.z(DecodeJob.java:3)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.h.h(DecodeJob.java:2)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.h.g(DecodeJob.java:3)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.h.i(DecodeJob.java:3)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.h.f(DecodeJob.java:10)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.w.d(ResourceCacheGenerator.java:1)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.p.d$a.f(ByteBufferFileLoader.java:2)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.w.e(ResourceCacheGenerator.java:17)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.h.y(DecodeJob.java:4)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.h.A(DecodeJob.java:7)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.h.run(DecodeJob.java:7)
07-12 22:44:38.535 W/ExifInterface(31738): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-12 22:44:38.535 W/ExifInterface(31738): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-12 22:44:38.535 W/ExifInterface(31738): 	at java.lang.Thread.run(Thread.java:919)
07-12 22:44:38.535 W/ExifInterface(31738): 	at com.bumptech.glide.load.o.c0.a$a$a.run(GlideExecutor.java:6)
IS_SILENT=false
USER_CRASH_DATE=2020-07-12T22:44:38.537+03:00
```

**Comment by emansih** [comment]
Found [this issue](https://issuetracker.google.com/issues/140447194) on Google's bug tracker. I have added a guard against this.

**Comment by emansih** [comment]
@gtrubach can you test this APK? https://drive.google.com/file/d/1WlwwO2ZtBjO62YWZjqA9iqOct53-GIJq/view?usp=sharing

**Comment by gtrubach** [comment]
@emansih - tried, seems to be working great!

**Comment by emansih** [comment]
are you able to enable biometric in the app or is it disabled?

**Comment by gtrubach** [comment]
It's enabled and I was able to unlock with biometric without any errors.

**Comment by emansih** [comment]
nice. thanks for your feedback. I will close this issue
