### ISSUE TITLE
 Trust anchor for certification path not found 

### ISSUE THREAD

**Issue by M-Gregoire** [emansih/FireflyMobile#93]
**Firefly III Server Version:**
5.2.4
**Firefly III Mobile Version:**
2.0.3

**Android Version:**  
Android 10

## Current Behavior

I have a self hosted instance of Firefly III behind a HTTPS reverse proxy.
The exposed certificate is not self-signed but is signed with a Root Certificate I own (So this one is self signed):

```
[My root certificate (Self signed)] --->Signed [Certificate for firefly.domain.local]. 
```

The root certificate has been added to the Android store and my browser store as well.

Just to be sure, an extract of `openssl s_client -connect firefly.domain.local:443`:
```
depth=1 C = EU, ST = FR, O = Local Corp., CN = domain.local
verify return:1
depth=0 C = EU, ST = FR, O = Local Corp., CN = firefly.domain.local
verify return:1
---
Certificate chain
 0 s:C = EU, ST = FR, O = Local Corp., CN = firefly.domain.local
   i:C = EU, ST = FR, O = Local Corp., CN = domain.local
---
```
I've tried using your application but it always crash with the following log:
```
STACK_TRACE=java.lang.NullPointerException
	at java.io.File.<init>(File.java:283)
	at xyz.hisname.fireflyiii.ui.onboarding.b$d.onClick(LoginFragment.kt:12)
	at android.view.View.performClick(View.java:7140)
	at android.view.View.performClickInternal(View.java:7117)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27351)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

LOGCAT=05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.h.f.a(RealConnection.java:94)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.h.f.a(RealConnection.java:73)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.h.f.a(RealConnection.java:15)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.h.e.a(ExchangeFinder.java:51)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.h.e.a(ExchangeFinder.java:12)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.h.e.a(ExchangeFinder.java:6)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.h.k.a(Transmitter.java:23)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.h.b.a(ConnectInterceptor.java:5)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:11)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:2)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.g.a.a(CacheInterceptor.java:22)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:11)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:2)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.a.a(BridgeInterceptor.java:22)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:11)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.j.a(RetryAndFollowUpInterceptor.java:6)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:11)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:2)
05-01 19:11:16.494 E/ACRA    (15461): 	at xyz.hisname.fireflyiii.util.s.c.a(HeaderInterceptor.kt:8)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:11)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.i.g.a(RealInterceptorChain.java:2)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.f0.a(RealCall.java:24)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.f0$a.b(RealCall.java:2)
05-01 19:11:16.494 E/ACRA    (15461): 	at i.n0.d.run(NamedRunnable.java:3)
05-01 19:11:16.494 E/ACRA    (15461): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-01 19:11:16.494 E/ACRA    (15461): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-01 19:11:16.494 E/ACRA    (15461): 	at java.lang.Thread.run(Thread.java:919)
05-01 19:11:16.494 E/ACRA    (15461): Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:658)
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
05-01 19:11:16.494 E/ACRA    (15461): 	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
05-01 19:11:16.494 E/ACRA    (15461): 	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
05-01 19:11:16.494 E/ACRA    (15461): 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
05-01 19:11:16.494 E/ACRA    (15461): 	... 27 more
05-01 19:11:16.494 E/ACRA    (15461): Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
05-01 19:11:16.494 E/ACRA    (15461): 	... 38 more
05-01 19:11:16.652 I/ACRA    (15461): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2020-05-01T19:11:16.503+02:00.stacktrace
05-01 19:11:16.670 I/Process (15461): Sending signal. PID: 15461 SIG: 9
05-01 19:11:17.150 E/DatabaseUtils(14077): Writing exception to parcel
05-01 19:11:17.150 E/DatabaseUtils(14077): java.lang.SecurityException: Permission Denial: reading org.acra.attachment.AcraContentProvider uri content://xyz.hisname.fireflyiii.acra/root/data/user/0/xyz.hisname.fireflyiii/cache/Fireflyiii-mobile.txt from pid=14047, uid=1000 requires the provider be exported, or grantUriPermission()
05-01 19:11:17.150 E/DatabaseUtils(14077): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
05-01 19:11:17.150 E/DatabaseUtils(14077): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
05-01 19:11:17.150 E/DatabaseUtils(14077): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
05-01 19:11:17.150 E/DatabaseUtils(14077): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
05-01 19:11:17.150 E/DatabaseUtils(14077): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
05-01 19:11:17.150 E/DatabaseUtils(14077): 	at android.os.Binder.execTransact(Binder.java:994)
05-01 19:15:13.798 I/MultiDex(16161): VM with version 2.1.0 has multidex support
05-01 19:15:13.798 I/MultiDex(16161): Installing application
05-01 19:15:13.798 I/MultiDex(16161): VM has multidex support, MultiDex support library is disabled.
05-01 19:15:13.811 I/ashmem  (16161): memfd: device VNDK version (28) is < Q so using ashmem.
05-01 19:15:13.861 I/ACRA    (16161): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
05-01 19:15:13.884 W/ActivityThread(16161): handleWindowVisibility: no activity for token android.os.BinderProxy@7b29c82
05-01 19:15:13.966 I/Adreno  (16161): QUALCOMM build                   : 6cbc6c9, Ib736691963
05-01 19:15:13.966 I/Adreno  (16161): Build Date                       : 04/25/19
05-01 19:15:13.966 I/Adreno  (16161): OpenGL ES Shader Compiler Version: EV031.26.03.01
05-01 19:15:13.966 I/Adreno  (16161): Local Branch                     : 
05-01 19:15:13.966 I/Adreno  (16161): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r81-rel
05-01 19:15:13.966 I/Adreno  (16161): Remote Branch                    : NONE
05-01 19:15:13.966 I/Adreno  (16161): Reconstruct Branch               : NOTHING
05-01 19:15:13.966 I/Adreno  (16161): Build Config                     : S P 6.0.9 AArch64
05-01 19:15:13.970 I/Adreno  (16161): PFP: 0x016ee183, ME: 0x00000000
05-01 19:15:13.995 W/Gralloc3(16161): mapper 3.x is not supported
05-01 19:25:54.821 D/AndroidRuntime(16161): Shutting down VM
05-01 19:25:54.822 E/AndroidRuntime(16161): FATAL EXCEPTION: main
05-01 19:25:54.822 E/AndroidRuntime(16161): Process: xyz.hisname.fireflyiii, PID: 16161
05-01 19:25:54.822 E/AndroidRuntime(16161): java.lang.NullPointerException
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at java.io.File.<init>(File.java:283)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at xyz.hisname.fireflyiii.ui.onboarding.b$d.onClick(LoginFragment.kt:12)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at android.view.View.performClick(View.java:7140)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at android.view.View.performClickInternal(View.java:7117)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at android.view.View.access$3500(View.java:801)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at android.view.View$PerformClick.run(View.java:27351)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at android.os.Handler.handleCallback(Handler.java:883)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at android.os.Looper.loop(Looper.java:214)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at java.lang.reflect.Method.invoke(Native Method)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-01 19:25:54.822 E/AndroidRuntime(16161): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-01 19:25:54.823 E/ACRA    (16161): ACRA caught a NullPointerException for xyz.hisname.fireflyiii
05-01 19:25:54.823 E/ACRA    (16161): java.lang.NullPointerException
05-01 19:25:54.823 E/ACRA    (16161): 	at java.io.File.<init>(File.java:283)
05-01 19:25:54.823 E/ACRA    (16161): 	at xyz.hisname.fireflyiii.ui.onboarding.b$d.onClick(LoginFragment.kt:12)
05-01 19:25:54.823 E/ACRA    (16161): 	at android.view.View.performClick(View.java:7140)
05-01 19:25:54.823 E/ACRA    (16161): 	at android.view.View.performClickInternal(View.java:7117)
05-01 19:25:54.823 E/ACRA    (16161): 	at android.view.View.access$3500(View.java:801)
05-01 19:25:54.823 E/ACRA    (16161): 	at android.view.View$PerformClick.run(View.java:27351)
05-01 19:25:54.823 E/ACRA    (16161): 	at android.os.Handler.handleCallback(Handler.java:883)
05-01 19:25:54.823 E/ACRA    (16161): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-01 19:25:54.823 E/ACRA    (16161): 	at android.os.Looper.loop(Looper.java:214)
05-01 19:25:54.823 E/ACRA    (16161): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-01 19:25:54.823 E/ACRA    (16161): 	at java.lang.reflect.Method.invoke(Native Method)
05-01 19:25:54.823 E/ACRA    (16161): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-01 19:25:54.823 E/ACRA    (16161): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I've tried:
- No using the "Self signed" option (Since root CA is in the Android store)
- Using "Self signed" option and passing a chained PEM (With both certificate)
- Using "Self signed" option and passing only the `firefly.domain.local` certificate

Do you have any idea on the way I could fix this?

**Comment by emansih** [comment]
this is an interesting edge case. how about importing both certs into Android trust store?

**Comment by emansih** [comment]
Also, check this out: https://github.com/emansih/FireflyMobile/issues/59#issuecomment-512347032

**Comment by M-Gregoire** [comment]
Thanks a lot for your answer.
Only the root certificate is imported in the Android store, and I don't believe it's possible to add a server certificate directly in the Android truststore (I tried but It ask for the private key, so I'm guessing it's trying to add it as a user certificate).

Thank you for the link you sent. I've tried using a full chain on the server side, resulting in:
```
Certificate chain
 0 s:C = EU, ST = FR, O = Local Corp., CN = firefly.domain.local
   i:C = EU, ST = FR, O = Local Corp., CN = domain.local
 1 s:C = EU, ST = FR, O = Local Corp., CN = domain.local
   i:C = EU, ST = FR, O = Local Corp., CN = domain.local
```
instead of
```
Certificate chain
 0 s:C = EU, ST = FR, O = Local Corp., CN = firefly.domain.local
   i:C = EU, ST = FR, O = Local Corp., CN = domain.local
```.

I also used `magisk` to add the root certificate as a "System certificate" and not a "User certificate" but that didn't solved my issue.

I've tried using the "Self-signed certificate" and passed my root CA but the application crash even before going to Firefox (While if I don't use the checkbox, I can login and approve the OAUTH in Firefly and get the log from the intial post).

Here is the log of this case:
```
STACK_TRACE=java.lang.NullPointerException
	at java.io.File.<init>(File.java:283)
	at xyz.hisname.fireflyiii.ui.onboarding.b$d.onClick(LoginFragment.kt:12)
	at android.view.View.performClick(View.java:7140)
	at android.view.View.performClickInternal(View.java:7117)
	at android.view.View.access$3500(View.java:801)
	at android.view.View$PerformClick.run(View.java:27351)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7356)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

LOGCAT=05-02 18:22:48.082 D/TextClassifierService( 1838): No configured system TextClassifierService
05-02 18:22:48.095 D/TextClassifierService( 1838): No configured system TextClassifierService
05-02 18:22:48.101 D/TextClassifierService( 1838): No configured system TextClassifierService
05-02 18:22:48.166 D/androidtc( 1838): Loading ModelFile { path=/etc/textclassifier/lang_id.model name=lang_id.model version=0 locales=und }
05-02 18:22:48.214 D/androidtc( 1838): Loading ModelFile { path=/etc/textclassifier/textclassifier.en.model name=textclassifier.en.model version=608 locales=en }
05-02 18:22:48.219 I/tflite  ( 1838): Initialized TensorFlow Lite runtime.
05-02 18:22:48.354 W/LabeledIntent( 1838): resolveInfo or activityInfo is null
05-02 18:22:48.342 D/TextClassifierService( 1838): No configured system TextClassifierService
05-02 18:23:06.469 D/AndroidRuntime( 1838): Shutting down VM
--------- beginning of crash
05-02 18:23:06.482 E/AndroidRuntime( 1838): FATAL EXCEPTION: main
05-02 18:23:06.482 E/AndroidRuntime( 1838): Process: xyz.hisname.fireflyiii, PID: 1838
05-02 18:23:06.482 E/AndroidRuntime( 1838): java.lang.NullPointerException
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at java.io.File.<init>(File.java:283)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at xyz.hisname.fireflyiii.ui.onboarding.b$d.onClick(LoginFragment.kt:12)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at android.view.View.performClick(View.java:7140)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at android.view.View.performClickInternal(View.java:7117)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at android.view.View.access$3500(View.java:801)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at android.view.View$PerformClick.run(View.java:27351)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at android.os.Handler.handleCallback(Handler.java:883)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at android.os.Looper.loop(Looper.java:214)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at java.lang.reflect.Method.invoke(Native Method)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-02 18:23:06.482 E/AndroidRuntime( 1838): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-02 18:23:06.482 E/ACRA    ( 1838): ACRA caught a NullPointerException for xyz.hisname.fireflyiii
05-02 18:23:06.482 E/ACRA    ( 1838): java.lang.NullPointerException
05-02 18:23:06.482 E/ACRA    ( 1838): 	at java.io.File.<init>(File.java:283)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at xyz.hisname.fireflyiii.ui.onboarding.b$d.onClick(LoginFragment.kt:12)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at android.view.View.performClick(View.java:7140)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at android.view.View.performClickInternal(View.java:7117)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at android.view.View.access$3500(View.java:801)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at android.view.View$PerformClick.run(View.java:27351)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at android.os.Handler.handleCallback(Handler.java:883)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at android.os.Looper.loop(Looper.java:214)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at java.lang.reflect.Method.invoke(Native Method)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-02 18:23:06.482 E/ACRA    ( 1838): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-02 18:23:06.573 I/ACRA    ( 1838): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2020-05-02T18:23:06.491+02:00.stacktrace
05-02 18:23:06.596 I/Process ( 1838): Sending signal. PID: 1838 SIG: 9
05-02 18:23:06.879 E/DatabaseUtils( 1750): Writing exception to parcel
05-02 18:23:06.879 E/DatabaseUtils( 1750): java.lang.SecurityException: Permission Denial: reading org.acra.attachment.AcraContentProvider uri content://xyz.hisname.fireflyiii.acra/root/data/user/0/xyz.hisname.fireflyiii/cache/Fireflyiii-mobile.txt from pid=1680, uid=1000 requires the provider be exported, or grantUriPermission()
05-02 18:23:06.879 E/DatabaseUtils( 1750): 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:729)
05-02 18:23:06.879 E/DatabaseUtils( 1750): 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:602)
05-02 18:23:06.879 E/DatabaseUtils( 1750): 	at android.content.ContentProvider$Transport.query(ContentProvider.java:231)
05-02 18:23:06.879 E/DatabaseUtils( 1750): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:104)
05-02 18:23:06.879 E/DatabaseUtils( 1750): 	at android.os.Binder.execTransactInternal(Binder.java:1021)
05-02 18:23:06.879 E/DatabaseUtils( 1750): 	at android.os.Binder.execTransact(Binder.java:994)
05-02 18:23:17.556 I/MultiDex( 2421): VM with version 2.1.0 has multidex support
05-02 18:23:17.556 I/MultiDex( 2421): Installing application
05-02 18:23:17.556 I/MultiDex( 2421): VM has multidex support, MultiDex support library is disabled.
05-02 18:23:17.567 I/ashmem  ( 2421): memfd: device VNDK version (28) is < Q so using ashmem.
05-02 18:23:17.608 I/ACRA    ( 2421): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
05-02 18:23:17.633 W/ActivityThread( 2421): handleWindowVisibility: no activity for token android.os.BinderProxy@9786b79
05-02 18:23:17.717 I/Adreno  ( 2421): QUALCOMM build                   : 6cbc6c9, Ib736691963
05-02 18:23:17.717 I/Adreno  ( 2421): Build Date                       : 04/25/19
05-02 18:23:17.717 I/Adreno  ( 2421): OpenGL ES Shader Compiler Version: EV031.26.03.01
05-02 18:23:17.717 I/Adreno  ( 2421): Local Branch                     : 
05-02 18:23:17.717 I/Adreno  ( 2421): Remote Branch                    : quic/gfx-adreno.lnx.1.0.r81-rel
05-02 18:23:17.717 I/Adreno  ( 2421): Remote Branch                    : NONE
05-02 18:23:17.717 I/Adreno  ( 2421): Reconstruct Branch               : NOTHING
05-02 18:23:17.717 I/Adreno  ( 2421): Build Config                     : S P 6.0.9 AArch64
05-02 18:23:17.723 I/Adreno  ( 2421): PFP: 0x016ee183, ME: 0x00000000
05-02 18:23:17.759 W/Gralloc3( 2421): mapper 3.x is not supported
05-02 18:23:27.735 W/InputEventReceiver( 2421): Attempted to finish an input event but the input event receiver has already been disposed.
05-02 18:23:31.941 D/AndroidRuntime( 2421): Shutting down VM
05-02 18:23:31.943 E/AndroidRuntime( 2421): FATAL EXCEPTION: main
05-02 18:23:31.943 E/AndroidRuntime( 2421): Process: xyz.hisname.fireflyiii, PID: 2421
05-02 18:23:31.943 E/AndroidRuntime( 2421): java.lang.NullPointerException
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at java.io.File.<init>(File.java:283)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at xyz.hisname.fireflyiii.ui.onboarding.b$d.onClick(LoginFragment.kt:12)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at android.view.View.performClick(View.java:7140)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at android.view.View.performClickInternal(View.java:7117)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at android.view.View.access$3500(View.java:801)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at android.view.View$PerformClick.run(View.java:27351)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at android.os.Handler.handleCallback(Handler.java:883)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at android.os.Looper.loop(Looper.java:214)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at java.lang.reflect.Method.invoke(Native Method)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-02 18:23:31.943 E/AndroidRuntime( 2421): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-02 18:23:31.943 E/ACRA    ( 2421): ACRA caught a NullPointerException for xyz.hisname.fireflyiii
05-02 18:23:31.943 E/ACRA    ( 2421): java.lang.NullPointerException
05-02 18:23:31.943 E/ACRA    ( 2421): 	at java.io.File.<init>(File.java:283)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at xyz.hisname.fireflyiii.ui.onboarding.b$d.onClick(LoginFragment.kt:12)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at android.view.View.performClick(View.java:7140)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at android.view.View.performClickInternal(View.java:7117)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at android.view.View.access$3500(View.java:801)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at android.view.View$PerformClick.run(View.java:27351)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at android.os.Handler.handleCallback(Handler.java:883)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at android.os.Handler.dispatchMessage(Handler.java:100)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at android.os.Looper.loop(Looper.java:214)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at java.lang.reflect.Method.invoke(Native Method)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-02 18:23:31.943 E/ACRA    ( 2421): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I'm sorry I can't help more, I'm not very knowledgeable about certificate usage in Android.

Thank you for your help

**Comment by emansih** [comment]
I'm not sure why it's throwing a null pointer.... Are you using crt or pem file? From the logs, I can only assume there is an issue with your cert

**Comment by M-Gregoire** [comment]
Thank you for your answer:
```
$ file mycert.pem
mycrt.pem: PEM certificate

$ openssl x509 -noout -text -in mycert.pem 
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            aa:bb:cc:dd:ee:ff:11:22
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = EU, ST = FR, O = Local Corp., CN = domain.local
        Validity
            Not Before: <Date>
            Not After : <Date>
        Subject: C = EU, ST = FR, O = Local Corp., CN = another.local.domain
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    <Modulus>
                Exponent: <Exp>
        X509v3 extensions:
            X509v3 Subject Alternative Name: 
                DNS:firefly.domain.local
    Signature Algorithm: sha256WithRSAEncryption
         <Snip>
```

As you can see, the `firefly.domain.local` is not the CN of the certificate but is in the SAN attribute, I don't believe that's the issue but I prefer to mention it.

Just to be sure, the certificate as the following format:
```
-----BEGIN CERTIFICATE-----
<Snip>
-----END CERTIFICATE-----
```

**Comment by M-Gregoire** [comment]
I've deleted the cache and the data from the Android App, added the certificates to the system store with Magisk and tried again (OAuth) and it worked!

I'm not sure what was the problem in the first place but clearing the cache and data seems to have helped.

Thank you for your assistance on this issue and for making an Android App for Firefly!

**Comment by emansih** [comment]
I forgot about this issue since I am busy with uni. Great that this works for you!
