### ISSUE TITLE
App crashes with IndexOutOfBoundsException

### ISSUE THREAD

**Issue by david-lindner** [emansih/FireflyMobile#96]
First of all, thanks for the great app!

I haven't had any issues in the past. However sice installing the latest update from FDroid, the app does not longer start on my device. When I try to open the app, I briefly see part of the UI before it crashes and return the logfile attached below. It seems like the issue is an IndexOutOfBoundsException because of an empty list? It might be a problem with my setup, but I feel like this error should be caught and it should provide a more understandable error message. 

--------------------------------------

**Firefly III Server Version:**
5.2.3

**Firefly III Mobile Version:**
2.0.5

**Android Version:**  
8.1.0

**Device Information:**  
Motorola Moto G5

--------------------------------------

# Logfile & Stacktrace

```
REPORT_ID=68017c96-2fc5-4515-b008-067eb9f1cfa3
APP_VERSION_NAME=2.0.5
PHONE_MODEL=Moto G (5)
BRAND=motorola
PRODUCT=cedric
ANDROID_VERSION=8.1.0
BUILD_CONFIG=
STACK_TRACE=java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:437)
	at xyz.hisname.fireflyiii.ui.h.a$d.a(LiveData.kt:2)
	at androidx.lifecycle.LiveData.b(LiveData.java:6)
	at androidx.lifecycle.LiveData.a(LiveData.java:8)
	at androidx.lifecycle.LiveData.b(LiveData.java:14)
	at androidx.lifecycle.w.b(MutableLiveData.java:1)
	at androidx.lifecycle.LiveData$a.run(LiveData.java:5)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6626)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

LOGCAT=06-20 09:28:17.080 E/AndroidRuntime(  406): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
06-20 09:28:17.080 E/AndroidRuntime(  406): 	at java.lang.reflect.Method.invoke(Native Method)
06-20 09:28:17.080 E/AndroidRuntime(  406): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-20 09:28:17.080 E/AndroidRuntime(  406): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
06-20 09:28:17.080 E/ACRA    (  406): ACRA caught a IndexOutOfBoundsException for xyz.hisname.fireflyiii
06-20 09:28:17.080 E/ACRA    (  406): java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
06-20 09:28:17.080 E/ACRA    (  406): 	at java.util.ArrayList.get(ArrayList.java:437)
06-20 09:28:17.080 E/ACRA    (  406): 	at xyz.hisname.fireflyiii.ui.h.a$d.a(LiveData.kt:2)
06-20 09:28:17.080 E/ACRA    (  406): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
06-20 09:28:17.080 E/ACRA    (  406): 	at androidx.lifecycle.LiveData.a(LiveData.java:8)
06-20 09:28:17.080 E/ACRA    (  406): 	at androidx.lifecycle.LiveData.b(LiveData.java:14)
06-20 09:28:17.080 E/ACRA    (  406): 	at androidx.lifecycle.w.b(MutableLiveData.java:1)
06-20 09:28:17.080 E/ACRA    (  406): 	at androidx.lifecycle.LiveData$a.run(LiveData.java:5)
06-20 09:28:17.080 E/ACRA    (  406): 	at android.os.Handler.handleCallback(Handler.java:790)
06-20 09:28:17.080 E/ACRA    (  406): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-20 09:28:17.080 E/ACRA    (  406): 	at android.os.Looper.loop(Looper.java:164)
06-20 09:28:17.080 E/ACRA    (  406): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
06-20 09:28:17.080 E/ACRA    (  406): 	at java.lang.reflect.Method.invoke(Native Method)
06-20 09:28:17.080 E/ACRA    (  406): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-20 09:28:17.080 E/ACRA    (  406): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
06-20 09:28:17.154 I/Process (  406): Sending signal. PID: 406 SIG: 9
06-20 09:28:17.161 I/ACRA    (32735): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2020-06-20T09:28:17.084+02:00.stacktrace
06-20 09:28:56.339 I/MultiDex(  839): VM with version 2.1.0 has multidex support
06-20 09:28:56.339 I/MultiDex(  839): Installing application
06-20 09:28:56.339 I/MultiDex(  839): VM has multidex support, MultiDex support library is disabled.
06-20 09:28:56.478 I/ACRA    (  839): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
06-20 09:28:56.564 W/b       (  839): Use a non-transparent color for the default color as it will be used to finish ripple animations.
06-20 09:28:56.821 D/NetworkSecurityConfig(  839): Using Network Security Config from resource network_security_config debugBuild: false
06-20 09:28:57.053 I/zygote  (  839): Do partial code cache collection, code=30KB, data=24KB
06-20 09:28:57.055 I/zygote  (  839): After code cache collection, code=30KB, data=24KB
06-20 09:28:57.055 I/zygote  (  839): Increasing code cache capacity to 128KB
06-20 09:28:57.201 I/zygote  (  839): Do partial code cache collection, code=56KB, data=44KB
06-20 09:28:57.203 I/zygote  (  839): After code cache collection, code=56KB, data=44KB
06-20 09:28:57.203 I/zygote  (  839): Increasing code cache capacity to 256KB
06-20 09:28:57.251 I/zygote  (  839): Deoptimizing android.graphics.Typeface d.g.d.c.f.a(android.content.Context, int, android.util.TypedValue, int, d.g.d.c.f$a, android.os.Handler, boolean) due to JIT inline cache
06-20 09:28:57.316 D/OpenGLRenderer(  839): HWUI GL Pipeline
06-20 09:28:57.450 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout$c.a(d.e.b.j.e, d.e.b.j.m.b$a) due to JIT inline cache
06-20 09:28:57.588 I/zygote  (  839): Do full code cache collection, code=122KB, data=95KB
06-20 09:28:57.591 I/zygote  (  839): After code cache collection, code=108KB, data=73KB
06-20 09:28:57.629 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout$c.a(d.e.b.j.e, d.e.b.j.m.b$a) due to JIT inline cache
06-20 09:28:57.649 I/zygote  (  839): Do partial code cache collection, code=114KB, data=80KB
06-20 09:28:57.651 I/zygote  (  839): After code cache collection, code=113KB, data=79KB
06-20 09:28:57.651 I/zygote  (  839): Increasing code cache capacity to 512KB
06-20 09:28:57.882 I/Adreno  (  839): QUALCOMM build                   : bb5b86c, I77d3059488
06-20 09:28:57.882 I/Adreno  (  839): Build Date                       : 06/07/18
06-20 09:28:57.882 I/Adreno  (  839): OpenGL ES Shader Compiler Version: EV031.22.00.01_06
06-20 09:28:57.882 I/Adreno  (  839): Local Branch                     : 
06-20 09:28:57.882 I/Adreno  (  839): Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.5.R1.08.01.00.312.086
06-20 09:28:57.882 I/Adreno  (  839): Remote Branch                    : NONE
06-20 09:28:57.882 I/Adreno  (  839): Reconstruct Branch               : NOTHING
06-20 09:28:57.890 D/vndksupport(  839): Loading /vendor/lib/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
06-20 09:28:57.902 I/Adreno  (  839): PFP: 0x005ff087, ME: 0x005ff063
06-20 09:28:57.908 I/zygote  (  839): android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
06-20 09:28:57.911 I/OpenGLRenderer(  839): Initialized EGL, version 1.4
06-20 09:28:57.912 D/OpenGLRenderer(  839): Swap behavior 2
06-20 09:28:57.978 E/RecyclerView(  839): No adapter attached; skipping layout
06-20 09:28:57.989 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.onMeasure(int, int) due to JIT inline cache
06-20 09:28:57.990 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.a() due to JIT inline cache
06-20 09:28:57.992 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.a(d.e.b.j.f, int, int, int) due to JIT inline cache
06-20 09:28:57.992 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.a(d.e.b.j.f, int, int, int, int) due to JIT inline cache
06-20 09:28:57.992 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout$c.a(d.e.b.j.e, d.e.b.j.m.b$a) due to JIT inline cache
06-20 09:28:57.994 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout$c.a() due to JIT inline cache
06-20 09:28:57.996 I/zygote  (  839): Deoptimizing void androidx.constraintlayout.widget.ConstraintLayout.a(int, int, int, int, boolean, boolean) due to JIT inline cache
06-20 09:28:58.103 I/Choreographer(  839): Skipped 45 frames!  The application may be doing too much work on its main thread.
06-20 09:28:58.182 D/vndksupport(  839): Loading /vendor/lib/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
06-20 09:28:58.184 D/vndksupport(  839): Loading /vendor/lib/hw/gralloc.msm8937.so from current namespace instead of sphal namespace.
06-20 09:28:58.665 D/AndroidRuntime(  839): Shutting down VM
06-20 09:28:58.666 E/AndroidRuntime(  839): FATAL EXCEPTION: main
06-20 09:28:58.666 E/AndroidRuntime(  839): Process: xyz.hisname.fireflyiii, PID: 839
06-20 09:28:58.666 E/AndroidRuntime(  839): java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at java.util.ArrayList.get(ArrayList.java:437)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at xyz.hisname.fireflyiii.ui.h.a$d.a(LiveData.kt:2)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at androidx.lifecycle.LiveData.a(LiveData.java:8)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at androidx.lifecycle.LiveData.b(LiveData.java:14)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at androidx.lifecycle.w.b(MutableLiveData.java:1)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at androidx.lifecycle.LiveData$a.run(LiveData.java:5)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at android.os.Handler.handleCallback(Handler.java:790)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at android.os.Looper.loop(Looper.java:164)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at java.lang.reflect.Method.invoke(Native Method)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-20 09:28:58.666 E/AndroidRuntime(  839): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
06-20 09:28:58.666 E/ACRA    (  839): ACRA caught a IndexOutOfBoundsException for xyz.hisname.fireflyiii
06-20 09:28:58.666 E/ACRA    (  839): java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
06-20 09:28:58.666 E/ACRA    (  839): 	at java.util.ArrayList.get(ArrayList.java:437)
06-20 09:28:58.666 E/ACRA    (  839): 	at xyz.hisname.fireflyiii.ui.h.a$d.a(LiveData.kt:2)
06-20 09:28:58.666 E/ACRA    (  839): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
06-20 09:28:58.666 E/ACRA    (  839): 	at androidx.lifecycle.LiveData.a(LiveData.java:8)
06-20 09:28:58.666 E/ACRA    (  839): 	at androidx.lifecycle.LiveData.b(LiveData.java:14)
06-20 09:28:58.666 E/ACRA    (  839): 	at androidx.lifecycle.w.b(MutableLiveData.java:1)
06-20 09:28:58.666 E/ACRA    (  839): 	at androidx.lifecycle.LiveData$a.run(LiveData.java:5)
06-20 09:28:58.666 E/ACRA    (  839): 	at android.os.Handler.handleCallback(Handler.java:790)
06-20 09:28:58.666 E/ACRA    (  839): 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-20 09:28:58.666 E/ACRA    (  839): 	at android.os.Looper.loop(Looper.java:164)
06-20 09:28:58.666 E/ACRA    (  839): 	at android.app.ActivityThread.main(ActivityThread.java:6626)
06-20 09:28:58.666 E/ACRA    (  839): 	at java.lang.reflect.Method.invoke(Native Method)
06-20 09:28:58.666 E/ACRA    (  839): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
06-20 09:28:58.666 E/ACRA    (  839): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)
IS_SILENT=false
USER_CRASH_DATE=2020-06-20T09:28:58.669+02:00
```

**Comment by emansih** [comment]
your log doesn't say much about the crash. Do you have a valid currency? Do you have a valid default currency? Do you have valid transactions?

**Comment by david-lindner** [comment]
Thanks for your help! The answer to all your questions is yes. However, I was able to fix the problem by reinstalling the app and giving it a new OAuth token. So I don't think I have a way to reproduce the issue for now, so this can be closed. In case the error reappears or I can figure out how to reproduce it, I will comment here again.

**Comment by emansih** [comment]
nice

**Comment by haho16** [comment]
Hey @emansih and @david-lindner, 

I am getting similar crashes since latest update: 

**Firefly III Server Version:**
5.2.2

**Firefly III Mobile Version:**
2.0.8

**Android Version:**
7.1.2

**Device Information:**
Xiami Redmi 4A / Lineage OS 14.1

```
REPORT_ID=c25e5b46-b0cc-43a1-b300-984c0da43382
APP_VERSION_NAME=2.0.8
PHONE_MODEL=Redmi 4A
BRAND=Xiaomi
PRODUCT=lineage_rolex
ANDROID_VERSION=7.1.2
BUILD_CONFIG=
STACK_TRACE=java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.get(ArrayList.java:411)
	at xyz.hisname.fireflyiii.ui.h.a$e.a(LiveData.kt:2)
	at androidx.lifecycle.LiveData.b(LiveData.java:6)
	at androidx.lifecycle.LiveData.c(LiveData.java:8)
	at androidx.lifecycle.LiveData.m(LiveData.java:4)
	at androidx.lifecycle.v.m(MutableLiveData.java:1)
	at androidx.lifecycle.LiveData$a.run(LiveData.java:5)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

LOGCAT=07-26 15:13:07.179 D/AppCompatDelegate(18165): updateForNightMode not recreating Activity: xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a
07-26 15:13:07.179 D/AppCompatDelegate(18165): updateForNightMode. Skipping. Night mode: 1 for host:xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a
07-26 15:13:07.303 I/art     (18165): Do partial code cache collection, code=60KB, data=59KB
07-26 15:13:07.303 I/art     (18165): After code cache collection, code=60KB, data=59KB
07-26 15:13:07.303 I/art     (18165): Increasing code cache capacity to 256KB
07-26 15:13:07.573 I/art     (18165): Do full code cache collection, code=125KB, data=115KB
07-26 15:13:07.574 I/art     (18165): Starting a blocking GC JitCodeCache
07-26 15:13:07.574 I/art     (18165): After code cache collection, code=74KB, data=68KB
07-26 15:13:07.696 I/Adreno-EGL(18165): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8937_64_LA.UM.5.5.R1__release_AU (I23cc4685e6)
07-26 15:13:07.696 I/Adreno-EGL(18165): OpenGL ES Shader Compiler Version: XE031.09.00.04
07-26 15:13:07.696 I/Adreno-EGL(18165): Build Date: 04/11/17 Tue
07-26 15:13:07.696 I/Adreno-EGL(18165): Local Branch: 
07-26 15:13:07.696 I/Adreno-EGL(18165): Remote Branch: quic/gfx-adreno.lnx.1.0.r5-rel
07-26 15:13:07.696 I/Adreno-EGL(18165): Local Patches: NONE
07-26 15:13:07.696 I/Adreno-EGL(18165): Reconstruct Branch: NOTHING
07-26 15:13:07.704 I/OpenGLRenderer(18165): Initialized EGL, version 1.4
07-26 15:13:07.704 D/OpenGLRenderer(18165): Swap behavior 1
07-26 15:13:07.789 W/RecyclerView(18165): No adapter attached; skipping layout
07-26 15:13:07.884 I/art     (18165): Do partial code cache collection, code=123KB, data=118KB
07-26 15:13:07.885 I/art     (18165): After code cache collection, code=99KB, data=103KB
07-26 15:13:07.885 I/art     (18165): Increasing code cache capacity to 512KB
07-26 15:13:07.974 I/Choreographer(18165): Skipped 43 frames!  The application may be doing too much work on its main thread.
07-26 15:13:08.184 D/AndroidRuntime(18165): Shutting down VM
07-26 15:13:08.186 E/ACRA    (18165): ACRA caught a IndexOutOfBoundsException for xyz.hisname.fireflyiii
07-26 15:13:08.186 E/ACRA    (18165): java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
07-26 15:13:08.186 E/ACRA    (18165): 	at java.util.ArrayList.get(ArrayList.java:411)
07-26 15:13:08.186 E/ACRA    (18165): 	at xyz.hisname.fireflyiii.ui.h.a$e.a(LiveData.kt:2)
07-26 15:13:08.186 E/ACRA    (18165): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
07-26 15:13:08.186 E/ACRA    (18165): 	at androidx.lifecycle.LiveData.c(LiveData.java:8)
07-26 15:13:08.186 E/ACRA    (18165): 	at androidx.lifecycle.LiveData.m(LiveData.java:4)
07-26 15:13:08.186 E/ACRA    (18165): 	at androidx.lifecycle.v.m(MutableLiveData.java:1)
07-26 15:13:08.186 E/ACRA    (18165): 	at androidx.lifecycle.LiveData$a.run(LiveData.java:5)
07-26 15:13:08.186 E/ACRA    (18165): 	at android.os.Handler.handleCallback(Handler.java:751)
07-26 15:13:08.186 E/ACRA    (18165): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-26 15:13:08.186 E/ACRA    (18165): 	at android.os.Looper.loop(Looper.java:154)
07-26 15:13:08.186 E/ACRA    (18165): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
07-26 15:13:08.186 E/ACRA    (18165): 	at java.lang.reflect.Method.invoke(Native Method)
07-26 15:13:08.186 E/ACRA    (18165): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-26 15:13:08.186 E/ACRA    (18165): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
07-26 15:13:08.278 I/Process (18165): Sending signal. PID: 18165 SIG: 9
07-26 15:13:08.288 I/ACRA    (18113): Sending report /data/user/0/xyz.hisname.fireflyiii/app_ACRA-approved/2020-07-26T15:13:08.193+02:00.stacktrace
07-26 15:13:13.376 I/art     (18285): Starting a blocking GC AddRemoveAppImageSpace
07-26 15:13:13.379 W/System  (18285): ClassLoader referenced unknown path: /data/app/xyz.hisname.fireflyiii-1/lib/arm64
07-26 15:13:13.434 D/AppCompatDelegate(18285): Application config ({1.0 214mcc4mnc [en] ldltr sw399dp w399dp h687dp 288dpi nrml long port finger -keyb/v/h -nav/h s.7}) matches base context config, using empty base overlay
07-26 15:13:13.447 D/AppCompatDelegate(18285): Applying night mode using ContextThemeWrapper and applyOverrideConfiguration(). Config: {0.0 ?mcc?mnc ?localeList ?layoutDir ?swdp ?wdp ?hdp ?density ?lsize ?long ?orien ?uimode ?touch ?keyb/?/? ?nav/?}
07-26 15:13:13.461 D/AppCompatDelegate(18285): updateForNightMode [allowRecreation:false, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:false, canReturnDifferentContext:true, host:xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a]
07-26 15:13:13.461 D/AppCompatDelegate(18285): updateForNightMode not recreating Activity: xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a
07-26 15:13:13.461 D/AppCompatDelegate(18285): updateForNightMode. Skipping. Night mode: -1 for host:xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a
07-26 15:13:13.471 D/AppCompatDelegate(18285): setDefaultNightMode. New:1, Current:-100
07-26 15:13:13.471 D/AppCompatDelegate(18285): applyDayNightToActiveDelegates. Applying to androidx.appcompat.app.h@aa9e3f2
07-26 15:13:13.471 D/AppCompatDelegate(18285): updateForNightMode [allowRecreation:true, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:true, canReturnDifferentContext:true, host:xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a]
07-26 15:13:13.472 D/AppCompatDelegate(18285): updateForNightMode not recreating Activity: xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a
07-26 15:13:13.472 D/AppCompatDelegate(18285): updateForNightMode. Skipping. Night mode: 1 for host:xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a
07-26 15:13:13.510 I/ACRA    (18285): ACRA is enabled for xyz.hisname.fireflyiii, initializing...
07-26 15:13:13.544 W/b       (18285): Use a non-transparent color for the default color as it will be used to finish ripple animations.
07-26 15:13:13.568 W/b       (18285): Use a non-transparent color for the default color as it will be used to finish ripple animations.
07-26 15:13:13.741 D/NetworkSecurityConfig(18285): Using Network Security Config from resource network_security_config debugBuild: false
07-26 15:13:13.926 I/art     (18285): Do partial code cache collection, code=30KB, data=25KB
07-26 15:13:13.926 I/art     (18285): After code cache collection, code=29KB, data=25KB
07-26 15:13:13.926 I/art     (18285): Increasing code cache capacity to 128KB
07-26 15:13:14.068 D/AppCompatDelegate(18285): updateForNightMode [allowRecreation:true, currentNightMode:16, newNightMode:16, activityHandlingUiMode:false, baseContextAttached:true, created:true, canReturnDifferentContext:true, host:xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a]
07-26 15:13:14.068 D/AppCompatDelegate(18285): updateForNightMode not recreating Activity: xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a
07-26 15:13:14.068 D/AppCompatDelegate(18285): updateForNightMode. Skipping. Night mode: 1 for host:xyz.hisname.fireflyiii.ui.HomeActivity@6ff7b9a
07-26 15:13:14.185 I/art     (18285): Do partial code cache collection, code=60KB, data=57KB
07-26 15:13:14.186 I/art     (18285): After code cache collection, code=60KB, data=57KB
07-26 15:13:14.186 I/art     (18285): Increasing code cache capacity to 256KB
07-26 15:13:14.467 I/art     (18285): Do full code cache collection, code=125KB, data=115KB
07-26 15:13:14.468 I/art     (18285): Starting a blocking GC JitCodeCache
07-26 15:13:14.468 I/art     (18285): After code cache collection, code=74KB, data=68KB
07-26 15:13:14.594 I/Adreno-EGL(18285): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8937_64_LA.UM.5.5.R1__release_AU (I23cc4685e6)
07-26 15:13:14.594 I/Adreno-EGL(18285): OpenGL ES Shader Compiler Version: XE031.09.00.04
07-26 15:13:14.594 I/Adreno-EGL(18285): Build Date: 04/11/17 Tue
07-26 15:13:14.594 I/Adreno-EGL(18285): Local Branch: 
07-26 15:13:14.594 I/Adreno-EGL(18285): Remote Branch: quic/gfx-adreno.lnx.1.0.r5-rel
07-26 15:13:14.594 I/Adreno-EGL(18285): Local Patches: NONE
07-26 15:13:14.594 I/Adreno-EGL(18285): Reconstruct Branch: NOTHING
07-26 15:13:14.598 I/OpenGLRenderer(18285): Initialized EGL, version 1.4
07-26 15:13:14.599 D/OpenGLRenderer(18285): Swap behavior 1
07-26 15:13:14.694 W/RecyclerView(18285): No adapter attached; skipping layout
07-26 15:13:14.808 I/art     (18285): Do partial code cache collection, code=124KB, data=118KB
07-26 15:13:14.808 I/art     (18285): After code cache collection, code=98KB, data=102KB
07-26 15:13:14.808 I/art     (18285): Increasing code cache capacity to 512KB
07-26 15:13:14.934 I/Choreographer(18285): Skipped 47 frames!  The application may be doing too much work on its main thread.
07-26 15:13:15.147 D/AndroidRuntime(18285): Shutting down VM
07-26 15:13:15.148 E/ACRA    (18285): ACRA caught a IndexOutOfBoundsException for xyz.hisname.fireflyiii
07-26 15:13:15.148 E/ACRA    (18285): java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
07-26 15:13:15.148 E/ACRA    (18285): 	at java.util.ArrayList.get(ArrayList.java:411)
07-26 15:13:15.148 E/ACRA    (18285): 	at xyz.hisname.fireflyiii.ui.h.a$e.a(LiveData.kt:2)
07-26 15:13:15.148 E/ACRA    (18285): 	at androidx.lifecycle.LiveData.b(LiveData.java:6)
07-26 15:13:15.148 E/ACRA    (18285): 	at androidx.lifecycle.LiveData.c(LiveData.java:8)
07-26 15:13:15.148 E/ACRA    (18285): 	at androidx.lifecycle.LiveData.m(LiveData.java:4)
07-26 15:13:15.148 E/ACRA    (18285): 	at androidx.lifecycle.v.m(MutableLiveData.java:1)
07-26 15:13:15.148 E/ACRA    (18285): 	at androidx.lifecycle.LiveData$a.run(LiveData.java:5)
07-26 15:13:15.148 E/ACRA    (18285): 	at android.os.Handler.handleCallback(Handler.java:751)
07-26 15:13:15.148 E/ACRA    (18285): 	at android.os.Handler.dispatchMessage(Handler.java:95)
07-26 15:13:15.148 E/ACRA    (18285): 	at android.os.Looper.loop(Looper.java:154)
07-26 15:13:15.148 E/ACRA    (18285): 	at android.app.ActivityThread.main(ActivityThread.java:6186)
07-26 15:13:15.148 E/ACRA    (18285): 	at java.lang.reflect.Method.invoke(Native Method)
07-26 15:13:15.148 E/ACRA    (18285): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
07-26 15:13:15.148 E/ACRA    (18285): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
IS_SILENT=false
USER_CRASH_DATE=2020-07-26T15:13:15.170+02:00
```
In response to the comments above:
- I have Euro as default currency in the server, not sure whether the mobile client app is well configured as I can no longer access it. 
- I tried as @david-lindner to re-install with new personal access token but to no success

Can you tell me if there is anything else I should do to help debug the issue? 
Thanks for the great app!

**Comment by emansih** [comment]
You are using the old version of the app
